import { buildTopic, references, sourced } from "@/content/authoring";
import {
  AAST_ACS_DCR_PROTOCOL_SOURCE as DCR,
  PROPPR_TRIAL_SOURCE as PROPPR,
  TRAUMA_LAPAROTOMY_PACKET_SOURCE as PACKET,
  UK_REBOA_TRIAL_SOURCE as REBOA,
  WSES_AAST_DUODENOPANCREATIC_SOURCE as WSES_DP,
  WSES_BOWEL_INJURY_SOURCE as WSES_BOWEL,
  WSES_LIVER_TRAUMA_SOURCE as WSES_LIVER,
} from "@/content/sources";
import type { TopicBlock } from "@/lib/types";

const blocks: TopicBlock[] = [
  sourced({
    id: "block-tlap-summary",
    type: "summary",
    heading: "At a glance",
    text: "Trauma laparotomy is one operation with one governing principle: **physiology over anatomy**. In a depleted patient an abbreviated operation with a planned return beats a technically perfect repair the patient does not survive, so the whole sequence is built to answer three questions in order — where is the bleeding, where is the contamination, and can this physiology tolerate anything more today. The unstable patient with a positive **FAST** goes to the operating room rather than the scanner, and the clock matters: delay in a decompensating patient buys mortality at roughly **1 percent every three minutes**. Almost everything else in this topic is a rule for deciding when to stop.",
  }, PACKET),
  sourced({
    id: "block-tlap-indications",
    type: "bullets",
    heading: "Indications for emergent laparotomy",
    items: [
      "**Hemodynamic instability with a positive FAST** — the classic exam-based trigger, and the one most often tested.",
      "**Peritonitis** on examination.",
      "**Evisceration** of intra-abdominal contents.",
      "**Diaphragmatic rupture** with intrathoracic herniation of viscera.",
      "**Impalement**, or persistent gastrointestinal hemorrhage.",
      "Penetrating trauma — a gunshot wound with **peritoneal violation** warrants laparotomy.",
      "- **Selective nonoperative management** applies only to the stable patient without peritonitis, and it is a commitment to serial examination rather than a decision to do nothing.",
    ],
  }, PACKET),
  sourced({
    id: "block-tlap-resuscitation",
    type: "bullets",
    heading: "Resuscitation and preparation",
    items: [
      "**Balanced resuscitation** — whole blood, or plasma, platelets, and red cells at **1:1:1**. Crystalloid is minimized because it drives trauma-induced coagulopathy and bowel edema.",
      "**Tranexamic acid within 3 hours** of injury: a **1 g** bolus over 10 minutes then **1 g** over 8 hours, or a single **2 g** dose. Earlier is better, and given after 3 hours it may increase mortality.",
      "Empiric **calcium** replacement, **fibrinogen** supplementation, and viscoelastic-guided correction with **TEG** or **ROTEM** once the audible bleeding is controlled.",
      "Prep **chin to mid-thigh** and midaxillary line to midaxillary line, so a sternotomy, a thoracotomy, or femoral access needs no re-prep.",
      "Suspected **tamponade** — prep and drape the awake patient before induction, because losing sympathetic tone on induction can collapse them on the table.",
      "Suspected **rectal injury** — modified lithotomy if there is time, to allow proctoscopy.",
    ],
  }, DCR),
  sourced({
    id: "block-tlap-sequence",
    type: "sequence",
    heading: "The first minutes in the abdomen",
    steps: [
      { title: "Incise", detail: "**Midline, xiphoid to pubis.** Exposure and speed beat every other consideration." },
      { title: "Eviscerate and evacuate", detail: "Deliver the small bowel and scoop out blood and clot until you can see where the bleeding comes from." },
      { title: "Pack", detail: "**Directed packing** to the quadrant that is actually bleeding. Reserve all four quadrants for genuinely multi-site hemorrhage." },
      { title: "Compress", detail: "Manual pressure on active bleeders, and a deliberate pause while anesthesia catches up on volume." },
      { title: "Take the aorta if you must", detail: "For refractory hypotension, open the gastrohepatic ligament, palpate the aorta at the hiatus between the crura, and compress or clamp it **supraceliac**." },
    ],
  }, PACKET),
  sourced({
    id: "block-tlap-zones",
    type: "table",
    heading: "Retroperitoneal zones — explore or observe",
    columns: ["Zone", "Contents", "Blunt", "Penetrating"],
    rows: [
      ["Zone 1, central", "Aorta, **IVC**, celiac axis, **SMA** and SMV", "**Explore** — mandatory whatever the hematoma looks like", "**Explore** — mandatory, exactly as for blunt injury"],
      ["Zone 2, flank and perirenal", "Kidney, renal vessels, ureter, colon", "**Leave a nonexpanding hematoma alone.** Open it for rupture, pulsatility, expansion, or persistent instability", "**May be explored**, accepting a higher rate of renal and ureteral injury; an isolated low-grade renal injury already staged on CT can be observed"],
      ["Zone 3, pelvic", "Iliac vessels, presacral venous plexus", "**Do not open it** — preperitoneal packing, pelvic stabilization, and angioembolization instead", "Explore for hard signs or an expanding hematoma; consider endovascular control if the patient is stable"],
    ],
  }, PACKET),
  sourced({
    id: "block-tlap-universal-rule",
    type: "warning",
    tone: "danger",
    heading: "The rule that overrides the zones",
    text: "Any hematoma that is **expanding, pulsatile, or ruptured** is explored, whatever the zone and whatever the mechanism. The zone table decides what to do about a hematoma that is sitting still; it never licenses leaving one that is growing.",
  }, PACKET),
  sourced({
    id: "block-tlap-maneuvers",
    type: "table",
    heading: "Exposure maneuvers",
    columns: ["Maneuver", "What is mobilized", "What it exposes"],
    rows: [
      ["Left medial visceral rotation (Mattox)", "Left colon, spleen, tail of pancreas, and left kidney swung to the right", "Aorta from the hiatus down, celiac axis, **SMA**, left renal vessels"],
      ["Right medial visceral rotation (Cattell-Braasch)", "Right colon and the small bowel mesentery swung to the left", "Infrahepatic **IVC**, infrarenal aorta, and the right retroperitoneum"],
      ["Extended Kocher", "Duodenum reflected medially off its lateral peritoneal attachment", "**D2 through D4**, the pancreatic head, and the retrohepatic cava"],
      ["Gastrocolic division", "Greater omentum taken off the transverse colon", "Lesser sac — the posterior wall of the stomach and the body of the pancreas"],
    ],
  }, PACKET),
  sourced({
    id: "block-tlap-organs",
    type: "table",
    heading: "Organ-specific management",
    columns: ["Organ", "What the index operation is", "The trap"],
    rows: [
      ["Liver", "Perihepatic packing, **Pringle** for inflow, and resectional debridement only", "Packing **inside** a deep laceration instead of compressing the lobe around it"],
      ["Small bowel", "Under **50 percent** of the circumference, transverse primary repair; at or beyond it, resection with primary anastomosis", "Missing the **mesenteric devascularization** that dooms a segment you just repaired"],
      ["Colon", "Primary repair, or resection with anastomosis, for most injuries", "Reaching for a colostomy by reflex rather than for shock, heavy contamination, or an ongoing transfusion requirement"],
      ["Rectum", "Intraperitoneal, treat as colon; extraperitoneal and destructive, **proximal fecal diversion**", "Adding distal washout and presacral drains to the diversion"],
      ["Stomach", "Open the **lesser sac**, inspect the posterior wall, then two-layer repair", "Closing after finding only the anterior hole"],
      ["Duodenum", "Tension-free primary repair after wide exposure, even for most high-grade lacerations", "**Pyloric exclusion**, which has never been shown to reduce leak and does lengthen the stay"],
      ["Pancreas", "Decided by **main duct** integrity and position relative to the **SMV**", "Suture repair of a low-grade injury, which raises the pseudocyst rate above simple drainage"],
    ],
  }, PACKET),
  sourced({
    id: "block-tlap-liver",
    type: "bullets",
    heading: "↳ Liver, when packing is not enough",
    items: [
      "The **Pringle maneuver** clamps the hepatoduodenal ligament and so controls hepatic arterial and portal venous inflow — everything entering the liver.",
      "Bleeding that continues through a correctly applied Pringle is coming from somewhere the Pringle cannot reach: the **retrohepatic IVC** or the **hepatic veins**.",
      "For that injury, mobilize the lobe, pack, and consider **total hepatic vascular isolation**, an atriocaval **Schrock shunt**, or a combined balloon occlusion of the aorta and cava. Direct repair of the injured vein carries a high mortality.",
      "**Avoid major anatomic resection** at the index operation. Debride what is destroyed, and send persistent arterial blush to angioembolization.",
    ],
  }, WSES_LIVER),
  sourced({
    id: "block-tlap-duodenopancreatic",
    type: "bullets",
    heading: "↳ Duodenum and pancreas",
    items: [
      "A **duodenal hematoma** without perforation is managed nonoperatively with nasogastric decompression and nutrition. Operate if the obstruction has not resolved by about **14 days**, or if the wall is perforated.",
      "Routine **periduodenal drainage** is unnecessary when the pancreas is uninjured.",
      "An unreconstructable duodenum needs resection with **duodenoduodenostomy** or a **Roux-en-Y duodenojejunostomy**.",
      "**Pancreaticoduodenectomy** is reserved for massive combined duodenopancreatic or ampullary destruction, and is ideally staged behind a damage control operation rather than done at the index laparotomy.",
      "Pancreatic **grades I and II**, with the duct intact, need closed-suction drainage and nothing more.",
      "**Grade III** — a distal duct injury left of the SMV — is a distal pancreatectomy, with or without splenectomy.",
      "**Grades IV and V** — proximal, ductal, or ampullary — come down to drainage versus a staged Whipple, and drainage of these grades carries the higher rate of pancreas-related complications.",
    ],
  }, WSES_DP),
  sourced({
    id: "block-tlap-hollow-viscus",
    type: "bullets",
    heading: "↳ Hollow viscus",
    items: [
      "**Primary repair or anastomosis is preferred wherever it is feasible**, and the burden of proof now sits on diverting rather than on repairing.",
      "Multiple lacerations close together are treated as one destructive segment and resected, rather than repaired one at a time.",
      "The stomach hides its second hole behind the **lesser sac**, which is why the posterior wall is inspected rather than assumed.",
      "Divert for **profound shock**, heavy fecal contamination, or an ongoing transfusion and pressor requirement — physiology, not the injury grade, drives that call.",
    ],
  }, WSES_BOWEL),
  sourced({
    id: "block-tlap-damage-control",
    type: "flow",
    heading: "Damage control decision",
    nodes: [
      { id: "controlled", label: "Hemorrhage and contamination controlled" },
      { id: "holds", label: "Warm, correcting, and clotting", tone: "good" },
      { id: "fails", label: "Lethal triad, or sheer transfusion burden", tone: "caution" },
      { id: "definitive", label: "Definitive repair and fascial closure at this operation", tone: "good" },
      { id: "abbreviate", label: "Abbreviate — ligate or shunt, staple the bowel closed, pack, temporary abdominal closure", tone: "caution" },
      { id: "icu", label: "ICU: rewarm, correct acidosis and coagulopathy, restore euvolemia, monitor bladder pressure" },
      { id: "relook", label: "Return at 24 to 48 hours, or when the trends say so rather than the clock" },
      { id: "close", label: "Definitive anastomosis or ostomy, and attempt fascial closure at every look", tone: "good" },
    ],
    edges: [
      { from: "controlled", to: "holds", label: "physiology holds" },
      { from: "controlled", to: "fails", label: "physiology fails" },
      { from: "holds", to: "definitive" },
      { from: "fails", to: "abbreviate" },
      { from: "abbreviate", to: "icu" },
      { from: "icu", to: "relook" },
      { from: "relook", to: "close" },
    ],
  }, PACKET),
  sourced({
    id: "block-tlap-dcs-triggers",
    type: "bullets",
    heading: "Damage control triggers",
    items: [
      "**Hypothermia** — classically below **35 °C**, with expert criteria putting the line nearer **34 °C**.",
      "**Acidosis** — a **pH below 7.2**, with a rising base deficit alongside it.",
      "**Coagulopathy** — non-mechanical bleeding you can see in the field, an **INR above 1.5**, or an abnormal TEG or ROTEM.",
      "More than **10 units** of packed red cells.",
      "Combined **vascular and hollow viscus** injury.",
      "Fascia that cannot be closed without producing compartment syndrome.",
      "The counterweight: **damage control used on a moderately injured patient increases morbidity**, so the triggers are permission to abbreviate, not an instruction to.",
    ],
  }, PACKET),
  sourced({
    id: "block-tlap-dcs-phases",
    type: "sequence",
    heading: "↳ The three phases",
    steps: [
      { title: "Phase 1, in the operating room", detail: "Hemorrhage control by ligation, shunt, or packing; contamination control by stapled resection with the bowel left in discontinuity; then a negative-pressure **temporary abdominal closure**. Keep it short — the point of the phase is to end it." },
      { title: "Phase 2, in the intensive care unit", detail: "Rewarm, correct the acidosis and coagulopathy, restore euvolemia, and monitor bladder pressure for the compartment syndrome this patient is now at risk of." },
      { title: "Phase 3, the return", detail: "Definitive anastomosis or ostomy and early primary fascial closure. Attempt the fascia at **every** re-look, because bedside examination does not predict closability; neuromuscular blockade and vacuum-assisted devices both improve the odds." },
    ],
  }, PACKET),
  sourced({
    id: "block-tlap-acs",
    type: "table",
    heading: "Intra-abdominal hypertension and compartment syndrome",
    columns: ["State", "Bladder pressure", "What it calls for"],
    rows: [
      ["Normal", "**0 to 5 mm Hg**", "Nothing beyond continued measurement in an abdomen at risk"],
      ["Intra-abdominal hypertension", "**12 mm Hg** or above", "Medical optimization — sedation, neuromuscular blockade, gastric and rectal decompression, crystalloid restriction, and drainage of free fluid"],
      ["Abdominal compartment syndrome", "**Above 20 mm Hg** with new end-organ dysfunction", "**Decompressive laparotomy** — the gold standard — with a temporary abdominal closure"],
    ],
  }, PACKET),
  sourced({
    id: "block-tlap-acs-detail",
    type: "bullets",
    heading: "↳ Measuring it, and living with the open abdomen",
    items: [
      "Measure by transducing a **bladder catheter** after instilling about **25 mL** of sterile saline, with the patient supine and the reading taken at end-expiration.",
      "The organ effects follow the pressure: oliguria from renal vein and parenchymal compression, high peak airway pressures and hypoxia, reduced venous return and cardiac output, and a rising intracranial pressure.",
      "The open abdomen has its own complication set — **entero-atmospheric fistula**, lateral fascial retraction, and a giant ventral hernia — managed with serial fascial traction, component separation, or bridging mesh and a planned hernia.",
      "**Prevention beats treatment.** Timely hemorrhage control and low-crystalloid hemostatic resuscitation prevent most postinjury compartment syndrome.",
    ],
  }, PACKET),
  sourced({
    id: "block-tlap-reboa",
    type: "bullets",
    heading: "REBOA — an adjunct, not a cure",
    items: [
      "**Zone 1 REBOA** is an option in the exsanguinating patient bleeding below the diaphragm, as a bridge to definitive hemorrhage control.",
      "The **UK-REBOA** trial found no mortality benefit, and a signal toward harm, when emergency department REBOA was added to standard care. Select carefully and keep the occlusion time short.",
      "**Partial and intermittent** occlusion reduces distal ischemia in preclinical models, and is the direction the technique is moving.",
      "**Resuscitative thoracotomy** with aortic cross-clamping is the different, more desperate tool: traumatic arrest with signs of life, cardiac motion, or tamponade on FAST.",
    ],
  }, REBOA),
  sourced({
    id: "block-tlap-splits",
    type: "table",
    heading: "Board answer versus current practice",
    columns: ["Question", "Board answer", "Current practice"],
    rows: [
      ["Working up the unstable abdomen", "**DPL** in the hypotensive blunt trauma patient", "**FAST** and E-FAST have all but replaced it. A hypotensive trauma patient does not belong in the CT suite"],
      ["Transfusion ratio", "**1:1:1** plasma, platelets, and red cells", "PROPPR found better hemostasis and fewer exsanguination deaths at 1:1:1, but **no significant mortality difference** at 24 hours or 30 days, and the 2023 European guideline still permits a plasma to red cell ratio of at least 1:2. This one is genuinely unsettled — 1:1:1 remains the practical target rather than the proven one"],
      ["Packing the bleeding abdomen", "Routine **four-quadrant packing**", "Directed packing to the bleeding quadrant performs as well and costs less time and fewer iatrogenic injuries. Only about **15 percent** of hemorrhaging laparotomies truly need all four"],
      ["Colon injury", "**Diversion** for all of them", "Primary repair or resection with anastomosis for most, and an EAST multicenter trial favored repair over resection for **AAST grades I and II**"],
      ["Rectal injury", "The **three Ds** — diversion, distal washout, presacral drainage", "Diversion alone. Washout and presacral drains have been largely abandoned in civilian practice"],
      ["Duodenal injury", "**Diverticulization** and triple-tube decompression", "Tension-free primary repair, with pyloric exclusion set aside as unproven and costly in length of stay"],
      ["REBOA", "A bridge for the exsanguinating patient bleeding below the diaphragm", "The same, with a real caution attached: **UK-REBOA** showed no benefit and a signal toward harm in the emergency department setting"],
    ],
  }, PACKET),
  sourced({
    id: "block-tlap-pearls",
    type: "bullets",
    heading: "Board pearls",
    items: [
      "Unstable with a positive **FAST** goes to the operating room, not to CT.",
      "A **Pringle** that fails means retrohepatic **IVC** or hepatic vein injury.",
      "An **expanding or pulsatile** retroperitoneal hematoma is explored, whatever the mechanism.",
      "Blunt **zone 2** and nonexpanding, leave it. Blunt **zone 3**, pack and embolize rather than open.",
      "The **50 percent rule** — under half the circumference, primary repair; at or beyond half, resection with anastomosis.",
      "**TXA** only inside 3 hours, and later than that it may increase mortality.",
      "Routine colostomy, the rectal three Ds, duodenal diverticulization, and routine pyloric exclusion are all out. **Primary repair with selective diversion** is in.",
      "A distal pancreatic duct injury **left of the SMV** is a distal pancreatectomy. A Whipple is only for destructive head and duodenal injury, staged.",
      "**Compartment syndrome** is a pressure above 20 mm Hg plus organ dysfunction, and the answer is a decompressive laparotomy.",
    ],
  }, PACKET),
  references("block-tlap-references", [PACKET, WSES_LIVER, WSES_BOWEL, WSES_DP, PROPPR, REBOA, DCR]),
];

export const abdominalExplorationForTraumaTopic = buildTopic({
  id: "00000000-0000-4000-8000-000000001210",
  versionId: "00000000-0000-4000-8000-000000001220",
  slug: "abdominal-exploration-for-trauma",
  title: "Abdominal Exploration for Trauma",
  aliases: ["trauma laparotomy", "exploratory laparotomy for trauma", "ex lap trauma", "damage control laparotomy", "damage control surgery", "lethal triad", "retroperitoneal zones", "zone 1 hematoma", "zone 2 hematoma", "zone 3 hematoma", "Mattox maneuver", "Cattell-Braasch", "extended Kocher", "Pringle maneuver", "Schrock shunt", "atriocaval shunt", "REBOA", "UK-REBOA", "PROPPR", "TXA", "tranexamic acid", "massive transfusion protocol", "50% rule", "pyloric exclusion", "duodenal injury", "pancreatic trauma", "colon injury", "rectal injury", "three Ds", "open abdomen", "temporary abdominal closure", "abdominal compartment syndrome", "intra-abdominal hypertension", "FAST", "selective nonoperative management", "SNOM", "four-quadrant packing"],
  scoreNodeId: "trauma-procedures",
  scoreCategory: "SCORE · Trauma · Operations & Procedures",
  tags: ["trauma", "damage-control", "operative-technique", "emergency", "critical-care", "absite", "score"],
  sourceId: PACKET,
  additionalSourceIds: [WSES_LIVER, WSES_BOWEL, WSES_DP, PROPPR, REBOA, DCR],
  blocks,
  reviewedAt: "2026-08-18T00:00:00.000Z",
});
