import { buildTopic, references, sourced } from "@/content/authoring";
import { TRAUMA_CHEST_WALL_PLEURA_DIAPHRAGM_PACKET_SOURCE as PACKET } from "@/content/sources";
import type { TopicBlock } from "@/lib/types";

const blocks: TopicBlock[] = [
  sourced({
    id: "block-cwpd-summary",
    type: "summary",
    heading: "At a glance",
    text: "Chest wall, pleural, and diaphragmatic injuries share one exam thread: several of the classic teaching points have been revised by trials and guideline updates published within the last two years, so the board answer and the current answer now genuinely diverge in places. Anatomy sets the traps — the neurovascular bundle runs under the inferior rib, the phrenic nerve branches radially across the diaphragm, and a chest tube placed too low risks a transdiaphragmatic injury. Pleural space emergencies are driven by numeric thresholds worth memorizing cold: what volume of hemothorax can be observed, what triggers a thoracotomy, and when retained hemothorax needs VATS rather than a second tube. Chest wall trauma turns on the flail segment versus flail chest distinction and on how liberally to fix displaced ribs, a question a 2026 randomized trial just answered more narrowly than prior teaching. Diaphragmatic injury turns on timing — acute repairs go through the abdomen, chronic repairs go through the chest — and on a diagnostic trap: normal imaging does not exclude an occult tear in a penetrating thoracoabdominal wound.",
  }, PACKET),
  sourced({
    id: "block-cwpd-anatomy-danger-zones",
    type: "bullets",
    heading: "Danger-zone anatomy",
    items: [
      "The intercostal neurovascular bundle runs in the costal groove along the **inferior border of each rib**, ordered superior to inferior as **Vein–Artery–Nerve (VAN)**; instruments, chest tubes, and thoracentesis needles all pass immediately over the **superior margin of the lower rib** to avoid it.",
      "Needle decompression for tension pneumothorax is landmarked at the **2nd intercostal space, midclavicular line**, localized off the angle of Louis (sternomanubrial joint); the WSES-AAST guideline lists the **5th intercostal space, midaxillary line** as an accepted alternative site, reflecting adult chest-wall thickness data.",
      "The safe triangle for tube thoracostomy is the **4th to 5th intercostal space, anterior-to-mid axillary line**; placing the tube lower risks a transdiaphragmatic intra-abdominal injury because diaphragmatic excursion is variable.",
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-diaphragm-anatomy",
    type: "bullets",
    heading: "Diaphragmatic hiatuses and phrenic anatomy",
    items: [
      "Mnemonic \"I ate ten eggs at twelve\" for the three major hiatuses: the **IVC at T8**, the **esophagus and vagus nerve at T10**, and the **aorta, thoracic duct, and azygos vein at T12**.",
      "The **phrenic vein** courses roughly 1 cm above the esophageal hiatus and is a major bleeding source during hiatal mobilization.",
      "The **phrenic nerve (C3 to C5)** runs anterior to the lung hilum directly on the pericardium, then branches centrifugally on the caudal diaphragmatic surface into anterior, posterior, and two lateral branches; repair sutures must run parallel to these radial branches to avoid hemidiaphragm paralysis.",
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-pearls-table",
    type: "table",
    heading: "Pleural emergencies: clues and the board trigger",
    columns: ["Condition", "Classic clues", "Emergent management / board trigger"],
    rows: [
      ["Tension pneumothorax", "Hypotension, JVD, absent breath sounds, contralateral tracheal deviation", "Clinical diagnosis — do not wait for CXR; immediate needle or finger decompression, then tube thoracostomy"],
      ["Open (\"sucking\") chest wound", "Defect ≥ 2/3 the diameter of the trachea — air preferentially enters the wound", "Three-sided occlusive dressing (flutter valve), then chest tube at a separate site, then definitive closure"],
      ["Massive hemothorax", "Dullness, shock, opacified hemithorax with contralateral mediastinal shift", "Large-bore tube thoracostomy; thoracotomy once the volume or rate thresholds are met"],
      ["Retained hemothorax", "Persistent opacity or clot after a tube, confirmed on CT", "VATS evacuation, not a second chest tube"],
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-numeric-thresholds",
    type: "bullets",
    heading: "Pneumothorax and hemothorax: numeric thresholds to memorize",
    items: [
      "Supine CXR detects hemothorax once **200 to 300 mL** of blood is present.",
      "A small hemothorax **under 300 mL** in a stable patient can be observed (WSES-AAST); board-classic teaching says every hemothorax gets a tube.",
      "A hemothorax **≥ 500 mL** in a stable patient should be drained, optimally within **72 hours** (WSES-AAST 2025).",
      "Massive hemothorax is rapid loss of **more than 1500 mL** into the chest.",
      "Thoracotomy triggers: **≥ 1500 mL immediate output**, OR **≥ 200 mL/h for 2 to 4 consecutive hours**, OR an ongoing transfusion requirement to maintain stability.",
      "A small pneumothorax **≤ 2 cm** (apical rim ≤ 3.5 cm) in a stable patient is observed for **at least 24 hours**.",
      "An occult pneumothorax is one seen on CT but not on CXR; CT is the gold standard for detecting a small pneumothorax.",
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-shift-warning",
    type: "warning",
    tone: "danger",
    heading: "Contralateral versus ipsilateral mediastinal shift",
    text: "Fluid or blood in the chest — hemothorax or tension physiology — pushes the mediastinum to the **opposite** side. Complete lung collapse or atelectasis instead **pulls** mediastinal structures toward the **affected** side. Reading the shift the wrong way flips the diagnosis.",
  }, PACKET),
  sourced({
    id: "block-cwpd-pleural-flow",
    type: "flow",
    heading: "Pleural space injury: from presentation to VATS",
    nodes: [
      { id: "present", label: "Chest trauma with suspected pneumothorax or hemothorax" },
      { id: "tension", label: "Tension physiology: hypotension, JVD, absent breath sounds, contralateral tracheal deviation", tone: "caution" },
      { id: "decompress", label: "Immediate needle or finger decompression, then tube thoracostomy — a clinical diagnosis, do not wait for imaging", tone: "good" },
      { id: "noTension", label: "No tension physiology: obtain CXR or CT" },
      { id: "smallPtx", label: "Small pneumothorax ≤ 2 cm (apical rim ≤ 3.5 cm), stable" },
      { id: "observePtx", label: "Observe for at least 24 hours", tone: "good" },
      { id: "smallHtx", label: "Small hemothorax under 300 mL, stable" },
      { id: "observeHtx", label: "Observation acceptable (WSES-AAST)", tone: "good" },
      { id: "drainHtx", label: "Hemothorax ≥ 500 mL, stable" },
      { id: "drain", label: "Tube thoracostomy, optimally within 72 hours" },
      { id: "massive", label: "Massive hemothorax: ≥ 1500 mL immediate output, ≥ 200 mL/h for 2 to 4 hours, or ongoing transfusion requirement", tone: "caution" },
      { id: "thoracotomy", label: "Emergent thoracotomy", tone: "caution" },
      { id: "retained", label: "Retained hemothorax after tube thoracostomy", tone: "caution" },
      { id: "vats", label: "Early VATS, within roughly 4 days — not a second chest tube", tone: "good" },
    ],
    edges: [
      { from: "present", to: "tension" },
      { from: "present", to: "noTension" },
      { from: "tension", to: "decompress" },
      { from: "noTension", to: "smallPtx" },
      { from: "noTension", to: "smallHtx" },
      { from: "noTension", to: "drainHtx" },
      { from: "noTension", to: "massive" },
      { from: "smallPtx", to: "observePtx" },
      { from: "smallHtx", to: "observeHtx" },
      { from: "drainHtx", to: "drain" },
      { from: "massive", to: "thoracotomy" },
      { from: "drain", to: "retained" },
      { from: "retained", to: "vats" },
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-retained-hemothorax",
    type: "bullets",
    heading: "Retained hemothorax: timing and complications",
    items: [
      "**VATS, not a second chest tube**, is first-line for retained hemothorax.",
      "Optimal timing is **early VATS within roughly 4 days** (under 3.9 days) and within the first week; TQIP data show VATS before 3.9 days reduced pulmonary morbidity (**13% vs 17%**) and length of stay, and VATS within 7 days was the only modifiable factor lowering pulmonary morbidity (odds ratio 0.52).",
      "Early VATS within 5 days produced complete resolution in **87%** of cases, with an **11%** conversion-to-thoracotomy rate (ERS/ESTS, 2023).",
      "A 2024 TQIP analysis found each day of delay increased length of stay and infection risk but did **not** increase VATS failure, need for repeat procedure, or mortality — so evacuation can be delayed when clinically necessary.",
      "Post-traumatic empyema occurs in up to **25%** of retained hemothoraces, and residual blood **over 300 mL** raises empyema risk; antibiotic prophylaxis is indicated when draining a retained hemothorax.",
      "Intrapleural fibrinolytics are reserved for high operative-risk patients and are associated with longer length of stay and no proven superiority to VATS.",
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-hemothorax-board-note",
    type: "prose",
    heading: "Board answer versus current practice",
    text: "Board-classic teaching holds that every hemothorax gets a chest tube. WSES-AAST now permits observation of a small hemothorax under 300 mL in a hemodynamically stable patient. Know both: the keyed answer on an exam that has not caught up is still \"drain it,\" but the guideline-driven answer for a genuinely small, stable collection is observation.",
  }, PACKET),
  sourced({
    id: "block-cwpd-flail-definitions",
    type: "bullets",
    heading: "Flail chest: definitions and pathophysiology",
    items: [
      "Flail **segment** is a radiographic finding: **3 or more consecutive ribs**, each fractured in **2 or more places**.",
      "Flail **chest** is a clinical finding: paradoxical movement of that segment with respiration (WSES/CWIS, 2024); paradoxical motion is **not** required to diagnose the underlying flail segment.",
      "The primary driver of hypoxemia is the underlying **pulmonary contusion**, producing a right-to-left intrapulmonary shunt, not the chest-wall mechanics alone; contused lung is exquisitely fluid-sensitive, so resuscitation should be judicious.",
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-nonop",
    type: "bullets",
    heading: "Nonoperative management of chest wall trauma",
    items: [
      "Nonoperative management is the cornerstone for most patients: **multimodal analgesia**, with thoracic epidural or paravertebral block preferred over IV opioids alone.",
      "Aggressive **pulmonary toilet** and incentive spirometry.",
      "**Judicious fluids**, given contused lung's fluid sensitivity, plus NIV or invasive ventilation as needed.",
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-ssrf-indications",
    type: "bullets",
    heading: "Surgical stabilization of rib fractures (SSRF): indications",
    items: [
      "**Flail chest in a hemodynamically stable patient** — the strongest evidence base for SSRF.",
      "**3 or more ipsilateral, severely displaced fractures** (ribs 3 to 10), especially with failure to wean or poor ventilatory response.",
      "Severely displaced or comminuted fractures encountered during a **thoracotomy done for another injury**.",
      "**Progressive pulmonary deterioration** or intractable pain despite multimodal analgesia.",
      "**Significant chest-wall deformity, nonunion, or chronic flail segment**, or a symptomatic chest-wall defect with lung herniation.",
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-ssrf-contraindications",
    type: "bullets",
    heading: "SSRF: contraindications and cautions",
    items: [
      "**Hemodynamic instability is an absolute contraindication.**",
      "Traumatic brain or spinal cord injury and pulmonary contusion are **no longer absolute contraindications** — they are now case-by-case; board-classic teaching still wrongly lists contusion as a contraindication.",
      "Relative cautions: advanced age, severe cardiopulmonary comorbidity, active malignancy, empyema, or prior chest radiation.",
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-ssrf-timing",
    type: "bullets",
    heading: "SSRF: timing",
    items: [
      "Perform SSRF within **48 to 72 hours** (WSES-AAST: high level of evidence); if delayed, within **3 to 7 days**.",
      "TQIP data show early SSRF — under 82 hours, or under 3 days — lowers pneumonia, ARDS, ventilator days, and length of stay.",
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-ssrf-board-note",
    type: "prose",
    heading: "Board answer versus current practice",
    text: "Randomized trials and meta-analyses show SSRF for flail chest reduces ventilator days, pneumonia, tracheostomy, and ICU length of stay, and is cost-effective; TQIP data put flail-chest mortality at 4.2% with SSRF versus 10.1% with nonoperative management, and board-classic teaching has extended that enthusiasm to fixing multiple displaced ribs liberally. The 2026 SOFRIB multicenter randomized trial tested exactly that extension — patients with 3 or more displaced ribs and compromise, pain, or deformity, but not classic flail chest — and found routine SSRF did **not** reduce ICU length of stay, while causing a **longer hospital stay (+3.3 days)** and **more pneumonia (11.4% vs 3.3%)**, despite improving pain and quality-of-life scores. The conclusion is selective, not routine, SSRF outside classic flail chest, where the evidence base remains strong.",
  }, PACKET),
  sourced({
    id: "block-cwpd-sternal",
    type: "bullets",
    heading: "Sternal fractures and blunt cardiac injury: screening",
    items: [
      "Sternal fracture carries a high association with blunt cardiac injury, thoracic-spine fracture, and head injury — screen with **ECG and troponin**.",
      "Board-classic teaching: a normal ECG plus normal troponin essentially rules out clinically significant blunt cardiac injury; if either is abnormal, obtain **24 to 48 hours of telemetry**, with echocardiography as needed. This remains the guideline answer for exams.",
      "Sternal fracture operative fixation is indicated for an unstable fracture, associated infection, chronic pain, or nonunion, using plates, intramedullary devices, bridging prostheses, or wires.",
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-bci-board-note",
    type: "prose",
    heading: "Board answer versus current practice",
    text: "The keyed exam answer is still that any abnormal ECG or troponin after a sternal fracture earns 24 to 48 hours of telemetry, with echocardiography added as needed. Current evidence complicates that reflex on two fronts: the optimal high-sensitivity troponin cutoff for clinically significant blunt cardiac injury is closer to **40 ng/L**, not the older 76 ng/L threshold, and multiple recent studies find severe cardiac complications after an isolated sternal fracture are rare — **under 2%** — with no tamponade or structural injury on echo despite an abnormal ECG or troponin, challenging mandatory telemetry and routine echo for isolated fractures with only minor abnormalities. Abnormal **ECG**, not troponin, is the stronger predictor of an adverse event in a stable patient.",
  }, PACKET),
  sourced({
    id: "block-cwpd-diaphragm-epi",
    type: "bullets",
    heading: "Diaphragmatic injury: epidemiology and mechanism",
    items: [
      "Diaphragmatic injury occurs in roughly **0.4 to 0.5%** of trauma; about **63%** is penetrating, and most injuries are **left-sided (roughly 80%)**.",
      "Blunt mechanism: a sudden rise in intra-abdominal pressure increases the pleuroperitoneal pressure gradient, producing large radial posterolateral tears, usually on the left because the liver protects the right.",
      "Penetrating mechanism produces small, focal tears; suspect diaphragmatic injury with any penetrating wound **below the nipple line or the 4th intercostal space** (the thoracoabdominal zone).",
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-diaphragm-diagnosis",
    type: "bullets",
    heading: "Diaphragmatic injury: diagnosis",
    items: [
      "CXR is insensitive, detecting only **25 to 70%** of injuries; suggestive findings are a gastric bubble or NG tube coiled in the left chest, or a blurred or elevated hemidiaphragm.",
      "Contrast-enhanced CT is the gold standard, with pooled sensitivity of roughly **0.80** and specificity of roughly **0.98** for blunt injury; right-sided injuries are frequently missed because the liver shields them, and nearly **half** of blunt injuries are not seen on preoperative CT.",
      "High-yield rule of thumb: a stable patient with a penetrating left thoracoabdominal wound and normal imaging still needs **diagnostic laparoscopy or VATS** to exclude an occult laceration, because a missed injury leads to a delayed diaphragmatic hernia.",
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-diaphragm-approach-table",
    type: "table",
    heading: "Operative approach by injury age",
    columns: ["Timing", "Approach", "Why"],
    rows: [
      ["Acute, under 1 week", "Abdominal (laparotomy or laparoscopy)", "Reduces herniated viscera and allows evaluation of associated intra-abdominal injuries"],
      ["Chronic or delayed, over 1 week", "Transthoracic (thoracotomy)", "Dense adhesions form between herniated viscera and intrathoracic structures"],
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-diaphragm-repair-steps",
    type: "sequence",
    heading: "Diaphragm repair, operative steps",
    steps: [
      { title: "Debride and evert", detail: "Debride nonviable edges and evert the borders for adequate approximation, using stay sutures or an Allis clamp." },
      { title: "Close primarily", detail: "Close with heavy, nonabsorbable or slowly absorbable monofilament suture — interrupted horizontal mattress, figure-of-eight, or running; no technique is proven superior." },
      { title: "Match the repair to the defect", detail: "Primary repair for tears 5 to 6 cm or smaller; figure-of-eight or mattress sutures for larger tears." },
      { title: "Reconstruct large central defects", detail: "Use prosthetic or biologic mesh (e.g., PTFE), or detach the peripheral costal insertions and re-anchor the diaphragm 2 to 3 interspaces cephalad, staying off the radial phrenic nerve branches." },
      { title: "Place a chest tube", detail: "Always place a chest tube after repair." },
      { title: "Anticipate insufflation physiology", detail: "During laparoscopic repair, abdominal insufflation can cause tension pneumothorax — anticipate needing a chest tube or conversion." },
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-diaphragm-outcomes",
    type: "bullets",
    heading: "Diaphragmatic injury: outcomes and complications",
    items: [
      "Mortality is roughly **15% for blunt** versus roughly **4% for penetrating** injury; overall reported mortality is **18 to 40%** and morbidity **40 to 60%**, driven mostly by associated injuries.",
      "Repair-specific complications include empyema, subphrenic abscess, dehiscence, and hemidiaphragm paralysis from phrenic nerve injury.",
    ],
  }, PACKET),
  sourced({
    id: "block-cwpd-diaphragm-warning",
    type: "warning",
    tone: "danger",
    heading: "Normal imaging does not clear a thoracoabdominal stab wound",
    text: "A stable patient with a penetrating left thoracoabdominal wound and a normal CT can still have an occult diaphragmatic laceration — CT misses nearly half of blunt injuries and is worse for penetrating tears. **Diagnostic laparoscopy or VATS is required to exclude the injury**, because a missed tear presents later as a delayed diaphragmatic hernia.",
  }, PACKET),
  sourced({
    id: "block-cwpd-rapid-recall",
    type: "bullets",
    heading: "Rapid recall: if X, think Y",
    items: [
      "**First-rib fracture** → think blunt aortic injury (**15 to 30%** frequency).",
      "**Widened mediastinum** (over 8 cm on a supine AP film) → CT angiography for aortic injury.",
      "**Sternal fracture** → think blunt cardiac injury plus thoracic-spine and head injury.",
      "Open chest wound **≥ 2/3 the tracheal diameter** → three-sided dressing before anything else.",
    ],
  }, PACKET),
  references("block-cwpd-references", [PACKET]),
];

export const chestWallPleuraAndDiaphragmInjuriesTopic = buildTopic({
  id: "00000000-0000-4000-8000-000000001219",
  versionId: "00000000-0000-4000-8000-000000001229",
  slug: "chest-wall-pleura-and-diaphragm-injuries",
  title: "Chest Wall, Pleura, and Diaphragm Injuries",
  aliases: ["chest wall injuries", "pleural injuries", "diaphragmatic injury", "diaphragm injury", "diaphragmatic rupture", "diaphragmatic hernia trauma", "flail chest", "flail segment", "rib fractures", "sternal fracture", "SSRF", "surgical stabilization of rib fractures", "pneumothorax", "tension pneumothorax", "hemothorax", "retained hemothorax", "massive hemothorax", "blunt cardiac injury", "BCI", "VATS", "video-assisted thoracoscopic surgery", "tube thoracostomy", "chest tube", "needle decompression", "safe triangle", "thoracic trauma", "pulmonary contusion", "SOFRIB", "absite", "score"],
  scoreNodeId: "trauma-conditions",
  scoreCategory: "SCORE · Trauma · Diseases & Conditions",
  tags: ["trauma", "chest-wall", "pleura", "diaphragm", "thoracic-trauma", "absite", "score"],
  sourceId: PACKET,
  blocks,
  reviewedAt: "2026-08-21T00:00:00.000Z",
});
