import { buildTopic, references, sourced } from "@/content/authoring";
import { CROHN_DISEASE_PACKET_SOURCE as PACKET } from "@/content/sources";
import type { TopicBlock } from "@/lib/types";

const blocks: TopicBlock[] = [
  sourced({
    id: "block-crohn-summary",
    type: "summary",
    heading: "At a glance",
    text: "Crohn disease is **transmural** inflammation that can appear anywhere from mouth to anus, and every peculiarity of its surgical management follows from that one word. Transmural inflammation makes **strictures, fistulae, abscesses, and phlegmon** instead of the mucosal bleeding that defines ulcerative colitis, which is why the operations are drainage and bowel-sparing resection rather than removal of the diseased organ. Nothing is curative — not medicine, not surgery — so the operation is always **anatomy-limited**: take out what is obstructing or perforating, take grossly normal margins and no more, and expect to be asked again. Recurrence is the rule rather than the complication, and the whole postoperative apparatus of risk stratification, prophylactic biologics, and a scope at six to twelve months exists because of it.",
  }, PACKET),
  sourced({
    id: "block-crohn-distribution",
    type: "bullets",
    heading: "Where it lives, and what drives it",
    items: [
      "**Terminal ileum and ileocecal region** is the commonest distribution, around **40 percent**, and is the segment most operations are performed on.",
      "**Isolated colonic disease** accounts for roughly **15 to 20 percent**.",
      "**Upper gastrointestinal disease** — gastroduodenal, esophageal, oral — is under **5 percent**.",
      "**Perianal disease** affects up to **30 percent** of patients with ileal disease and more than **50 percent** of those with colonic disease, which is why a fistula-in-ano in a young patient should raise the question.",
      "The mechanism is a **dysregulated mucosal immune response to gut microbiota in a genetically susceptible host** — an impaired epithelial barrier, defective bacterial clearance through **NOD2/CARD15** and **ATG16L1**, and dysbiosis.",
      "**Mesenteric \"creeping\" fat** and dysbiosis are not merely descriptive findings; both appear to drive **postoperative recurrence**, which is the argument behind extended mesenteric resection.",
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-pathology",
    type: "table",
    heading: "Gross versus microscopic pathology",
    columns: ["Feature", "Gross", "Microscopic"],
    rows: [
      ["Hallmarks", "**Creeping fat**, **skip lesions**, **cobblestoning**, thickened rubbery mesentery, enlarged nodes", "**Transmural inflammation**, deep fissuring ulcers, lymphoid aggregates"],
      ["Ulceration", "Longitudinal and serpiginous ulcers separating islands of preserved mucosa, which is what makes the cobblestone", "Fissures that track through muscularis propria toward serosa — the anatomic basis of fistula and abscess"],
      ["Granulomas", "Not visible", "**Noncaseating**, present in only about **30 to 50 percent**, and explicitly not required for the diagnosis"],
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-granuloma",
    type: "warning",
    heading: "A granuloma confirms Crohn; its absence excludes nothing",
    text: "This is the most reliably mis-answered pathology point in inflammatory bowel disease. **Noncaseating granulomas are classic but are found in a minority of specimens** — roughly 30 to 50 percent, and fewer on mucosal biopsy than on resection. Finding one settles the argument in favour of Crohn disease. **Not finding one settles nothing**, and a report of \"no granulomas identified\" is never grounds to reclassify a patient as ulcerative colitis. The diagnosis is made from the whole picture: distribution, depth, small-bowel involvement, perianal disease, and serology, with the granuloma as a bonus rather than a criterion.",
  }, PACKET),
  sourced({
    id: "block-crohn-vs-uc",
    type: "table",
    heading: "Crohn disease versus ulcerative colitis",
    columns: ["Factor", "Crohn disease", "Ulcerative colitis"],
    rows: [
      ["Distribution", "**Skip lesions** anywhere from mouth to anus, with rectal sparing common", "**Continuous** and confluent from the rectum proximally, without skip areas"],
      ["Depth of inflammation", "**Transmural**", "Mucosa and submucosa only"],
      ["Small bowel", "Terminal ileum frequently involved", "Spared, apart from backwash ileitis"],
      ["Fistula and stricture", "Common, and the two commonest reasons to operate", "Rare — a stricture here should raise suspicion of cancer"],
      ["Perianal disease", "**30 to 50 percent** and higher with colonic involvement", "Uncommon"],
      ["Granulomas", "**Noncaseating**, in about 30 to 50 percent", "Absent; crypt abscesses instead"],
      ["Smoking", "**Increases** incidence and severity", "**Protective** — the classic testable inversion"],
      ["Serology", "ASCA positive, p-ANCA negative", "p-ANCA positive, ASCA negative"],
      ["Does proctocolectomy cure it?", "No — disease recurs proximally and an ileal pouch is contraindicated", "Yes, for the intestinal disease, because inflammation never leaves the colon and rectum"],
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-epidemiology",
    type: "bullets",
    heading: "Epidemiology, genetics, and risk",
    items: [
      "**Bimodal age distribution**, peaking around **15 to 25** and again around **55 to 65 years**, with a roughly equal sex ratio.",
      "**NOD2/CARD15** is the best-established susceptibility gene; **IL23R** and **ATG16L1** also contribute, and first-degree relative risk is elevated.",
      "**Ashkenazi Jewish ancestry** is over-represented.",
      "**Cigarette smoking is the highest-yield modifiable risk factor** — it raises incidence, worsens severity, and is one of the three strongest predictors of postoperative recurrence.",
      "**NSAIDs** and a Western diet are the other environmental contributors usually named.",
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-presentation",
    type: "bullets",
    heading: "Presentation and extraintestinal manifestations",
    items: [
      "Core symptoms are **crampy abdominal pain, chronic diarrhea, weight loss, low-grade fever, and fatigue**, often with perianal complaints that the patient volunteers last.",
      "The complications that bring a surgeon in are **obstruction, fistula, intra-abdominal abscess or phlegmon, perforation, hemorrhage, and toxic colitis**.",
      "Extraintestinal manifestations that **parallel bowel activity and improve after resection**: erythema nodosum, peripheral large-joint arthritis, episcleritis, and oral aphthae.",
      "Extraintestinal manifestations that run **independent of bowel activity and do not improve after resection**: primary sclerosing cholangitis and ankylosing spondylitis, with pyoderma gangrenosum usually independent and uveitis variable.",
      "That split is worth memorising as a pair: **joints, skin, and eyes track the gut; liver and spine do not**.",
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-workup",
    type: "bullets",
    heading: "Diagnosis and workup",
    items: [
      "**Ileocolonoscopy with terminal ileal intubation and segmental biopsies** is the diagnostic gold standard.",
      "**CT or MR enterography** is the first-line cross-sectional study for small-bowel disease, strictures, and penetrating complications.",
      "**MR enterography** is preferred where it is available because it distinguishes **active inflammation** — mural hyperenhancement and edema, which may respond to medicine — from **fibrostenosis**, which will not, and it avoids radiation in a young patient facing decades of imaging.",
      "**ASCA positive with p-ANCA negative** favours Crohn disease; the reverse pattern favours ulcerative colitis.",
      "**CRP and ESR** track activity; **fecal calprotectin** correlates with mucosal inflammation and predicts both relapse and postoperative recurrence.",
      "Send **stool cultures and C. difficile PCR** before escalating therapy — superinfection mimics a flare and steroids make it worse.",
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-montreal",
    type: "table",
    heading: "Montreal classification",
    columns: ["Axis", "Categories", "Why it matters"],
    rows: [
      ["Age at diagnosis (A)", "A1 at or under 16 years; A2 17 to 40 years; A3 over 40 years", "Younger onset tracks with a more aggressive course"],
      ["Location (L)", "L1 ileal; L2 colonic; L3 ileocolonic; L4 upper gastrointestinal, used as a modifier", "Determines which operation is even on the table"],
      ["Behavior (B)", "B1 non-stricturing and non-penetrating; B2 stricturing; B3 penetrating, with a \"p\" modifier for perianal disease", "The single best predictor of whether and when a patient comes to surgery"],
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-medical",
    type: "bullets",
    heading: "Medical management, in the detail a surgeon needs",
    items: [
      "**CDAI severity**: remission below **150**, mild **150 to 219**, moderate to severe at or above **220**, severe above **450**.",
      "**5-ASA agents** (sulfasalazine, mesalamine) have limited efficacy in Crohn disease and are **not effective for postoperative prophylaxis**; watch for interstitial nephritis.",
      "**Corticosteroids**: budesonide for ileal and right colonic disease, prednisone around 40 mg daily tapered over no more than three months, intravenous methylprednisolone for flares. Steroids have **no maintenance role**, and an **abscess must be excluded before they are given**.",
      "**Antibiotics** (metronidazole, ciprofloxacin) are adjuncts for perianal and fistulizing disease, not primary therapy.",
      "**Immunomodulators** (azathioprine, 6-mercaptopurine, methotrexate) are steroid-sparing maintenance; monitor for myelosuppression, pancreatitis, hepatotoxicity, and lymphoma.",
      "**Biologics and small molecules** for moderate to severe disease: anti-TNF (infliximab, adalimumab, certolizumab), anti-integrin (vedolizumab), IL-12/23 (ustekinumab), IL-23 (risankizumab, mirikizumab, guselkumab), and the JAK inhibitor upadacitinib.",
      "**Positioning, per the 2025 AGA synthesis**: in biologic-naive patients infliximab (often with an immunomodulator) and adalimumab rank highest and are preferred for complex, fistulizing, or stricturing phenotypes, while ustekinumab and risankizumab are reasonable for moderate luminal disease. After anti-TNF failure, **risankizumab and upadacitinib** are among the most effective.",
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-topdown",
    type: "prose",
    heading: "Board answer versus current practice: step-up or top-down",
    text: "The teaching most of us learned is the **step-up pyramid** — 5-ASA, then steroids, then an immunomodulator, then a biologic once everything below has failed — and on an older exam that sequence is the keyed answer. It has been overtaken. The **PROFILE trial** randomised newly diagnosed patients between accelerated step-up and early combined **infliximab with an immunomodulator**, and the difference was not marginal: steroid-free and surgery-free remission at one year of roughly **79 percent against 15 percent**. The **2025 ACG guideline now calls top-down therapy the standard of care** for newly diagnosed active Crohn disease. The practical reading is that the pyramid described a disease we were managing reactively, and the reason it looked reasonable is that the damage it permitted — stricture, fistula, resected bowel — accumulated slowly enough to seem like the disease rather than the delay. Answer step-up only if a question is explicitly asking for historical sequencing; otherwise the modern answer is early effective therapy in anyone at high risk.",
  }, PACKET),
  sourced({
    id: "block-crohn-surgical-principles",
    type: "bullets",
    heading: "Surgical principles",
    items: [
      "**Surgery is not curative.** Resect only to **grossly normal margins**, around **2 cm** — microscopically positive margins do not mandate a wider resection and do not alter recurrence.",
      "**Preserve bowel length.** Every centimetre taken is a centimetre unavailable at the next operation, and short bowel syndrome is a disease the surgeon creates.",
      "**Favour stricturoplasty** over resection wherever short-bowel risk exists, meaning multiple strictures, prior resections, or long diseased segments.",
      "**Recurrence is expected**: endoscopic recurrence reaches about **50 percent by 18 months**, and reoperation rates after ileocecal resection run roughly **19, 28, and 40 percent at one, five, and ten years**.",
      "**Kono-S anastomosis** and **extended mesenteric resection** are emerging techniques that may reduce recurrence, on the reasoning that the mesentery is part of the disease rather than a bystander.",
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-indications",
    type: "bullets",
    heading: "Indications for operation",
    items: [
      "**Fibrostenotic obstruction** — the most common indication overall.",
      "**Penetrating disease**: abscess, fistula, or phlegmon — the second most common.",
      "**Hemorrhage, free perforation, dysplasia or cancer**, and **medically refractory disease**.",
      "**Early elective resection in limited ileal disease** is now a legitimate first-line option rather than a failure of medicine — see the LIR!C block below.",
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-lirc",
    type: "prose",
    heading: "Board answer versus current practice: surgery is not a treatment failure",
    text: "The reflex that surgery in Crohn disease represents the point at which medicine lost is deeply embedded and, in limited ileocecal disease, wrong. The **LIR!C trial** randomised patients with limited ileal disease between **laparoscopic ileocecal resection** and **infliximab** and found them equivalent for quality of life at one year. The **ten-year follow-up** is the more striking half: roughly **48 percent of the infliximab arm eventually came to resection anyway**, while **none of the resection arm required a second resection** and many remained off all treatment. Read carefully, that does not say surgery is better — it says that for a short segment of terminal ileal disease, an early operation and a biologic are two reasonable opening moves, and the operation buys a substantial chance of drug-free remission that indefinite infliximab does not. Offer it as a choice rather than as a concession, and note that this reasoning does not transfer to diffuse, colonic, or perianal disease.",
  }, PACKET),
  sourced({
    id: "block-crohn-operative-decision",
    type: "flow",
    heading: "Complicated Crohn disease: choosing the operation",
    nodes: [
      { id: "complicated", label: "Complicated Crohn disease requiring a surgical decision" },
      { id: "perforation", label: "Free perforation with peritonitis", tone: "caution" },
      { id: "abscess", label: "Intra-abdominal abscess, typically over 3 cm" },
      { id: "toxic", label: "Toxic colitis or megacolon, colon over 6 cm with systemic toxicity", tone: "caution" },
      { id: "stricture", label: "Fibrostenotic stricture causing obstruction" },
      { id: "refractory", label: "Medically refractory luminal disease without a mechanical complication" },
      { id: "urgentResect", label: "Urgent resection with proximal diversion — no primary anastomosis in a contaminated field", tone: "caution" },
      { id: "drain", label: "Percutaneous drainage plus antibiotics, leaving the drain in until the operation", tone: "good" },
      { id: "delayed", label: "Delayed elective resection once sepsis is controlled and nutrition optimised", tone: "good" },
      { id: "medicalTrial", label: "Trial of medical therapy for 24 to 72 hours" },
      { id: "colectomy", label: "Subtotal colectomy with end ileostomy and a Hartmann stump or mucous fistula", tone: "caution" },
      { id: "smallBowel", label: "Small-bowel or anastomotic stricture" },
      { id: "colonic", label: "Colonic stricture" },
      { id: "shortSingle", label: "Short, single, endoscopically accessible, no fistula or abscess" },
      { id: "dilate", label: "Endoscopic balloon dilation", tone: "good" },
      { id: "resectOrSp", label: "Resection, or stricturoplasty where bowel length is at risk", tone: "good" },
      { id: "segmental", label: "Segmental resection — never stricturoplasty, because of occult malignancy risk", tone: "caution" },
      { id: "electiveResect", label: "Elective resection or advanced therapy, decided with the patient", tone: "good" },
    ],
    edges: [
      { from: "complicated", to: "perforation", label: "free perforation" },
      { from: "complicated", to: "abscess", label: "abscess or phlegmon" },
      { from: "complicated", to: "toxic", label: "toxic colitis" },
      { from: "complicated", to: "stricture", label: "obstruction" },
      { from: "complicated", to: "refractory", label: "refractory disease" },
      { from: "perforation", to: "urgentResect" },
      { from: "abscess", to: "drain" },
      { from: "drain", to: "delayed" },
      { from: "toxic", to: "medicalTrial" },
      { from: "medicalTrial", to: "colectomy", label: "no improvement" },
      { from: "medicalTrial", to: "electiveResect", label: "responds" },
      { from: "stricture", to: "smallBowel", label: "small bowel" },
      { from: "stricture", to: "colonic", label: "colon" },
      { from: "smallBowel", to: "shortSingle", label: "assess length and access" },
      { from: "shortSingle", to: "dilate", label: "criteria met" },
      { from: "shortSingle", to: "resectOrSp", label: "long, multiple, or complicated" },
      { from: "colonic", to: "segmental" },
      { from: "refractory", to: "electiveResect" },
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-abscess",
    type: "bullets",
    heading: "Intra-abdominal abscess: drain, then wait",
    items: [
      "An abscess, conventionally one over **3 cm**, is drained **percutaneously with antibiotics first**, and resection is deliberately delayed.",
      "Meta-analysis favours this over upfront surgery, with **fewer complications** and an odds ratio around **0.58**.",
      "**Leave the drain in until the operation.** Draining and then removing the drain preoperatively, or operating on an undrained abscess, both raise the rate at which the patient ends up diverted.",
      "The delay is not merely infection control — it buys time for **nutritional optimisation and steroid weaning**, both of which change what anastomosis is safe.",
      "**Free perforation with peritonitis** is the exception: urgent resection with diversion, not drainage.",
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-dilation",
    type: "bullets",
    heading: "Endoscopic balloon dilation",
    items: [
      "Appropriate for **short strictures under 4 to 5 cm** that are **single and endoscopically accessible** and have **no associated fistula or abscess**.",
      "**Technical success around 90 percent**, with a **perforation rate of 2 to 4 percent**.",
      "About **one third still require surgery within two to five years**, so it is a way of deferring an operation rather than avoiding one.",
      "Colonic strictures are the exception and should not be dilated in preference to resection, because of the risk of an occult carcinoma behind them.",
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-stricturoplasty",
    type: "table",
    heading: "Stricturoplasty by length: classic teaching versus ASCRS",
    columns: ["Technique", "Board-classic length", "ASCRS 2020 length"],
    rows: [
      ["Heineke-Mikulicz", "5 cm or less", "Under 10 cm"],
      ["Finney", "5 to 10 cm", "10 to 25 cm"],
      ["Michelassi (side-to-side isoperistaltic)", "Over 10 cm", "Over 25 cm"],
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-stricturoplasty-split",
    type: "prose",
    heading: "Which set of stricturoplasty numbers to give",
    text: "Two schemes circulate and they differ by more than rounding. The older board-review scheme — **Heineke-Mikulicz up to 5 cm, Finney 5 to 10 cm, Michelassi above 10 cm** — is what most question banks still key. The **ASCRS 2020 guideline** moves every threshold substantially upward: **Heineke-Mikulicz under 10 cm, Finney 10 to 25 cm, and side-to-side isoperistaltic stricturoplasty above 25 cm**. The difference reflects accumulated experience that a transverse closure tolerates a longer stricture than was once thought and that the alternative — resecting 25 cm of ileum in a patient who will need another operation — is the worse trade. Know both, and **cite the ASCRS numbers for anything framed as guideline-based**. Contraindications do not vary between the schemes: **perforation, phlegmon or inflammatory mass, malignancy or dysplasia, severe malnutrition, and any colonic stricture**.",
  }, PACKET),
  sourced({
    id: "block-crohn-site-specific",
    type: "bullets",
    heading: "Perianal, gastroduodenal, and colonic disease",
    items: [
      "**Perianal fistulae**: drain any abscess, place **loose non-cutting setons** for complex tracts, and combine with **anti-TNF therapy** — infliximab gives the best fistula response.",
      "**Avoid cutting fistulotomy and lateral internal sphincterotomy** in Crohn disease; the incontinence risk in a rectum that will keep flaring is not recoverable.",
      "**Gastroduodenal disease**: try endoscopic balloon dilation first, and for refractory obstruction prefer **gastrojejunostomy bypass over resection**.",
      "**Colonic strictures** are resected segmentally and never treated by stricturoplasty, because occult malignancy sits behind a proportion of them.",
      "**Ileal pouch-anal anastomosis is contraindicated in Crohn disease** by classic teaching, given the rates of pouch failure and pouch fistulisation. For refractory pancolonic or perianal disease the durable operation is **total proctocolectomy with end ileostomy**.",
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-recurrence",
    type: "bullets",
    heading: "Postoperative recurrence: prevention and surveillance",
    items: [
      "The **three strongest risk factors** are **active smoking, penetrating disease, and two or more prior resections**; male sex and prior biologic exposure also contribute.",
      "**Anti-TNF therapy (infliximab or adalimumab) is first-line prophylaxis** and the most effective agent for preventing recurrence.",
      "**Vedolizumab** is now supported by the **REPRIVIO** trial, which reported severe endoscopic recurrence of **23 percent against 62 percent** on placebo at week 26.",
      "**5-ASA and antibiotic monotherapy are ineffective** for postoperative prophylaxis — a common distractor.",
      "**Low-risk patients** — nonsmoker, no penetrating disease, no prior resection — may be observed with **colonoscopy at 6 to 12 months** rather than started on a drug.",
      "**High-risk patients**, or anyone with a prior resection within ten years, get **postoperative anti-TNF with or without an immunomodulator**.",
      "**Everyone gets an ileocolonoscopy at 6 to 12 months** and is graded by the **Rutgeerts score**; the **POCER** trial validated risk-stratified therapy with early endoscopy.",
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-rutgeerts",
    type: "table",
    heading: "Rutgeerts score at the neoterminal ileum",
    columns: ["Grade", "Endoscopic appearance", "Implication"],
    rows: [
      ["i0", "No lesions", "Low risk — continue current strategy"],
      ["i1", "Five or fewer aphthous lesions", "Low risk"],
      ["i2a", "Lesions confined to the anastomosis alone", "Low risk, and the reason i2 was subdivided"],
      ["i2b", "More than five aphthous ulcers in the neoterminal ileum with normal mucosa between them", "Higher risk — escalate therapy"],
      ["i3", "Diffuse aphthous ileitis with diffusely inflamed mucosa", "Higher risk"],
      ["i4", "Diffuse inflammation with large ulcers, nodules, or narrowing", "Higher risk, and the grade that predicts clinical recurrence soonest"],
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-cancer",
    type: "bullets",
    heading: "Malignancy risk and colorectal cancer surveillance",
    items: [
      "**Crohn colitis carries a colorectal cancer risk comparable to ulcerative colitis** of similar extent and duration — the transmural-versus-mucosal distinction does not protect the colon.",
      "**Small-bowel adenocarcinoma risk is elevated**, but there is no routine small-bowel surveillance programme.",
      "Begin **surveillance colonoscopy 8 years after symptom onset** in patients with at least **30 percent colonic involvement**; with **primary sclerosing cholangitis**, begin at the PSC diagnosis regardless of duration.",
      "**Interval every 1 to 3 years**, risk-stratified, with some societies extending to 5 years in low-risk patients.",
      "**Technique**: high-definition white light or chromoendoscopy, with targeted biopsies of every visible abnormality plus random four-quadrant biopsies every 10 cm, at least **32 samples**.",
      "**Confirmed multifocal or endoscopically unresectable dysplasia** triggers a colectomy discussion.",
    ],
  }, PACKET),
  sourced({
    id: "block-crohn-pearls",
    type: "bullets",
    heading: "Board pearls",
    items: [
      "**Smoking is the number one modifiable risk factor** — it worsens Crohn and protects in ulcerative colitis.",
      "**Fibrostenotic obstruction is the most common surgical indication**; penetrating disease is second.",
      "**Resect to grossly normal margins only** — microscopically positive margins do not change recurrence and do not justify taking more bowel.",
      "**A colonic stricture is resected, never stricturoplastied**, because of occult cancer.",
      "**An abscess over 3 cm is drained percutaneously first**, the drain stays in, and the resection is delayed.",
      "**Noncaseating granuloma, creeping fat, skip lesions, or a perianal fistula** all point to Crohn disease.",
      "**Large-joint arthralgia that improves after resection** is an activity-linked extraintestinal manifestation; **PSC and ankylosing spondylitis are unchanged by resection**.",
      "**Ileal pouch-anal anastomosis is contraindicated in Crohn disease**; Kono-S anastomosis and extended mesenteric excision are the newer recurrence-reduction strategies.",
      "Three guideline-versus-classic flags worth rehearsing: the **ASCRS stricturoplasty lengths** rather than the older 5 / 5 to 10 / over 10 scheme; **top-down biologics** rather than step-up after PROFILE; and **early ileocecal resection** as an accepted first-line alternative to infliximab in limited ileal disease after LIR!C.",
    ],
  }, PACKET),
  references("block-crohn-references", [PACKET]),
];

export const crohnDiseaseTopic = buildTopic({
  id: "00000000-0000-4000-8000-000000001310",
  versionId: "00000000-0000-4000-8000-000000001320",
  slug: "crohn-disease",
  title: "Crohn Disease",
  aliases: ["crohn disease", "crohn's disease", "crohns", "CD", "regional enteritis", "terminal ileitis", "ileocolic crohn", "ileocecal resection", "inflammatory bowel disease", "IBD", "creeping fat", "skip lesions", "cobblestoning", "noncaseating granuloma", "stricturoplasty", "strictureplasty", "Heineke-Mikulicz", "Finney", "Michelassi", "Kono-S", "Rutgeerts score", "enterocutaneous fistula", "perianal fistula", "seton", "NOD2", "CARD15", "ASCA", "Montreal classification", "CDAI", "LIR!C", "PROFILE trial", "top-down therapy", "infliximab", "postoperative recurrence"],
  scoreNodeId: "small-intestine-conditions",
  scoreCategory: "SCORE · Small Intestine · Diseases & Conditions",
  tags: ["small-intestine", "crohn-disease", "inflammatory-bowel-disease", "colorectal", "stricturoplasty", "absite", "score"],
  sourceId: PACKET,
  blocks,
  reviewedAt: "2026-08-20T00:00:00.000Z",
});
