import { buildTopic, references, sourced, sourcedUnits } from "@/content/authoring";
import {
  COBRRA_SOURCE as COBRRA,
  DVT_PACKET_SOURCE as PACKET,
  FISER_HEMATOLOGY_SOURCE as FISER_HEME,
  FISER_VASCULAR_SOURCE as FISER,
  SCORE_VENA_CAVA_FILTER_SOURCE as SCORE_FILTER,
  SCORE_VENOUS_THROMBOEMBOLISM_SOURCE as SCORE,
  SIR_ILIOFEMORAL_DVT_2023_SOURCE as SIR,
  SVS_AVF_EARLY_THROMBUS_REMOVAL_2012_SOURCE as SVS,
} from "@/content/sources";
import type { TopicBlock } from "@/lib/types";

const blocks: TopicBlock[] = [
  sourced({
    id: "block-dvt-summary",
    type: "summary",
    heading: "At a glance",
    text: "Deep venous thrombosis is clot in the **deep veins**, most often of the leg, and the clot's **location** sets the plan. Isolated calf clot can be watched with serial duplex; **popliteal and above** gets anticoagulation, now a **DOAC** for most patients; iliofemoral clot raises the question of thrombus removal, which is reserved for **phlegmasia** and selected young patients; and the arm splits into **catheter-related** clot, **Paget-Schroetter** effort thrombosis, and SVC obstruction. When anticoagulation is contraindicated, the answer for a **proximal leg** clot is a **retrievable infrarenal IVC filter**, with anticoagulation restarted the moment it is safe. The exam also lives in **HIT**, the thrombophilias, and where a filter goes.",
  }, PACKET),
  sourcedUnits({
    id: "block-dvt-anatomy",
    type: "bullets",
    heading: "Proximal versus distal",
    items: [
      "**Proximal** DVT is the popliteal vein and above: femoral, common femoral, iliac, and IVC. **Distal** (calf) DVT is infrapopliteal: posterior tibial, peroneal, anterior tibial, and the soleal and gastrocnemius veins.",
      "Proximal clot embolizes far more readily than isolated calf clot, which is why location drives management.",
      "**Virchow triad**: venous stasis, endothelial injury, and hypercoagulability. Surgical patients hit all three.",
      "Natural history: propagation, then embolization, then valve destruction and venous hypertension — **post-thrombotic syndrome**.",
      "The **left leg** is involved about twice as often as the right, because the right common iliac artery crosses and compresses the left common iliac vein.",
      "Swelling tracks the level: **calf** clot causes minimal swelling, **femoral** clot ankle and calf swelling, **iliofemoral** clot swelling of the whole leg.",
    ],
  }, [[PACKET], [PACKET], [PACKET, FISER_HEME], [PACKET], [FISER], [FISER]]),
  sourcedUnits({
    id: "block-dvt-thrombophilia",
    type: "bullets",
    heading: "Risk factors and thrombophilias",
    items: [
      "Surgery and major transient provocation — major operations, pelvic and orthopedic surgery, trauma, immobilization, central lines — is the most common surgical driver.",
      "About **50% to 60%** of VTE is provoked, **20%** is cancer-associated, and **20% to 30%** is unprovoked.",
      "Active cancer carries a **7-fold** VTE risk, with an absolute risk of **5% to 20%** in the first year after diagnosis.",
      "**Factor V Leiden** (activated protein C resistance) is the most common inherited thrombophilia.",
      "**Smoking** is the most common cause of acquired hypercoagulability.",
      "**Antithrombin III deficiency** causes heparin resistance: give antithrombin concentrate or FFP, then heparin, or use a direct thrombin inhibitor.",
      "**Antiphospholipid syndrome** is the acquired thrombophilia that mandates warfarin rather than a DOAC.",
      "Others: prothrombin G20210A, protein C and S deficiency, estrogen and pregnancy, polycythemia vera, and nephrotic syndrome.",
    ],
  }, [[PACKET], [SCORE], [SCORE], [FISER_HEME], [FISER_HEME], [FISER_HEME, PACKET], [PACKET], [PACKET]]),
  sourcedUnits({
    id: "block-dvt-prophylaxis",
    type: "bullets",
    heading: "Prophylaxis by Caprini score",
    items: [
      "**Very low (0 to 1)**: early ambulation only.",
      "**Low (2)**: mechanical prophylaxis with sequential compression devices.",
      "**Moderate (3 to 4)**: mechanical or pharmacologic prophylaxis.",
      "**High (5 or more)**: combined mechanical and pharmacologic prophylaxis.",
      "High-risk patients after **major abdominopelvic cancer surgery** get pharmacologic prophylaxis for about **28 days** after discharge.",
      "Sequential compression devices reduce stasis and increase endothelial **tPA** release.",
      "Do not place or remove an epidural catheter within **12 hours** of a prophylactic LMWH dose; therapeutic dosing needs longer.",
    ],
  }, [[SCORE], [SCORE], [SCORE], [SCORE], [PACKET], [FISER], [PACKET]]),
  sourced({
    id: "block-dvt-presentation",
    type: "bullets",
    heading: "Presentation and red flags",
    items: [
      "Often asymptomatic or found incidentally on cross-sectional imaging.",
      "Unilateral pain, swelling, tenderness, warmth, and erythema; the Homan sign is unreliable, and the exam alone cannot make or exclude the diagnosis.",
      "Massive swelling to the groin or buttock: **iliofemoral** DVT.",
      "Painful white leg or painful blue leg: **phlegmasia**, and limb-threatening.",
      "Acutely swollen, cyanotic arm in a young athlete: **Paget-Schroetter** effort thrombosis.",
      "Bilateral arm, face, and neck swelling with chest-wall collaterals: **SVC** thrombosis.",
    ],
  }, PACKET),
  sourcedUnits({
    id: "block-dvt-workup",
    type: "sequence",
    heading: "Workup",
    steps: [
      { title: "Pretest probability", detail: "**Wells score** — not validated in pregnant or hospitalized patients." },
      { title: "D-dimer for low or unlikely probability", detail: "High sensitivity, poor specificity. A negative D-dimer with low pretest probability excludes DVT without ultrasound; after surgery, trauma, or in pregnancy it is routinely elevated and adds little." },
      { title: "Compression duplex ultrasound", detail: "First-line, and first outright for high pretest probability, recurrence, or pregnancy. **Noncompressibility** of the vein is the diagnostic sign; specificity is above 95%, and a complete groin-to-calf exam misses about 1%." },
      { title: "CT or MR venography", detail: "For the iliac veins and IVC when ultrasound is limited, equivocal, or negative despite whole-leg swelling." },
      { title: "Catheter venography", detail: "Invasive and rarely a first test; the gold standard for pelvic anatomy such as **May-Thurner** compression." },
    ],
  }, [[SCORE], [SCORE], [SCORE], [SCORE, PACKET], [PACKET]]),
  sourcedUnits({
    id: "block-dvt-location",
    type: "table",
    heading: "Where the clot is decides the plan",
    columns: ["Location", "Clue", "Management"],
    rows: [
      ["Isolated calf (distal)", "Minimal or localized calf symptoms; low embolic risk", "**3 months** of anticoagulation, or serial duplex over about 2 weeks when symptoms are mild — the stronger choice when bleeding risk is high. Treat if it extends proximally."],
      ["Femoral or popliteal", "Calf and ankle swelling", "**Therapeutic anticoagulation**"],
      ["Iliofemoral", "Whole-leg swelling to the groin", "Anticoagulation alone for most; thrombus removal only for phlegmasia or a selected young, low-bleeding-risk patient"],
      ["May-Thurner (left common iliac vein)", "Left leg swollen to the groin, classically a young woman", "Venography, lysis if indicated, and **iliac vein stenting** of the underlying compression"],
      ["Phlegmasia cerulea dolens", "Massive swelling, cyanosis, sensorimotor loss", "**Emergent** fluids and thrombus removal — catheter-directed or open"],
      ["Catheter-related arm", "Arm swelling with a central line or PICC; the most common upper extremity DVT", "Remove a line no longer needed and anticoagulate; keep an essential, working line and anticoagulate through it"],
      ["Subclavian at the thoracic outlet (Paget-Schroetter)", "Young athlete with repetitive overhead activity and a blue, swollen arm", "**Catheter-directed thrombolysis**, then **first rib resection** with scalenectomy"],
      ["Superior vena cava", "Bilateral arm, face, and neck swelling with chest-wall collaterals", "Look for the cause: catheters, pacemaker leads, or **mediastinal malignancy**"],
    ],
  }, [[PACKET], [PACKET], [PACKET, SIR], [PACKET], [PACKET, SVS], [PACKET, FISER], [PACKET, FISER], [PACKET]]),
  sourcedUnits({
    id: "block-dvt-contraindicated-flow",
    type: "flow",
    heading: "When anticoagulation is contraindicated",
    nodes: [
      { id: "start", label: "Acute DVT with a contraindication to anticoagulation: active bleeding, recent intracranial hemorrhage, or major trauma" },
      { id: "calf", label: "Isolated calf DVT" },
      { id: "surveil", label: "Serial duplex over about 2 weeks; no filter", tone: "good" },
      { id: "extends", label: "Extends to the popliteal vein or above: treat as proximal", tone: "caution" },
      { id: "proximal", label: "Proximal leg DVT, popliteal vein and above" },
      { id: "filter", label: "Retrievable infrarenal IVC filter", tone: "caution" },
      { id: "restart", label: "Start anticoagulation as soon as the contraindication resolves, then retrieve the filter", tone: "good" },
      { id: "limb", label: "Phlegmasia cerulea dolens — limb threatened" },
      { id: "thrombectomy", label: "Fluid resuscitation and mechanical thrombectomy without lytic — percutaneous, or open through the common femoral vein", tone: "caution" },
      { id: "arm", label: "Upper extremity DVT" },
      { id: "arm-plan", label: "Remove a catheter that is no longer needed, elevate, and re-image; an IVC filter cannot catch an arm clot", tone: "caution" },
    ],
    edges: [
      { from: "start", to: "calf", label: "calf only" },
      { from: "calf", to: "surveil" },
      { from: "surveil", to: "extends", label: "propagation" },
      { from: "extends", to: "filter" },
      { from: "start", to: "proximal", label: "proximal leg" },
      { from: "proximal", to: "filter" },
      { from: "filter", to: "restart" },
      { from: "start", to: "limb", label: "limb threatened" },
      { from: "limb", to: "thrombectomy" },
      { from: "start", to: "arm", label: "arm" },
      { from: "arm", to: "arm-plan" },
    ],
  }, [[PACKET], [PACKET], [PACKET], [PACKET], [PACKET], [PACKET, SCORE_FILTER], [SCORE, PACKET], [PACKET], [SCORE, PACKET], [PACKET], [PACKET, FISER_HEME], [PACKET], [PACKET], [PACKET], [PACKET], [PACKET]]),
  sourcedUnits({
    id: "block-dvt-contraindicated-notes",
    type: "bullets",
    heading: "↳ Why each branch",
    items: [
      "Calf clot rarely embolizes, so watching it is safer than a filter when bleeding risk is high; it needs treatment only if it propagates.",
      "A filter is indicated for **acute proximal DVT or PE** with a contraindication to anticoagulation, a complication of anticoagulation, or recurrence despite therapeutic anticoagulation.",
      "A filter **does not treat the DVT** — restart anticoagulation as soon as the contraindication resolves, even with the filter in place.",
      "Open venous thrombectomy is the option when lysis is contraindicated and the limb is immediately threatened.",
      "Percutaneous mechanical thrombectomy aspirates or captures clot through catheters, typically from **popliteal vein** access.",
      "An IVC filter protects only against clot from below it; pulmonary emboli from the arm reach the lung through the SVC.",
    ],
  }, [[PACKET], [SCORE_FILTER, FISER_HEME], [SCORE, PACKET], [PACKET], [SCORE], [FISER_HEME]]),
  sourcedUnits({
    id: "block-dvt-agent",
    type: "bullets",
    heading: "Anticoagulation: choosing the agent",
    items: [
      "Without cancer, a **DOAC** is first-line over warfarin: noninferior for recurrence, with less major, intracranial, and fatal bleeding.",
      "**Apixaban** and **rivaroxaban** start orally with no parenteral lead-in; **dabigatran** and **edoxaban** need **5 days** of LMWH first.",
      "**COBRRA** (2026): clinically relevant bleeding at 3 months was **3.3%** on apixaban against **7.1%** on rivaroxaban, with no difference in recurrence. Apixaban is now the favored DOAC.",
      "Use **warfarin**, not a DOAC, for antiphospholipid syndrome (especially triple-positive), creatinine clearance under 30 mL/min, moderate to severe liver disease, or a mechanical valve.",
      "Warfarin needs at least **5 days** of heparin overlap and an INR above 2.0 on two checks 24 hours apart; target INR 2 to 3.",
      "**Unfractionated heparin** or LMWH when you need rapid on-and-off control — a planned intervention or high bleeding risk.",
    ],
  }, [[PACKET, SCORE], [PACKET], [COBRRA], [PACKET], [PACKET], [PACKET]]),
  sourced({
    id: "block-dvt-doses",
    type: "table",
    heading: "↳ Starting doses",
    columns: ["Agent", "Initial phase", "Then"],
    rows: [
      ["Apixaban", "10 mg twice daily for 7 days", "5 mg twice daily"],
      ["Rivaroxaban", "15 mg twice daily with food for 21 days", "20 mg daily with food"],
      ["Dabigatran", "LMWH for at least 5 days", "150 mg twice daily"],
      ["Edoxaban", "LMWH for at least 5 days", "60 mg daily"],
      ["Warfarin", "Overlap with heparin at least 5 days and until INR above 2.0 twice", "INR goal 2 to 3"],
    ],
  }, PACKET),
  sourcedUnits({
    id: "block-dvt-duration",
    type: "table",
    heading: "How long",
    columns: ["Scenario", "Duration"],
    rows: [
      ["Provoked by surgery, trauma, or transient immobilization", "**3 months**"],
      ["First isolated calf DVT, provoked", "**3 months**, or surveillance"],
      ["Unprovoked proximal DVT", "At least 3 months, then **extended** with no planned stop if bleeding risk is acceptable"],
      ["Second unprovoked VTE", "**Indefinite**"],
      ["Active cancer", "At least 6 months, extended while the cancer is active"],
      ["Antiphospholipid syndrome", "Indefinite, on warfarin"],
      ["Upper extremity DVT", "At least **3 months**; for a catheter-related clot, as long as the catheter stays and at least 3 months"],
    ],
  }, [[PACKET, FISER_HEME], [PACKET], [PACKET, SCORE], [PACKET, SCORE], [PACKET], [PACKET], [PACKET]]),
  sourced({
    id: "block-dvt-extended",
    type: "bullets",
    heading: "↳ Extended phase",
    items: [
      "Options: **apixaban 2.5 mg** twice daily, apixaban 5 mg twice daily, or rivaroxaban 10 mg daily. Reduced-dose apixaban matches full dose for efficacy with less bleeding.",
      "Aspirin is inferior to a DOAC for secondary prevention.",
      "**HERDOO2** is the only prospectively validated rule identifying women with a first unprovoked VTE who may safely stop anticoagulation.",
      "Reassess bleeding risk periodically on extended therapy.",
    ],
  }, PACKET),
  sourced({
    id: "block-dvt-cancer",
    type: "bullets",
    heading: "Cancer-associated thrombosis",
    items: [
      "Oral factor Xa inhibitors — **apixaban, edoxaban, rivaroxaban** — are now first-line or equivalent to LMWH for most patients.",
      "Prefer **LMWH** for luminal GI or unresected genitourinary cancer, where DOACs cause more mucosal bleeding, and for severe renal impairment, thrombocytopenia, drug interactions, or poor absorption.",
      "Treat at least **6 months**, and continue while the cancer is active.",
      "About **4% to 10%** of patients with a truly unprovoked DVT have a cancer diagnosed within 12 months. Do age-appropriate screening, not an indiscriminate scan.",
    ],
  }, PACKET),
  sourcedUnits({
    id: "block-dvt-removal",
    type: "bullets",
    heading: "Thrombus removal for iliofemoral DVT",
    items: [
      "**ATTRACT**: pharmacomechanical catheter-directed therapy did not reduce overall post-thrombotic syndrome and increased major bleeding, though it reduced moderate to severe post-thrombotic syndrome and early symptoms.",
      "So anticoagulation alone is first-line for most proximal and iliofemoral DVT.",
      "Reserve catheter-directed or pharmacomechanical therapy for **phlegmasia cerulea dolens** and for selected patients under about 65 with acute (under 14 days) iliofemoral DVT, low bleeding risk, good function, and a life expectancy of at least a year.",
      "When lysis is chosen, catheter-directed beats systemic.",
      "An underlying **May-Thurner** compression is treated with an **iliac vein stent** after the clot is cleared.",
    ],
  }, [[SIR, PACKET], [SIR], [SIR, PACKET], [PACKET], [PACKET]]),
  sourcedUnits({
    id: "block-dvt-phlegmasia",
    type: "table",
    heading: "Phlegmasia: white leg versus blue leg",
    columns: ["Feature", "Phlegmasia alba dolens", "Phlegmasia cerulea dolens"],
    rows: [
      ["Pathology", "Extensive deep occlusion with **collaterals preserved**", "Near-total occlusion of deep veins **and collaterals**"],
      ["Appearance", "Pale, painful, swollen; pulses present", "Intensely **cyanotic**, massive swelling to the buttock, progressive ischemia"],
      ["Compartments", "Mildly raised pressure", "Markedly raised — **venous gangrene** and compartment syndrome"],
      ["Systemic effect", "Minor", "Massive third-spacing and **hypovolemic shock**"],
      ["Treatment", "Elevation, compression, therapeutic heparin", "**Aggressive fluids** and urgent catheter-directed or open thrombus removal; low threshold for four-compartment fasciotomy"],
    ],
  }, [[PACKET], [PACKET, FISER], [PACKET, SCORE], [PACKET, SCORE], [PACKET, SVS]]),
  sourced({
    id: "block-dvt-open-thrombectomy",
    type: "sequence",
    heading: "↳ Open venous thrombectomy",
    steps: [
      { title: "Resuscitate first", detail: "Most patients are hypovolemic from the fluid shift into the leg." },
      { title: "Groin exposure", detail: "Longitudinal incision and venotomy of the **common femoral vein**." },
      { title: "Proximal clot", detail: "Pass a balloon thrombectomy catheter up through the iliac veins." },
      { title: "Distal clot", detail: "Valves block a balloon passed down the leg, so wrap the leg distal to proximal with an **Esmarch bandage** and milk the clot out of the venotomy." },
      { title: "Protect the result", detail: "A temporary **arteriovenous fistula** from the great saphenous vein to the superficial femoral artery raises flow through the cleared segment." },
    ],
  }, SCORE),
  sourcedUnits({
    id: "block-dvt-arm",
    type: "bullets",
    heading: "Upper extremity DVT",
    items: [
      "**Catheter-related** clot is the most common upper extremity DVT. Pull a line that is no longer needed, then anticoagulate; keep an essential, functioning line and anticoagulate, with tPA down the line an option.",
      "**Paget-Schroetter** (effort thrombosis, venous thoracic outlet syndrome): the subclavian vein is compressed at the **costoclavicular space** between the first rib and clavicle, classically in a young athlete with repetitive overhead activity.",
      "Duplex makes the diagnosis; catheter venography is the gold standard.",
      "Treat Paget-Schroetter with **catheter-directed thrombolysis**, then **first rib resection** with anterior scalenectomy in the same admission or soon after; anticoagulation alone leaves the compression in place.",
      "**SVC** thrombosis comes from catheters, pacemaker leads, or mediastinal malignancy, and presents with bilateral arm, face, and neck swelling and chest-wall collaterals.",
      "Anticoagulate an upper extremity DVT for at least **3 months**.",
    ],
  }, [[PACKET, FISER], [PACKET], [FISER], [PACKET, FISER], [PACKET], [PACKET]]),
  sourcedUnits({
    id: "block-dvt-filter",
    type: "bullets",
    heading: "IVC filters",
    items: [
      "Indications: acute proximal DVT or PE with a **contraindication to anticoagulation**, a complication of anticoagulation, recurrent VTE despite therapeutic anticoagulation, or inability to reach therapeutic levels.",
      "Relative indications: free-floating iliocaval thrombus, renal cell carcinoma with renal vein extension, thrombolysis or thrombectomy, limited cardiopulmonary reserve, and selected high-risk trauma patients.",
      "**Retrievable** filters are preferred. PREPIC: filters cut PE by about half but raise DVT by about 70%, with no survival benefit.",
      "Retrieve as soon as PE risk has passed — the FDA suggests between **29 and 54 days** — because retrieval gets harder with dwell time. Track every filter in a retrieval program.",
      "Late complications: filter thrombosis, migration, strut fracture, and caval perforation.",
    ],
  }, [[SCORE_FILTER, PACKET], [SCORE_FILTER], [PACKET], [PACKET, SCORE_FILTER], [PACKET, SCORE_FILTER]]),
  sourcedUnits({
    id: "block-dvt-filter-placement",
    type: "bullets",
    heading: "↳ Placement and caval anatomy",
    items: [
      "Standard position: **infrarenal IVC**, with the apex just below the lowest renal vein. A venogram locates the renal veins (about L1 to L2) and measures the cava.",
      "Access through the **right common femoral vein**, or the right internal jugular.",
      "Most filters fit a cava under **30 mm** (average about 23 mm); a larger cava needs a Bird's Nest filter or a filter in each common iliac vein.",
      "Go **suprarenal** for thrombus at or above the renal veins, gonadal or ovarian vein thrombosis, and pregnancy.",
      "**Duplicated IVC** (0.2% to 0.3%): a filter in each infrarenal limb, or one suprarenal filter.",
      "**Circumaortic or retroaortic left renal vein**: find the lowest renal vein before deploying.",
      "**Left-sided IVC** (0.2% to 0.5%) drains into the left renal vein and can confuse access.",
    ],
  }, [[FISER_HEME, SCORE_FILTER], [SCORE_FILTER], [SCORE_FILTER], [PACKET, SCORE_FILTER], [PACKET, SCORE_FILTER], [SCORE_FILTER], [SCORE_FILTER]]),
  sourcedUnits({
    id: "block-dvt-filter-warning",
    type: "warning",
    tone: "danger",
    heading: "PE with a filter in place",
    text: "The clot came from somewhere the filter does not guard: the **upper extremity** through the SVC, the IVC above the filter, or the **gonadal veins** — or it formed on the filter itself.",
  }, [[FISER_HEME, PACKET]]),
  sourcedUnits({
    id: "block-dvt-hit",
    type: "bullets",
    heading: "Heparin-induced thrombocytopenia",
    items: [
      "**IgG** antibodies against heparin-platelet factor 4 complexes activate platelets: thrombocytopenia with **thrombosis**, arterial and venous.",
      "Platelets fall more than **50%**, typically **5 to 10 days** after heparin starts — within a day if heparin was given in the prior 30 days. Bleeding is unusual; thrombosis is the danger.",
      "Workup: **4Ts** score, then the anti-PF4/heparin ELISA as the screen if the score is intermediate or high, then the **serotonin release assay** to confirm.",
      "Stop **all** heparin, including flushes, LMWH, and heparin-coated catheters.",
      "Start a non-heparin anticoagulant: **argatroban** (hepatic clearance) or **bivalirudin** (renal clearance), or fondaparinux.",
      "No warfarin in the acute phase — it causes venous limb gangrene and skin necrosis by dropping protein C. Reverse any warfarin already given with vitamin K.",
      "No prophylactic platelet transfusion.",
      "Move to warfarin or an oral factor Xa inhibitor only after platelets recover to 150 or more; treat about 4 weeks to 3 months for HIT alone and 3 to 6 months with thrombosis.",
      "Screen every HIT patient with lower extremity duplex for occult DVT.",
    ],
  }, [[SCORE, FISER_HEME], [SCORE, PACKET], [SCORE, PACKET], [PACKET, FISER_HEME], [PACKET, FISER_HEME], [PACKET, FISER_HEME], [FISER_HEME], [PACKET], [PACKET]]),
  sourcedUnits({
    id: "block-dvt-followup",
    type: "bullets",
    heading: "Follow-up and complications",
    items: [
      "Untreated VTE recurs in about **30%**; treated, about **5% to 6%** in the first 6 months.",
      "About half have residual vein occlusion on follow-up imaging, and **25% to 40%** develop post-thrombotic syndrome: leg pain, edema, discoloration, and ulceration.",
      "Compression stockings **do not prevent** post-thrombotic syndrome but relieve symptoms. Early ambulation and elevation help too.",
      "Recurrent ipsilateral DVT on duplex: a **new noncompressible segment** or a **4 mm** increase in clot diameter against the baseline scan taken when anticoagulation stopped.",
    ],
  }, [[SCORE], [SCORE], [SCORE, PACKET], [SCORE]]),
  sourcedUnits({
    id: "block-dvt-splits",
    type: "table",
    heading: "Board answer versus current practice",
    columns: ["Question", "Board answer", "Current practice"],
    rows: [
      ["First agent for DVT without cancer", "Heparin, then warfarin", "A **DOAC**, and apixaban over rivaroxaban after COBRRA's lower bleeding"],
      ["First agent for cancer-associated DVT", "**LMWH** — the SCORE module still keys it, from the CLOT trial", "**Oral factor Xa inhibitor** for most; LMWH for luminal GI or genitourinary tumors, severe renal disease, or thrombocytopenia"],
      ["Unprovoked proximal DVT", "**Lifetime** anticoagulation", "At least 3 months, then extended with no planned stop if bleeding risk allows, reassessed periodically; reduced-dose apixaban is an option"],
      ["Extensive iliofemoral DVT", "Lyse it to prevent post-thrombotic syndrome", "**Anticoagulation alone** for most after ATTRACT; thrombus removal for phlegmasia and selected young patients"],
      ["Compression stockings after DVT", "Prevent post-thrombotic syndrome", "**Do not prevent** it (SOX trial); worn for symptoms"],
      ["IVC filters", "Placed liberally", "Narrow indications, **retrievable**, and removed once PE risk passes"],
    ],
  }, [[FISER, COBRRA], [SCORE, PACKET], [FISER_HEME, PACKET], [PACKET, SIR], [PACKET, SCORE], [PACKET, SCORE_FILTER]]),
  sourcedUnits({
    id: "block-dvt-pearls",
    type: "bullets",
    heading: "Board pearls",
    items: [
      "Young pitcher or swimmer with an acutely blue, swollen arm: **Paget-Schroetter**. Catheter-directed thrombolysis, then first rib resection.",
      "Young woman with the left leg swollen to the groin: **May-Thurner**. Venography, lysis as needed, and an iliac stent.",
      "Painful white leg: phlegmasia alba dolens. Elevate and heparinize.",
      "Painful blue leg with sensorimotor loss: phlegmasia cerulea dolens. Fluids and emergent thrombus removal.",
      "Calf clot during open femoral thrombectomy: **Esmarch** milking, because valves stop the balloon.",
      "Proximal DVT and you cannot anticoagulate: **retrievable infrarenal IVC filter**, apex below the lowest renal vein, and anticoagulate once you can.",
      "PE despite a filter: the source is the arm, the IVC above the filter, or the gonadal veins.",
      "Platelets halve on heparin day 5 to 10: **HIT**. Stop all heparin, start argatroban or bivalirudin, and no warfarin until platelets recover.",
      "Heparin will not anticoagulate: **antithrombin III deficiency**.",
      "Central line clot: pull the line if it is not needed, then anticoagulate.",
    ],
  }, [[PACKET, FISER], [PACKET], [PACKET], [PACKET, FISER], [SCORE], [FISER_HEME, SCORE_FILTER], [FISER_HEME], [PACKET, FISER_HEME], [FISER_HEME], [FISER]]),
  references("block-dvt-references", [PACKET, SCORE, SCORE_FILTER, FISER_HEME, FISER, COBRRA, SIR, SVS]),
];

export const deepVenousThrombosisTopic = buildTopic({
  id: "00000000-0000-4000-8000-000000002520",
  versionId: "00000000-0000-4000-8000-000000002521",
  slug: "deep-venous-thrombosis",
  title: "Deep Venous Thrombosis",
  aliases: ["DVT", "deep vein thrombosis", "upper extremity DVT", "UEDVT", "calf DVT", "isolated distal DVT", "proximal DVT", "iliofemoral DVT", "phlegmasia cerulea dolens", "phlegmasia alba dolens", "May-Thurner syndrome", "iliac vein compression syndrome", "Paget-Schroetter syndrome", "effort thrombosis", "venous thoracic outlet syndrome", "catheter-related thrombosis", "IVC filter", "vena cava filter", "inferior vena cava filter", "heparin-induced thrombocytopenia", "HITT", "4Ts score", "factor V Leiden", "antithrombin III deficiency", "Virchow triad", "Caprini score", "Wells score", "post-thrombotic syndrome", "venous thrombectomy", "COBRRA", "ATTRACT trial", "HERDOO2"],
  scoreNodeId: "vascular-venous-conditions",
  scoreCategory: "SCORE · Vascular Venous · Diseases & Conditions",
  tags: ["vascular-venous", "vte", "anticoagulation", "absite", "score"],
  sourceId: PACKET,
  additionalSourceIds: [SCORE, SCORE_FILTER, FISER_HEME, FISER, COBRRA, SIR, SVS],
  blocks,
  reviewedAt: "2026-10-10T00:00:00.000Z",
});
