import { buildTopic, references, sourced } from "@/content/authoring";
import { TRAUMA_FASCIOTOMY_PACKET_SOURCE as PACKET } from "@/content/sources";
import type { TopicBlock } from "@/lib/types";

const blocks: TopicBlock[] = [
  sourced({
    id: "block-fasciotomy-summary",
    type: "summary",
    heading: "At a glance",
    text: "Acute compartment syndrome (ACS) is a rise in pressure within a closed osteofascial compartment that collapses the local arteriovenous perfusion gradient and produces tissue ischemia; fasciotomy is the surgical division of the enveloping fascia that decompresses the compartment and restores that gradient. The mechanism is the **arteriovenous gradient theory**: rising intracompartmental pressure raises intraluminal venous pressure, which collapses the pressure gradient that normally drives arterial blood into the capillary bed and shunts oxygenated blood away from the muscle. The resulting hypoxia and acidosis increase capillary permeability, which adds more edema, which raises the pressure further — a self-perpetuating **vicious cycle** that does not break on its own. The clock on that cycle is short: microscopic tissue compromise begins within **2 hours**, and nerve and muscle injury becomes irreversible in as little as **6 hours** of impaired perfusion, which is why compartment syndrome is treated as a surgical emergency rather than something to observe overnight.",
  }, PACKET),
  sourced({
    id: "block-fasciotomy-etiologies",
    type: "bullets",
    heading: "Etiologies",
    items: [
      "**Trauma is the most common cause**, and a tibial diaphyseal fracture is the single most commonly associated injury.",
      "**Reperfusion after revascularization** for acute limb ischemia is a major cause of compartment syndrome.",
      "Crush injury and intracompartmental hemorrhage, massive fluid resuscitation, blast or electrical injury, envenomation, and sepsis all raise compartment pressure by the same final pathway.",
      "Extrinsic compression — a tight cast or splint, a circumferential dressing, or a prolonged 'found-down' limb entrapment — can cause ACS without any fracture at all.",
    ],
  }, PACKET),
  sourced({
    id: "block-fasciotomy-epidemiology",
    type: "bullets",
    heading: "Epidemiology and risk factors",
    items: [
      "Incidence is roughly **3.1 per 100,000 per year**, with a strong male predominance — **7.3** per 100,000 in men against **0.7** per 100,000 in women.",
      "ACS complicates **1 to 9 percent** of lower-extremity fractures.",
      "A **popliteal artery injury** carries higher risk than a superficial femoral or more distal arterial injury, and combined arterial-and-venous injury carries more risk than an isolated injury.",
      "**Penetrating mechanism outranks blunt**, and **open fractures outrank closed** ones for risk — though an open injury does not exclude ACS, since the fascia itself can remain intact.",
      "The classic high-risk profile is a **young male** with a tibia or fibula fracture, a high-energy tibial plateau fracture, or a knee fracture-dislocation.",
      "Anticoagulation, prolonged limb elevation, and a prolonged 'found-down' presentation are additional risk factors independent of the injury itself.",
    ],
  }, PACKET),
  sourced({
    id: "block-fasciotomy-6ps-order",
    type: "prose",
    heading: "Reading the 6 Ps in order",
    text: "Diagnosis in an awake, examinable patient is primarily clinical, built around the '6 Ps': pain, pain on passive stretch, paresthesia, poikilothermia, pallor, paralysis, and pulselessness. **Pain out of proportion to the injury and pain on passive stretch of the compartment are the earliest and most reliable findings**, with pain on passive stretch the single most sensitive maneuver on exam. **Paralysis, pallor, and pulselessness are late findings that may never appear**, and by the time they do, the window for a good outcome has often already closed — only about **13 percent** of patients who progress to paralysis recover motor function, and a palpable distal pulse never rules out compartment syndrome, since compartment pressure rises well below arterial pressure. Individual signs carry low sensitivity but high specificity, so **3 or more** positive findings meaningfully raises sensitivity. No single exam settles the question — serial examination every **1 to 2 hours** over the following **24 to 48 hours** is what actually catches evolving compartment syndrome.",
  }, PACKET),
  sourced({
    id: "block-fasciotomy-6ps-table",
    type: "table",
    heading: "The 6 Ps",
    columns: ["Finding", "Timing", "Nuance"],
    rows: [
      ["Pain out of proportion", "Earliest", "Refractory to escalating analgesia and the most pronounced early sign"],
      ["Pain on passive stretch", "Early", "The single most sensitive maneuver on exam"],
      ["Paresthesia", "Early", "First sign of nerve ischemia — often the first web space, tracking the deep peroneal nerve"],
      ["Poikilothermia", "Intermediate", "The limb is cool compared with the contralateral side"],
      ["Pallor", "Intermediate to late", "Capillary refill is delayed"],
      ["Paralysis", "Late", "Signals impending irreversible damage; only about 13 percent of patients recover motor function once it appears"],
      ["Pulselessness", "Late", "A palpable distal pulse never rules out compartment syndrome"],
    ],
  }, PACKET),
  sourced({
    id: "block-fasciotomy-diagnosis-flow",
    type: "flow",
    heading: "The diagnostic decision",
    nodes: [
      { id: "suspect", label: "Suspected acute compartment syndrome in an injured or reperfused limb" },
      { id: "awake", label: "Awake, reliable, and can be serially examined" },
      { id: "obtunded", label: "Obtunded, sedated, under a regional block, or otherwise non-examinable, including many pediatric patients" },
      { id: "serial", label: "Serial clinical examination every 1 to 2 hours" },
      { id: "clinicalpos", label: "Exam is unequivocally positive for compartment syndrome", tone: "caution" },
      { id: "equivocal", label: "Exam is equivocal or the patient cannot reliably report symptoms" },
      { id: "icp", label: "Measure intracompartmental pressure within 5 cm of the fracture and in every compartment" },
      { id: "deltap", label: "Calculate delta P: diastolic blood pressure minus measured compartment pressure" },
      { id: "lowdelta", label: "Delta P under 30 mmHg", tone: "caution" },
      { id: "highdelta", label: "Delta P 30 mmHg or higher", tone: "good" },
      { id: "fasciotomy", label: "Proceed to fasciotomy", tone: "caution" },
      { id: "continue", label: "Continue serial reassessment and repeat measurement if suspicion persists", tone: "good" },
    ],
    edges: [
      { from: "suspect", to: "awake", label: "awake and examinable" },
      { from: "suspect", to: "obtunded", label: "cannot be reliably examined" },
      { from: "awake", to: "serial" },
      { from: "serial", to: "clinicalpos", label: "positive exam" },
      { from: "serial", to: "equivocal", label: "equivocal exam" },
      { from: "obtunded", to: "icp", label: "exam cannot be trusted" },
      { from: "equivocal", to: "icp", label: "adjunct needed" },
      { from: "clinicalpos", to: "fasciotomy", label: "clinical diagnosis alone is enough" },
      { from: "icp", to: "deltap" },
      { from: "deltap", to: "lowdelta" },
      { from: "deltap", to: "highdelta" },
      { from: "lowdelta", to: "fasciotomy" },
      { from: "highdelta", to: "continue" },
    ],
  }, PACKET),
  sourced({
    id: "block-fasciotomy-labs",
    type: "bullets",
    heading: "Supporting labs and normal values",
    items: [
      "Normal resting intracompartmental pressure is about **8 mm Hg**, the baseline a measured pressure is judged against.",
      "Send **creatine kinase**, urine for myoglobinuria, potassium, and BUN and creatinine — these track the muscle injury and its renal consequences rather than making the diagnosis themselves.",
    ],
  }, PACKET),
  sourced({
    id: "block-fasciotomy-deltap-current",
    type: "prose",
    heading: "Board answer versus current practice",
    text: "The board answer is that **delta P under 30 mmHg** — diastolic blood pressure minus the measured compartment pressure — is the trigger for fasciotomy, and it has replaced the older teaching of an absolute intracompartmental pressure of **30 to 45 mmHg**, which is no longer recommended as a stand-alone threshold because it ignores the patient's actual blood pressure and drives unnecessary operations. **McQueen and Court-Brown** established delta P over absolute pressure, and both the American College of Surgeons' orthopaedic trauma best-practices document and the AAOS endorse a delta P under 30 mmHg, sustained for **2 hours or more** on continuous monitoring, as very sensitive. Current diagnostic literature carries the caution further: no pressure measurement, delta P included, is sensitive or specific enough to overrule serial clinical examination in an awake, reliable patient — pressure measurement is an adjunct for the equivocal exam, the obtunded or sedated patient, a regional block, or a pediatric patient, not a substitute for watching the limb. Keep both facts in view: delta P under 30 mmHg is what gets keyed correctly on an exam, and a normal pressure reading in an awake patient with a worsening exam does not buy you out of the operating room.",
  }, PACKET),
  sourced({
    id: "block-fasciotomy-rutherford",
    type: "table",
    heading: "Rutherford acute limb ischemia classification",
    columns: ["Class", "Sensory", "Motor", "Doppler signals", "Implication"],
    rows: [
      ["Class I — viable", "Normal, no loss", "Normal, no deficit", "Both arterial and venous audible", "Not immediately threatened"],
      ["Class IIa — marginally threatened", "Loss limited to the toes", "None", "Arterial often inaudible, venous audible", "Salvageable if promptly treated"],
      ["Class IIb — immediately threatened", "Loss beyond the toes, with rest pain", "Mild to moderate weakness", "Arterial inaudible, venous audible", "Urgent revascularization, and a strong fasciotomy candidate"],
      ["Class III — irreversible", "Complete, anesthetic", "Complete paralysis", "Both arterial and venous inaudible", "Nonsalvageable — primary amputation, do not revascularize"],
    ],
  }, PACKET),
  sourced({
    id: "block-fasciotomy-pre-or",
    type: "bullets",
    heading: "Before the operating room",
    items: [
      "Remove or split any constrictive cast, splint, or circumferential dressing at the first suspicion of compartment syndrome.",
      "Keep the limb at the level of the heart rather than elevated.",
      "Correct hypotension while the operating room is being readied.",
    ],
  }, PACKET),
  sourced({
    id: "block-fasciotomy-indications",
    type: "bullets",
    heading: "Indications for fasciotomy",
    items: [
      "**Clinical acute compartment syndrome**, or a delta P under **30 mmHg** on adjunct measurement, is an indication for fasciotomy.",
      "**Prophylactic fasciotomy in acute limb ischemia** is reasonable (Class 2a) for Rutherford IIa or IIb limbs at the time of revascularization, and fasciotomy after any revascularization to prevent reperfusion sequelae is a Class 1 recommendation.",
      "Prolonged ischemia is its own trigger: **3 hours or more** in trauma, and **more than 6 hours** in thromboembolic acute limb ischemia, with many sources using that 6-hour ischemia time as the fasciotomy trigger on its own.",
    ],
  }, PACKET),
  sourced({
    id: "block-fasciotomy-contraindications",
    type: "bullets",
    heading: "When fasciotomy is the wrong operation",
    items: [
      "A **non-emergently diagnosed ACS beyond 24 to 36 hours** with already-necrotic muscle is a relative contraindication, because fasciotomy at that point risks fatal sepsis rather than salvaging the limb.",
      "A **Rutherford III, nonviable limb** is amputated, not decompressed — revascularizing it floods the circulation with potassium, myoglobin, and acid.",
    ],
  }, PACKET),
  sourced({
    id: "block-fasciotomy-landmarks",
    type: "bullets",
    heading: "Practice-changing landmarks",
    items: [
      "**McQueen and Court-Brown** established delta P over absolute pressure as the operative threshold.",
      "The **2024 ACC/AHA** multisociety lower-extremity peripheral artery disease guideline formalized prophylactic fasciotomy and concurrent amputation strategies in acute limb ischemia.",
      "Delayed fasciotomy is associated with markedly higher major amputation — **50 percent versus 5.9 percent** in one acute-limb-ischemia series.",
    ],
  }, PACKET),
  sourced({
    id: "block-fasciotomy-leg-technique",
    type: "sequence",
    heading: "Four-compartment lower leg fasciotomy, two-incision technique",
    steps: [
      { title: "Position and landmarks", detail: "Supine with access to the entire leg; identify the fibular shaft and the medial tibial border, since both incisions are placed relative to them." },
      { title: "Lateral incision", detail: "A longitudinal incision roughly **1 cm anterior to the fibular shaft**. Make a transverse fascial nick to find the anterior intermuscular septum, then open the fascia **1 cm anterior** to it to release the **anterior compartment** and **1 cm posterior** to it to release the **lateral compartment**, protecting the superficial peroneal nerve where it pierces the fascia in the distal third of the leg." },
      { title: "Compartments released laterally", detail: "The anterior compartment carries the tibialis anterior, extensor hallucis longus, extensor digitorum longus, and peroneus tertius, with the deep peroneal nerve and anterior tibial vessels at risk; the lateral compartment carries the peroneus longus and brevis, with the superficial peroneal nerve at risk." },
      { title: "Medial incision", detail: "A longitudinal incision roughly **2 cm posterior to the medial tibial border**, protecting the great saphenous vein and the saphenous nerve; open the superficial posterior compartment first, then detach the soleus origin from the posterior tibia to fully release the deep posterior compartment." },
      { title: "Compartments released medially", detail: "The superficial posterior compartment carries the gastrocnemius, soleus, and plantaris, with the sural nerve at risk; the deep posterior compartment carries the tibialis posterior, flexor hallucis longus, flexor digitorum longus, and popliteus, with the tibial nerve and posterior tibial vessels at risk." },
      { title: "Single-incision alternative", detail: "A single lateral, parafibular incision releasing all four compartments through one wound is an acceptable alternative, especially with a concurrent fracture." },
    ],
  }, PACKET),
  sourced({
    id: "block-fasciotomy-thigh-forearm",
    type: "bullets",
    heading: "Thigh and forearm fasciotomy",
    items: [
      "**Thigh, three compartments**: anterior (quadriceps, femoral nerve), posterior (hamstrings, sciatic nerve), and medial (adductors, obturator nerve); release through a long anterolateral incision opening the fascia lata for the anterior compartment, then retracting vastus lateralis and incising the lateral intermuscular septum for the posterior compartment, with a separate medial incision only if medial pressures stay high. Mortality runs up to **47 percent**, driven by the concomitant injuries that produce a thigh compartment syndrome in the first place, and wound infection runs up to **67 percent**.",
      "**Forearm, three compartments**: volar (flexors and pronators), dorsal (extensors), and the mobile wad (brachioradialis, extensor carpi radialis longus and brevis); release through a volar curvilinear S-shaped incision running from the thenar eminence and carpal tunnel across the antecubital fossa, including carpal tunnel release, with a separate straight dorsal incision if dorsal pressures remain elevated.",
    ],
  }, PACKET),
  sourced({
    id: "block-fasciotomy-open-wound",
    type: "warning",
    heading: "Leave the wound open",
    tone: "danger",
    text: "Leave every fasciotomy wound open at the index operation. **Primary closure at the index operation causes recurrent compartment syndrome**, converting a correctly performed decompression into a preventable failure.",
  }, PACKET),
  sourced({
    id: "block-fasciotomy-wound-care",
    type: "bullets",
    heading: "Wound care and closure",
    items: [
      "**Negative-pressure wound therapy** controls edema, speeds closure — roughly **9 days versus 14** — and reduces the need for a split-thickness skin graft, from **44 percent down to 17 percent** in the lower limb.",
      "Re-explore every **48 to 72 hours**, debriding all nonviable muscle before any closure is attempted.",
      "Progressive, or **'shoelace,'** closure using vessel loops allows delayed primary closure over serial re-explorations; one trial found tensioned wires carried a **higher infection risk** than sutures for the same technique.",
      "A **split-thickness skin graft**, meshed at roughly **1.0 to 1.5**, is used when skin retraction and edema prevent primary closure by day **7 to 10**.",
    ],
  }, PACKET),
  sourced({
    id: "block-fasciotomy-rhabdo",
    type: "bullets",
    heading: "Rhabdomyolysis and reperfusion management",
    items: [
      "**Aggressive intravenous crystalloid** is the cornerstone, titrated to a urine output of roughly **1 to 3 mL/kg/h** (up to about **300 mL/h**); a typical starting rate is about **400 mL/h**, with a reported range of **200 to 1000 mL/h**.",
      "Avoid nephrotoxins — **aminoglycosides, vancomycin, and NSAIDs** — on top of an already-injured kidney.",
      "**Sodium bicarbonate and mannitol add nothing over crystalloid alone** and are discouraged outside targeted trials; loop diuretics may worsen tubular obstruction.",
      "**Renal replacement therapy** is reserved for refractory hyperkalemia, acidosis, uremia, or fluid overload.",
    ],
  }, PACKET),
  sourced({
    id: "block-fasciotomy-outcomes",
    type: "bullets",
    heading: "Complications and outcomes",
    items: [
      "**Chronic venous insufficiency** is the most common long-term sequela, alongside scarring, nerve injury, foot drop from peroneal palsy, muscle contracture, infection, and amputation.",
      "Fasciotomy within **12 hours** of onset lets more than **70 percent** of patients regain normal function; delay beyond **12 hours** drops that to roughly **10 percent**.",
      "**Posterior compartment outcomes trail anterior compartment outcomes**, reflecting how often the deep posterior compartment is incompletely released.",
      "Persistent pain, paralysis, paresthesia, or a rising CK after fasciotomy should raise suspicion for an **incomplete release** or a re-occluded graft or artery.",
      "The **deep posterior compartment of the leg is the most commonly missed or incompletely released compartment** — the soleus origin has to come off the tibia to release it fully.",
    ],
  }, PACKET),
  references("block-fasciotomy-references", [PACKET]),
];

export const fasciotomyTopic = buildTopic({
  id: "00000000-0000-4000-8000-000000001215",
  versionId: "00000000-0000-4000-8000-000000001225",
  slug: "fasciotomy",
  title: "Fasciotomy",
  aliases: ["compartment syndrome", "acute compartment syndrome", "ACS", "fasciotomy", "four-compartment fasciotomy", "two-incision fasciotomy", "leg fasciotomy", "thigh fasciotomy", "forearm fasciotomy", "delta pressure", "delta P", "compartment pressure", "intracompartmental pressure", "ICP", "Rutherford", "Rutherford classification", "acute limb ischemia", "McQueen Court-Brown", "reperfusion injury", "crush syndrome", "rhabdomyolysis", "shoelace technique", "deep posterior compartment", "6 Ps"],
  scoreNodeId: "trauma-procedures",
  scoreCategory: "SCORE · Trauma · Operations & Procedures",
  tags: ["trauma", "compartment-syndrome", "operative-technique", "extremity", "absite", "score"],
  sourceId: PACKET,
  reviewedAt: "2026-08-18T00:00:00.000Z",
  blocks,
});
