import { buildTopic, references, sourced } from "@/content/authoring";
import { TRAUMA_FAST_PACKET_SOURCE as PACKET } from "@/content/sources";
import type { TopicBlock } from "@/lib/types";

const blocks: TopicBlock[] = [
  sourced({
    id: "block-fast-summary",
    type: "summary",
    heading: "At a glance",
    text: "FAST (Focused Assessment with Sonography for Trauma) is a bedside, noninvasive point-of-care ultrasound performed as an adjunct to the circulation portion of the primary survey, screening for hemoperitoneum and hemopericardium; the extended exam, E-FAST, adds bilateral lung windows to screen for hemothorax and pneumothorax. The exam answers a binary yes-or-no question about pathologic free fluid or air — it does **not** identify the source organ, grade the injury, or quantify how much blood has been lost. That matters because the leading cause of early trauma death is hemorrhagic shock, physical exam is unreliable for detecting intracavitary blood, and FAST provides the rapid triage information that predicts whether a patient needs hemorrhage-control surgery right now. The exam is far more **specific than sensitive**: a positive scan is highly reliable, but a negative scan never fully excludes injury, which is the single governing idea behind everything downstream in workup and disposition. This topic covers technique, the five standard windows, diagnostic performance, the stability-driven decision algorithm, and the exam's characteristic blind spots.",
  }, PACKET),
  sourced({
    id: "block-fast-physiology",
    type: "bullets",
    heading: "Definition and physiology",
    items: [
      "Detection requires roughly **150 to 200 mL** of intraperitoneal free fluid for reliable identification; pleural ultrasound detects as little as roughly **20 mL** of pleural fluid, and pericardial ultrasound detects as little as roughly **20 mL** of pericardial fluid.",
      "Free blood is anechoic to hypoechoic (black) and pools in dependent spaces, solid parenchyma is hyperechoic (gray), and air produces reverberation artifact that abolishes the pleural sliding signal.",
    ],
  }, PACKET),
  sourced({
    id: "block-fast-indications",
    type: "bullets",
    heading: "Indications and contraindications",
    items: [
      "ACEP indications: rapid torso evaluation for traumatic free fluid or pathologic air in the peritoneal, pericardial, and pleural cavities, especially the hypotensive blunt trauma patient and penetrating thoracoabdominal wounds where cavity violation is uncertain.",
      "No absolute contraindications exist.",
      "Relative contraindications are an immediate need for laparotomy or extensive overlying wounds and tissue destruction; even when heading emergently to the operating room, a brief look for tamponade or tension pneumothorax — both treatable before transfer — is appropriate.",
    ],
  }, PACKET),
  sourced({
    id: "block-fast-equipment",
    type: "table",
    heading: "Equipment and probe selection",
    columns: ["Window", "Probe", "Frequency", "Rationale"],
    rows: [
      ["Abdominal / general survey", "Curvilinear (convex)", "2 to 5 MHz", "Deep penetration; can complete all views without changing probes"],
      ["Pericardial (subxiphoid)", "Phased array (cardiac)", "Low frequency", "Small footprint fits the subxiphoid and intercostal windows"],
      ["Pleura / lung sliding", "Linear", "5 to 12 MHz", "Superior near-field resolution of the pleural line"],
    ],
  }, PACKET),
  sourced({
    id: "block-fast-technique",
    type: "prose",
    heading: "Scanning technique",
    text: "Set gain so that blood within a cardiac chamber appears completely anechoic, or black.",
  }, PACKET),
  sourced({
    id: "block-fast-sequence",
    type: "sequence",
    heading: "Examination sequence and windows",
    steps: [
      { title: "Subxiphoid (pericardial)", detail: "Probe flat in the epigastrium, angled toward the left shoulder under the xiphoid process. A positive view shows an anechoic stripe separating the visceral and parietal pericardium." },
      { title: "RUQ (Morison's pouch)", detail: "Right midaxillary line, ribs 9 through 12. Evaluates the hepatorenal recess, the diaphragm-liver interface, and the inferior renal pole — the most sensitive single view for blunt hemoperitoneum because it is the most dependent supine space. A positive view shows fluid in Morison's pouch or the suprahepatic space." },
      { title: "LUQ (splenorenal)", detail: "Left posterior axillary line, ribs 8 through 11, positioned more superior and posterior than the RUQ view (\"knuckles to the bed\"). Fluid classically collects in the subphrenic space first, then the splenorenal recess." },
      { title: "Suprapubic (pelvic)", detail: "1 to 2 cm above the pubic symphysis, transverse and sagittal planes. Evaluates the rectovesical pouch in men and the pouch of Douglas / rectouterine space in women — the most dependent space overall. Scan with a full bladder as the acoustic window." },
      { title: "Thoracic (E-FAST)", detail: "Longitudinal over the 2nd through 4th intercostal spaces at the midclavicular line. Normal is lung sliding (\"ants marching,\" the seashore sign on M-mode); absent sliding raises suspicion for pneumothorax, and the lung point is the most specific sign." },
    ],
  }, PACKET),
  sourced({
    id: "block-fast-performance",
    type: "table",
    heading: "Diagnostic performance",
    columns: ["Target", "Sensitivity", "Specificity"],
    rows: [
      ["Intraperitoneal free fluid (pooled E-FAST meta-analysis)", "74 percent", "98 percent"],
      ["Blunt abdominal free fluid (range across studies)", "73 to 99 percent", "94 to 100 percent"],
      ["Pericardial effusion (pooled)", "91 percent", "94 percent"],
      ["Pneumothorax — ultrasound (meta-analysis)", "roughly 83 to 91 percent", "roughly 99 percent"],
      ["Pneumothorax — supine chest x-ray", "roughly 28 to 47 percent", "roughly 100 percent"],
      ["Prehospital FAST for hemoperitoneum", "63 percent", "97 percent"],
      ["Lung point (for pneumothorax)", "59 to 75 percent", "99 to 100 percent"],
    ],
  }, PACKET),
  sourced({
    id: "block-fast-performance-notes",
    type: "prose",
    heading: "Interpreting the numbers",
    text: "Sensitivity is highest in the hypotensive patient, who has more free fluid to detect, and is higher in blunt trauma than in penetrating abdominal trauma.",
  }, PACKET),
  sourced({
    id: "block-fast-sensitivity-trap",
    type: "warning",
    heading: "The sensitivity trap",
    tone: "danger",
    text: "**A positive FAST rules in; a negative FAST does not rule out injury.** Up to **29 percent** of patients with a negative FAST still have an intra-abdominal injury, and retroperitoneal bleeding is systematically missed by the exam. If shock persists despite a negative scan, suspect a false negative — from the retroperitoneum, the pelvis, or simply insufficient free fluid to detect — and proceed to DPA or laparotomy rather than reassurance.",
  }, PACKET),
  sourced({
    id: "block-fast-algorithm",
    type: "flow",
    heading: "Clinical decision algorithm",
    nodes: [
      { id: "present", label: "Suspected traumatic hemoperitoneum, hemopericardium, or pneumothorax" },
      { id: "unstable", label: "Hemodynamically unstable", tone: "caution" },
      { id: "stable", label: "Hemodynamically stable" },
      { id: "unstable-abd-pos", label: "FAST positive, abdomen", tone: "caution" },
      { id: "unstable-peri-pos", label: "FAST positive, pericardium", tone: "caution" },
      { id: "unstable-equivocal", label: "FAST equivocal or negative, shock ongoing", tone: "caution" },
      { id: "laparotomy", label: "Immediate laparotomy (damage-control)", tone: "caution" },
      { id: "pericardial-action", label: "Pericardial window, sternotomy, or resuscitative thoracotomy", tone: "caution" },
      { id: "dpa-action", label: "DPA/DPL, pelvic x-ray, bilateral tube thoracostomy — suspect false negative", tone: "caution" },
      { id: "stable-pos", label: "FAST positive" },
      { id: "stable-neg", label: "FAST negative" },
      { id: "ct-grading", label: "CT abdomen/pelvis with IV contrast for grading", tone: "good" },
      { id: "serial-exams", label: "Serial exams, ± repeat FAST, ± CT by mechanism", tone: "good" },
    ],
    edges: [
      { from: "present", to: "unstable", label: "unstable" },
      { from: "present", to: "stable", label: "stable" },
      { from: "unstable", to: "unstable-abd-pos", label: "positive, abdomen" },
      { from: "unstable", to: "unstable-peri-pos", label: "positive, pericardium" },
      { from: "unstable", to: "unstable-equivocal", label: "equivocal/negative, shock persists" },
      { from: "unstable-abd-pos", to: "laparotomy" },
      { from: "unstable-peri-pos", to: "pericardial-action" },
      { from: "unstable-equivocal", to: "dpa-action" },
      { from: "stable", to: "stable-pos", label: "positive" },
      { from: "stable", to: "stable-neg", label: "negative" },
      { from: "stable-pos", to: "ct-grading" },
      { from: "stable-neg", to: "serial-exams" },
    ],
  }, PACKET),
  sourced({
    id: "block-fast-algorithm-notes",
    type: "bullets",
    heading: "Algorithm notes",
    items: [
      "CT abdomen/pelvis with IV contrast is the gold standard in the stable or stabilized patient, with sensitivity and specificity of roughly **96 to 100 percent**.",
      "Resuscitative thoracotomy is indicated for a systolic blood pressure at or below **60 mmHg**, or traumatic arrest with **15 minutes** of CPR; survival exceeds **15 percent** in penetrating trauma, especially with tamponade, versus **2 percent** in blunt trauma.",
    ],
  }, PACKET),
  sourced({
    id: "block-fast-limitations",
    type: "bullets",
    heading: "Limitations, false negatives, and false positives",
    items: [
      "False negatives from retroperitoneal hemorrhage: FAST does not survey Zone 1 (aorta/IVC), Zone 2 (perirenal), or Zone 3 (pelvic) bleeding, and it does not exclude renal vein, pancreatic, or duodenal injury.",
      "False negatives from hollow viscus or mesenteric injury: these generate insufficient early free fluid, and mesenteric fluid in particular may be missed entirely.",
      "False negatives from clotted or organized blood: it appears echogenic rather than anechoic and can be mistaken for solid tissue.",
      "False negatives from pericardial laceration: blood can decompress into the pleural space, producing a falsely reassuring subxiphoid view despite a real cardiac injury.",
      "Technical false negatives: obesity, subcutaneous emphysema, and overlying dressings all degrade image quality.",
      "False positives: pre-existing ascites from cirrhosis or heart failure, peritoneal dialysis fluid, a chronic pericardial effusion, and physiologic pelvic fluid or a ruptured ovarian cyst in a woman of reproductive age can all mimic a positive scan.",
    ],
  }, PACKET),
  sourced({
    id: "block-fast-surveillance",
    type: "bullets",
    heading: "Surveillance and special populations",
    items: [
      "Repeat FAST and clinical re-examination whenever vital signs change; a single negative scan is never definitive.",
      "Pediatric sensitivity is markedly lower, roughly **42 to 52 percent**, with a negative predictive value of **93 to 96 percent**; a positive pediatric FAST warrants urgent CT, and a negative scan with ongoing clinical suspicion still needs CT.",
      "After resuscitative thoracotomy, FAST sensitivity is roughly **66 percent** and specificity roughly **85 percent** for intra-abdominal hemorrhage; a positive scan goes to laparotomy, and a negative scan prompts DPA or mandatory exploration.",
    ],
  }, PACKET),
  sourced({
    id: "block-fast-pearls",
    type: "bullets",
    heading: "Board pearls",
    items: [
      "Unstable plus a positive abdominal FAST goes to the OR, not the CT scanner — a hypotensive trauma patient does not belong in the CT scanner.",
      "The most dependent supine spaces are Morison's pouch for hepatic-side bleeding and the pelvis overall — the earliest sites where free fluid accumulates.",
      "In the LUQ, blood collects in the subphrenic space first, above the spleen, not in the splenorenal recess — a classic missed-view pitfall; scan higher and more posterior.",
      "The lung point is pathognomonic for pneumothorax (specificity roughly **99 to 100 percent**); absent lung sliding plus absent B-lines plus absent lung pulse support pneumothorax, while the presence of B-lines or lung sliding excludes pneumothorax at that spot.",
      "Free fluid on CT without a solid-organ injury, especially with a seat-belt sign or Chance fracture, means occult hollow viscus or mesenteric injury until proven otherwise.",
      "Tamponade physiology can be masked by hypovolemia — jugular venous distension may be absent until volume is restored — so keep a low threshold for pericardial window.",
      "Traumatic arrest with cardiac standstill and no pericardial fluid on FAST carries **0 percent** survival, supporting termination of resuscitative efforts.",
    ],
  }, PACKET),
  sourced({
    id: "block-fast-board-vs-current",
    type: "prose",
    heading: "Board answer versus current practice",
    text: "Board-classic ATLS still teaches diagnostic peritoneal lavage as an adjunct for the unstable patient with an equivocal FAST, but in current practice FAST plus CT have largely supplanted DPL; it persists mainly as a niche tool for the unstable patient with an indeterminate FAST. Classic teaching also relies on the supine chest x-ray to diagnose pneumothorax, but current evidence shows E-FAST is roughly twice as sensitive — ultrasound roughly **83 to 91 percent** versus x-ray roughly **28 to 47 percent** — and should be the first-line study in the unstable patient.",
  }, PACKET),
  references("block-fast-references", [PACKET]),
];

export const fastExamTopic = buildTopic({
  id: "00000000-0000-4000-8000-000000001214",
  versionId: "00000000-0000-4000-8000-000000001224",
  slug: "focused-assessment-with-sonography-for-trauma",
  title: "Focused Assessment with Sonography for Trauma (FAST)",
  aliases: ["FAST", "E-FAST", "eFAST", "extended FAST", "focused assessment with sonography for trauma", "trauma ultrasound", "POCUS", "point-of-care ultrasound", "Morison's pouch", "hepatorenal recess", "splenorenal recess", "subxiphoid view", "pericardial window", "lung sliding", "lung point", "B-lines", "seashore sign", "barcode sign", "stratosphere sign", "hemoperitoneum", "hemopericardium", "pneumothorax", "hemothorax", "DPA", "diagnostic peritoneal aspiration", "cardiac tamponade"],
  scoreNodeId: "trauma-procedures",
  scoreCategory: "SCORE · Trauma · Operations & Procedures",
  tags: ["trauma", "fast", "ultrasound", "point-of-care-ultrasound", "diagnostics", "absite", "score"],
  sourceId: PACKET,
  blocks,
  reviewedAt: "2026-08-18T00:00:00.000Z",
});
