import { buildTopic, references, sourced } from "@/content/authoring";
import { ASCRS_HEMORRHOIDS_SOURCE as ASCRS, FISER_ANORECTAL_SOURCE as FISER, HEMORRHOIDS_PACKET_SOURCE as PACKET, SCORE_HEMORRHOIDS_SOURCE as SCORE } from "@/content/sources";
import type { TopicBlock } from "@/lib/types";

const blocks: TopicBlock[] = [
  sourced({
    id: "block-hemorrhoids-summary",
    type: "summary",
    heading: "At a glance",
    text: "Hemorrhoids are **normal** anal cushions; hemorrhoidal disease is what happens when straining engorges them and stretches them loose from their anchoring. Everything testable hangs off the **dentate line** — above it the cushion is insensate and bleeds painlessly, below it the anoderm is somatic and hurts when it thromboses. Grade the internal component, start every grade on fiber and fluid, and escalate through the office to the operating room.",
  }, PACKET),
  sourced({
    id: "block-hemorrhoids-dentate",
    type: "table",
    heading: "Above and below the dentate line",
    columns: ["Feature", "Internal hemorrhoid", "External hemorrhoid"],
    rows: [
      ["Position", "**Above** the dentate line", "**Below** the dentate line"],
      ["Lining", "Columnar and transitional mucosa", "Squamous **anoderm**"],
      ["Innervation", "**Visceral and autonomic** — insensate", "**Somatic**, via the inferior rectal nerve — sensate"],
      ["Typical complaint", "**Painless** bleeding and prolapse", "**Pain** when it thromboses"],
      ["Venous drainage", "Superior rectal vein to the inferior mesenteric vein — **portal**", "Middle and inferior rectal veins to the internal iliac — **systemic**"],
      ["What you can do in clinic", "Band it, inject it, or coagulate it", "**Never band it** — excise a thrombosis instead"],
    ],
  }, PACKET),
  sourced({
    id: "block-hemorrhoids-anatomy",
    type: "bullets",
    heading: "Anatomy worth memorizing",
    items: [
      "Anal cushions are discrete submucosal masses of **blood vessels**, smooth muscle drawn from the internal sphincter and conjoined longitudinal muscle, and elastic connective tissue.",
      "The submucosa of the anal canal is interrupted rather than continuous, and that interruption is what defines **three columns**: **left lateral**, **right anterior**, and **right posterior**.",
      "The cushions contribute roughly **5% to 15%** of resting fecal continence, and the number keyed on older exams is **5%**.",
      "Arterial supply arrives from three named vessels.",
      "- **Superior rectal artery** — the terminal branch of the **inferior mesenteric artery**",
      "- **Middle rectal artery** — a branch of the **internal iliac** artery",
      "- **Inferior rectal artery** — a branch of the **internal pudendal artery**, itself off the internal iliac",
      "Venous drainage straddles a **portosystemic watershed**, which is why the internal and external plexuses answer to different circulations.",
      "- **Superior rectal vein** drains to the **inferior mesenteric vein** and onward to the **portal** system",
      "- **Middle and inferior rectal veins** drain to the internal iliac and pudendal veins and onward to the **systemic** circulation",
    ],
  }, PACKET),
  sourced({
    id: "block-hemorrhoids-pathophys",
    type: "prose",
    heading: "Why a normal cushion becomes a disease",
    text: "Chronic straining slows venous outflow from the cushion, which engorges. The overlying mucosa or anoderm stretches, and the muscular anchoring that holds the cushion against the sphincter — **Treitz's muscle** — attenuates. What follows is **prolapse**. The useful consequence of framing it this way is that hemorrhoidal disease is a **degenerative and vascular** process of a normal structure, not a varicosity; a patient whose rectal bleeding really is varicose has **portal hypertension** and a different operation.",
  }, PACKET),
  sourced({
    id: "block-hemorrhoids-risk",
    type: "bullets",
    heading: "Epidemiology and risk factors",
    items: [
      "**Chronic constipation and straining** is the most common association and the one to name first.",
      "Prevalence is about **4.4%** by classic United States self-report data, and contemporary reviews put the burden near **10 million** Americans.",
      "Peak age is **45 to 65 years**, and hemorrhoids are uncommon before **20** — new anorectal symptoms in a young patient deserve a different differential.",
      "Pregnancy is a major contributor, with thrombosis in roughly **8%** in the third trimester and **20%** postpartum.",
      "Low-fiber diet, prolonged toilet sitting, obesity, pelvic floor dysfunction, chronic cough, and advancing age fill out the list.",
      "Suspect something other than hemorrhoids in **cirrhosis or portal hypertension**, in inflammatory bowel disease, and in anyone over 50 with a change in bowel habit or iron-deficiency anemia.",
    ],
  }, PACKET),
  sourced({
    id: "block-hemorrhoids-presentation",
    type: "bullets",
    heading: "How it presents",
    items: [
      "**Internal**: intermittent, **painless bright red blood per rectum** with defecation — on the paper or dripping into the bowl — with prolapse, mucus discharge, and pruritus.",
      "**External**: usually silent until it thromboses, and then sudden, severe, constant perianal pain with a tender, tense, bluish perianal mass.",
      "Bleeding is bright red and ranges from rare to several times daily; blood mixed into stool or melena is not hemorrhoidal until proven otherwise.",
      "**Red flags that mandate a workup beyond the anus**: anemia, melena, weight loss, change in stool caliber or bowel habit, age **50 or older**, and a family history of colorectal cancer.",
    ],
  }, PACKET),
  sourced({
    id: "block-hemorrhoids-workup",
    type: "sequence",
    heading: "Work it up in this order",
    steps: [
      { title: "History", detail: "Ask specifically about **bowel habits and any change in them**, bleeding pattern, pain, and protrusion — most of the differential separates on history alone." },
      { title: "Inspect the perineum", detail: "Look at skin, perineum, and anal opening, then have the patient **bear down** to bring out prolapse and judge sphincter tone." },
      { title: "Digital rectal examination", detail: "Assess **sphincter tone, masses, and pain**. Internal hemorrhoids are usually not palpable, so a normal exam does not exclude them." },
      { title: "Anoscopy", detail: "**Required** for definitive assessment and grading of internal hemorrhoids, because it is the only step that visualizes them directly." },
      { title: "Endoscopy when indicated", detail: "Add **colonoscopy** for atypical bleeding, anemia or melena, changed bowel habits, an age or risk profile meeting screening thresholds, or to exclude inflammatory bowel disease and malignancy." },
    ],
  }, SCORE),
  sourced({
    id: "block-hemorrhoids-colonoscopy",
    type: "prose",
    heading: "↳ When colonoscopy can be omitted",
    text: "The ASCRS recommendation here is **conditional**, not absolute: colonoscopy is indicated in **select** patients with symptomatic hemorrhoids and rectal bleeding. It may reasonably be **omitted** in a young patient with no risk factors and no family history whose bleeding **resolves with hemorrhoid therapy**. The trap is treating a resolved symptom as a completed workup in a patient who actually met screening criteria.",
  }, ASCRS),
  sourced({
    id: "block-hemorrhoids-grading",
    type: "table",
    heading: "Grade the internal hemorrhoid",
    columns: ["Grade", "Older name", "Definition", "Where treatment usually starts"],
    rows: [
      ["**I**", "Primary", "Bleeds but does **not** prolapse", "Fiber and medical therapy; office procedure if refractory"],
      ["**II**", "Secondary", "Prolapses and reduces **spontaneously**", "Fiber, then **rubber band ligation**"],
      ["**III**", "Tertiary", "Prolapses and needs **manual** reduction", "Banding in selected patients, or **excisional hemorrhoidectomy**"],
      ["**IV**", "Quaternary", "Prolapsed and **irreducible**", "**Excisional hemorrhoidectomy**"],
    ],
  }, PACKET),
  sourced({
    id: "block-hemorrhoids-conservative",
    type: "bullets",
    heading: "First-line therapy, at every grade",
    items: [
      "**Fiber and fluid** is the only intervention with solid randomized support — a Cochrane review of 7 RCTs with 378 patients found a **53% reduction** in persistent symptoms (RR 0.47) and less bleeding (RR 0.50), with little effect on prolapse, pain, or itching.",
      "Target **20 to 30 g of fiber daily** by the ACG, or **25 g for women and 38 g for men**, with **6 to 8 glasses** of fluid a day; psyllium or methylcellulose closes the gap.",
      "Behavioral change carries real weight: stop straining, and **limit toilet time** — no phone and no reading material.",
      "**Phlebotonics and flavonoids** such as diosmin and calcium dobesilate reduce bleeding, pruritus, and discharge but **not pain**, and symptoms recur in up to **80%** within 3 to 6 months of stopping.",
      "**Topical agents** — hydrocortisone, pramoxine, phenylephrine, witch hazel — rest on low-quality evidence and treat symptoms only; avoid prolonged steroid or anesthetic use, which sensitizes the skin.",
      "**Sitz baths** are standard advice for an acute flare or a thrombosis, notwithstanding thin evidence that they reduce pain.",
      "Topical **nitrates and calcium channel blockers** help the selected patient with elevated sphincter tone.",
      "In **pregnancy**, manage conservatively and expect postpartum resolution; the exception that forces an operation is **strangulation or gangrene**.",
    ],
  }, PACKET),
  sourced({
    id: "block-hemorrhoids-mimics",
    type: "table",
    heading: "What it is not",
    columns: ["Mimic", "The clue that gives it away", "What to do instead"],
    rows: [
      ["**Rectal varices**", "**Cirrhosis** and portal hypertension in the history; the superior rectal vein is engorged as a portosystemic collateral", "Treat the **portal hypertension** — nonselective beta blocker, and TIPS in selected patients. Do **not** perform a standard hemorrhoidectomy"],
      ["**Full-thickness rectal prolapse**", "**Concentric** rings of full-thickness rectal wall, starting 6 to 7 cm from the verge; prolapsed hemorrhoids show **radial** grooves in a rosette", "Rectopexy or perineal rectosigmoidectomy, chosen by fitness"],
      ["**Anal fissure**", "Tearing pain **during and after** defecation with a posterior midline tear, not a mass", "Fiber, sitz baths, and a topical relaxant before any sphincterotomy"],
      ["**Anorectal malignancy**", "Change in bowel habit, weight loss, anemia, or a firm fixed lesion", "**Endoscopy and biopsy** before anything is banded or excised"],
      ["**Abscess or fistula**", "Fever, fluctuance, induration, or drainage rather than bleeding", "Drainage, and delineation of the tract"],
    ],
  }, PACKET),
  sourced({
    id: "block-hemorrhoids-splits",
    type: "table",
    heading: "Board answer versus current practice",
    columns: ["Question", "Board answer", "Current practice"],
    rows: [
      ["Share of continence owed to the cushions", "**5%**", "**5% to 15%**, with 5% the figure the SCORE module still prints"],
      ["Arterial supply of the cushions", "Superior and middle rectal arteries", "Three vessels — superior, middle, and **inferior rectal** — the inferior arising from the internal pudendal artery"],
      ["Office procedure on an anticoagulated patient", "Banding is **contraindicated**; choose **sclerotherapy**", "The 2024 ASCRS guideline advises **caution and holding agents when possible** rather than an absolute bar, and a retrospective clopidogrel cohort found no significant excess post-band bleeding. Sclerotherapy remains the safer office choice"],
      ["Naming the internal grades", "**Primary through quaternary**", "**Grades I through IV**, though older stems still key on the ordinal words"],
    ],
  }, PACKET),
  sourced({
    id: "block-hemorrhoids-varices-warning",
    type: "warning",
    tone: "danger",
    heading: "Cirrhosis plus rectal bleeding is varices until proven otherwise",
    text: "The superior rectal vein is a **portosystemic collateral**, so portal hypertension engorges it exactly where hemorrhoids live. Operating on that as if it were hemorrhoidal disease invites **torrential, hard-to-control bleeding** from a decompressing collateral bed. Look for the cirrhosis before you look at the anus, and treat the **portal pressure** rather than the column.",
  }, PACKET),
  sourced({
    id: "block-hemorrhoids-pearls",
    type: "bullets",
    heading: "Board pearls",
    items: [
      "**Above versus below the dentate line is the whole exam**: internal means painless bleeding, visceral innervation, and portal drainage; external means painful thrombosis, somatic innervation via the inferior rectal nerve, and systemic drainage.",
      "**Never band an external hemorrhoid** — it is somatically innervated and the patient will not forgive you.",
      "**Concentric rings means rectal prolapse; radial grooves means prolapsed hemorrhoids.**",
      "**Cirrhosis plus rectal bleeding means varices**, and the treatment is directed at portal pressure.",
      "**Strangulated or gangrenous hemorrhoids are a surgical emergency**, pregnancy included.",
      "New anorectal bleeding **under age 20 or over age 50** should widen the differential rather than confirm the obvious.",
      "Fiber and fluid is the **only** conservative measure with randomized evidence behind it, and it belongs at every grade.",
    ],
  }, PACKET),
  references("block-hemorrhoids-references", [PACKET, SCORE, ASCRS, FISER]),
];

export const hemorrhoidsTopic = buildTopic({
  id: "00000000-0000-4000-8000-000000002110",
  versionId: "00000000-0000-4000-8000-000000002111",
  slug: "hemorrhoids",
  title: "Hemorrhoids",
  aliases: ["hemorrhoid", "haemorrhoids", "hemorrhoidal disease", "internal hemorrhoids", "external hemorrhoids", "anal cushions", "anal cushion", "piles", "thrombosed external hemorrhoid", "dentate line", "pectinate line", "anoderm", "bright red blood per rectum", "BRBPR", "hematochezia", "rectal bleeding", "Treitz's muscle", "superior rectal artery", "inferior rectal artery", "middle rectal artery", "rectal varices", "hemorrhoid grading", "grade IV hemorrhoids", "strangulated hemorrhoids"],
  scoreNodeId: "anorectal-conditions",
  scoreCategory: "SCORE · Anorectal · Diseases & Conditions",
  tags: ["anorectal", "hemorrhoids", "colorectal", "anatomy", "absite", "score"],
  sourceId: PACKET,
  additionalSourceIds: [SCORE, ASCRS, FISER],
  blocks,
  reviewedAt: "2026-08-25T00:00:00.000Z",
});
