import { buildTopic, references, sourced, sourcedUnits } from "@/content/authoring";
import {
  FISER_VASCULAR_SOURCE as FISER,
  HAKIM_RULE_OF_SIXES_2022_SOURCE as HAKIM,
  HEMODIALYSIS_CATHETER_PACKET_SOURCE as PACKET,
  KDOQI_VASCULAR_ACCESS_2019_SOURCE as KDOQI,
  SCORE_VASCULAR_ACCESS_DIALYSIS_SOURCE as SCORE,
} from "@/content/sources";
import type { TopicBlock } from "@/lib/types";

const blocks: TopicBlock[] = [
  sourced({
    id: "block-hdc-summary",
    type: "summary",
    heading: "At a glance",
    text: "A hemodialysis catheter is a **dual-lumen central venous catheter**: one lumen draws blood into the circuit, the other returns it, and the tip sits at the **cavoatrial junction** or right atrium. It is the last choice in the access hierarchy — **fistula, then graft, then catheter** — because catheters bring **bloodstream infection**, **central venous stenosis**, and **dysfunction**. The exam lives in four places: the **right internal jugular** as the first site, **never the subclavian** in anyone who may need permanent access, which catheter infections force **removal**, and the **Rule of 6s** for the fistula that should replace the catheter.",
  }, PACKET),
  sourced({
    id: "block-hdc-why-last",
    type: "bullets",
    heading: "Why catheters come last",
    items: [
      "**Access hierarchy**: autogenous AV fistula, then AV graft, then tunneled catheter.",
      "Starting dialysis on a catheter rather than a fistula carries about **51% higher mortality** (adjusted hazard ratio 1.51).",
      "Catheter dependence is mostly a timing failure: about **80%** of incident patients lack a working AV access, and **82%** of US patients start hemodialysis on a tunneled catheter.",
      "Other reasons: a bridge while a fistula or graft matures, failed peritoneal dialysis or transplant, exhausted AV options, limited life expectancy, or patient preference.",
      "**Central venous stenosis** comes from catheter contact with the vein wall, which drives **intimal hyperplasia**; angulated routes — subclavian and left-sided — touch the wall most.",
      "A **fibrin sheath** begins coating the catheter within **24 hours** and matures into a sleeve that acts as a **flap valve**: the line injects but will not aspirate.",
    ],
  }, PACKET),
  sourcedUnits({
    id: "block-hdc-types",
    type: "table",
    heading: "Nontunneled versus tunneled",
    columns: ["Feature", "Nontunneled (Quinton, Vas-Cath)", "Tunneled cuffed (Permcath, Tesio, Palindrome)"],
    rows: [
      ["Design", "Double-lumen, **noncuffed**, not tunneled", "Double-lumen with a **Dacron cuff**, tunneled under the skin"],
      ["Placement", "Bedside, percutaneous", "Under **fluoroscopy**, in interventional radiology or the operating room"],
      ["Best for", "Acutely ill patients needing **urgent** hemodialysis", "Long-term dialysis while awaiting permanent AV access, or access of last resort"],
      ["Infection risk", "**Highest** of the catheter types", "Lower than nontunneled, still higher than a fistula or graft"],
    ],
  }, [[PACKET, SCORE], [SCORE], [SCORE], [PACKET]]),
  sourced({
    id: "block-hdc-sites",
    type: "sequence",
    heading: "Site selection, in order",
    steps: [
      { title: "Right internal jugular", detail: "First choice: a **straight course** through the brachiocephalic vein and SVC to the right atrium, with the least wall contact, the fewest malpositions (**1.4%** against 9.1% subclavian), the lowest stenosis rate, and the best flow." },
      { title: "Left internal jugular", detail: "An angulated course, so more malposition, more replacements, and shorter patency." },
      { title: "External jugular or femoral", detail: "When the internal jugular veins are unavailable. The femoral vein suits short-term or rescue use and spares the arm veins, at the cost of more infection and thrombosis." },
      { title: "Subclavian", detail: "Avoid whenever future AV access is possible." },
      { title: "Salvage routes", detail: "Translumbar or transhepatic IVC catheters once every conventional site is exhausted." },
    ],
  }, PACKET),
  sourcedUnits({
    id: "block-hdc-site-rules",
    type: "bullets",
    heading: "↳ Site rules that protect the future fistula",
    items: [
      "**Never** place a catheter on the side of an existing or planned fistula or graft — the stenosis it causes fails the access downstream.",
      "Avoid the **subclavian vein** in anyone who may need long-term access: central stenosis after subclavian catheters runs about **42%** against about **10%** after internal jugular catheters.",
      "Subclavian stenosis can appear within **6 weeks** of a line, and it closes off the whole arm on that side for future access.",
    ],
  }, [[FISER, PACKET], [PACKET], [SCORE]]),
  sourced({
    id: "block-hdc-subclavian-warning",
    type: "warning",
    tone: "pearl",
    heading: "The subclavian rule is a dialysis rule",
    text: "In general ICU patients who will never need dialysis access, ultrasound-era data show the **subclavian** site has the lowest infection and thrombosis risk, without the mechanical penalty it once carried. Avoid the subclavian because of **central venous stenosis** in kidney patients — do not carry that rule to every central line.",
  }, PACKET),
  sourced({
    id: "block-hdc-insertion",
    type: "bullets",
    heading: "Insertion and infection prevention",
    items: [
      "**Real-time ultrasound** for every insertion — fewer attempts, fewer arterial punctures and hematomas.",
      "Stop and reassess after **3 attempts**; complications climb sharply beyond that.",
      "**Seldinger** technique with a micropuncture needle, and never force the wire.",
      "If the needle alone enters an artery, **remove it and hold pressure**. Never dilate or pass a sheath; a dilated arterial injury needs open or endovascular repair.",
      "Central-line bundle: hand hygiene, **maximal sterile barriers**, **chlorhexidine** skin preparation, avoiding the femoral site when feasible, a time-out, and a daily review of whether the line is still needed.",
    ],
  }, PACKET),
  sourced({
    id: "block-hdc-complications",
    type: "table",
    heading: "Sort the complication",
    columns: ["Problem", "Clue", "Workup", "Management"],
    rows: [
      ["Fibrin sheath or catheter thrombus", "Flows below prescription; **injects but won't aspirate**", "Confirm tip position at the cavoatrial junction on fluoroscopy or chest film", "**Alteplase** lock, then sheath disruption, then **exchange over a guidewire**"],
      ["Catheter bloodstream infection", "Fever or rigors during or just after a run; exit-site pus or tunnel tenderness", "**Paired cultures** from catheter and periphery before antibiotics", "Systemic antibiotics; remove or salvage by organism and stability"],
      ["Central venous stenosis", "Arm, face, or breast swelling; chest-wall collaterals; high venous pressures; prolonged bleeding after dialysis", "**Venography** — duplex is unreliable for the central veins", "**Balloon angioplasty**; stent for recoil or early recurrence"],
      ["Insertion injury", "Pneumothorax, hemothorax, air embolism, hematoma, arrhythmia from the wire, or malposition", "Chest film and clinical assessment after placement", "Treat the specific injury; reposition a malpositioned tip"],
    ],
  }, PACKET),
  sourced({
    id: "block-hdc-crbsi-flow",
    type: "flow",
    heading: "Catheter bloodstream infection",
    nodes: [
      { id: "suspect", label: "Fever or rigors in a patient dialyzing through a catheter" },
      { id: "cultures", label: "Paired catheter and peripheral blood cultures, then empiric antibiotics" },
      { id: "remove", label: "Remove the catheter: S. aureus, Pseudomonas, Candida, tunnel infection, septic shock, or bacteremia beyond 72 hours", tone: "caution" },
      { id: "salvage", label: "Attempt salvage: stable, uncomplicated, low-virulence organism — systemic antibiotics with an antibiotic lock", tone: "good" },
      { id: "reassess", label: "Reassess at 48 to 72 hours" },
      { id: "keep", label: "Clearing — complete the course and keep the catheter", tone: "good" },
      { id: "exchange", label: "Still bacteremic — remove the catheter, or exchange it over a guidewire in selected uncomplicated cases", tone: "caution" },
    ],
    edges: [
      { from: "suspect", to: "cultures" },
      { from: "cultures", to: "remove", label: "high-risk organism or unstable" },
      { from: "cultures", to: "salvage", label: "low risk" },
      { from: "salvage", to: "reassess" },
      { from: "reassess", to: "keep", label: "improving" },
      { from: "reassess", to: "exchange", label: "persistent" },
    ],
  }, PACKET),
  sourced({
    id: "block-hdc-crbsi-facts",
    type: "bullets",
    heading: "↳ Infection facts",
    items: [
      "Gram-positive organisms cause about **64%** of catheter bloodstream infections; **coagulase-negative staphylococci** lead at about 32%, then Staphylococcus aureus.",
      "A catheter exit-site infection is local erythema or pus; a **tunnel infection** is tenderness along the track and forces removal.",
      "**Taurolidine-heparin** lock (DefenCath) is FDA-approved to reduce catheter bloodstream infection in adults on chronic hemodialysis through a central catheter.",
    ],
  }, PACKET),
  sourced({
    id: "block-hdc-stenosis",
    type: "bullets",
    heading: "Central venous stenosis",
    items: [
      "Risk factors: a current or prior **subclavian** catheter, a left-sided catheter, several prior catheters, long dwell, and pacemaker or defibrillator leads.",
      "Classic picture: tender ipsilateral **arm, face, or breast swelling**, dilated collaterals over the shoulder and chest wall, rising **venous pressures** on the circuit, and **prolonged bleeding** from needle sites after dialysis.",
      "Disease at the SVC adds facial swelling and dyspnea — **SVC syndrome**.",
      "**Duplex ultrasound** misses central thoracic stenosis. **Catheter venography** is diagnostic and therapeutic; CT venography is the noninvasive alternative.",
      "Treat with **balloon angioplasty**, stenting for elastic recoil or early recurrence; restenosis is common and repeat intervention is the rule.",
    ],
  }, PACKET),
  sourced({
    id: "block-hdc-aeiou",
    type: "bullets",
    heading: "Emergent dialysis — AEIOU",
    items: [
      "**Acidosis**: severe metabolic acidosis refractory to medical therapy, classically pH below 7.1 to 7.15 or bicarbonate below 12 mEq/L.",
      "**Electrolytes**: refractory **hyperkalemia**, above 6.0 to 6.5 mEq/L or with ECG changes.",
      "**Intoxications**: dialyzable toxins — methanol, ethylene glycol, lithium, salicylates, and metformin-associated lactic acidosis.",
      "**Overload**: diuretic-refractory volume overload or pulmonary edema.",
      "**Uremia**: encephalopathy, **uremic pericarditis** (an absolute indication), uremic bleeding, or intractable nausea.",
    ],
  }, PACKET),
  sourcedUnits({
    id: "block-hdc-transition",
    type: "bullets",
    heading: "Getting off the catheter",
    items: [
      "Refer for dialysis modality education at an **eGFR under 30** (stage 4), earlier when GFR falls faster than 10 mL/min a year.",
      "Plan permanent AV access once creatinine clearance falls **below 25 mL/min**, and build an autogenous fistula **as soon as possible** so it has time to mature.",
      "Place a **prosthetic graft** only 3 to 6 weeks before dialysis is expected to start; it can be cannulated as early as **2 weeks**.",
      "An autogenous fistula should be ready for cannulation by **12 weeks**.",
      "More than **40%** of new fistulas need an assisting procedure to mature, and one that cannot be used by **3 months** despite intervention has failed to mature.",
    ],
  }, [[PACKET], [SCORE], [SCORE], [SCORE], [PACKET]]),
  sourced({
    id: "block-hdc-salvage",
    type: "bullets",
    heading: "When the upper-body veins are exhausted",
    items: [
      "**Translumbar IVC catheter** — direct puncture of the infrarenal IVC, the preferred route below the diaphragm, with high technical success and durable patency.",
      "**Transhepatic** catheter — the last resort when both the SVC and the IVC are occluded, with more thrombosis and infection and shorter patency.",
      "Specialized centers add transrenal and direct intra-atrial catheters, the **HeRO graft**, and thigh grafts or fistulas.",
    ],
  }, PACKET),
  sourcedUnits({
    id: "block-hdc-splits",
    type: "table",
    heading: "Board answer versus current practice",
    columns: ["Question", "Board answer", "Current practice"],
    rows: [
      ["How long can a nontunneled catheter stay?", "Internal jugular or subclavian **3 weeks**; femoral **5 days**", "Internal jugular **under 2 weeks**, or per facility policy, with early conversion to a tunneled catheter"],
      ["How long can a tunneled catheter stay?", "About **1 year**", "**No fixed maximum** — reassess the need regularly and convert to AV access"],
      ["When is a fistula mature?", "**Rule of 6s** at 6 weeks: 6 mm diameter, 6 cm straight length, under 6 mm deep, flow over 600 mL/min", "Too strict as a hard rule: **flow and depth** predict maturation as well as all the rules together, and diameter is the weakest predictor"],
      ["How long before a fistula is used?", "Wait **6 weeks**", "Ready by **12 weeks** in the SCORE module"],
      ["How long before a graft is used?", "Wait **6 weeks** for the tunnel to scar in", "Cannulation as early as **2 weeks**"],
      ["First treatment for central venous stenosis", "**Stent** the stenotic site", "**Balloon angioplasty** first; stent for elastic recoil or early recurrence"],
    ],
  }, [[FISER, KDOQI], [FISER, PACKET], [FISER, HAKIM], [FISER, SCORE], [FISER, SCORE], [FISER, PACKET]]),
  sourcedUnits({
    id: "block-hdc-pearls",
    type: "bullets",
    heading: "Board pearls",
    items: [
      "First site for a dialysis catheter: the **right internal jugular** — the straight shot to the right atrium.",
      "Future dialysis possible: avoid the **subclavian vein**. In the general ICU it is the lowest-infection site; the avoidance is dialysis-specific.",
      "Never put a catheter on the side of a **planned fistula** or graft.",
      "Arm swelling, chest-wall collaterals, high venous pressures, and prolonged needle-site bleeding: **central venous stenosis**. Venography, then angioplasty.",
      "Injects but won't aspirate: **fibrin sheath**. Alteplase lock, then sheath disruption, then exchange over a wire.",
      "Catheter infection with **S. aureus**, Pseudomonas, or Candida, a tunnel infection, septic shock, or bacteremia beyond 72 hours: the catheter comes out.",
      "A needle in an artery: pull it and hold pressure. **Never dilate**.",
      "Despite every guideline preferring a fistula, about **82%** of US patients still start hemodialysis on a catheter.",
    ],
  }, [[PACKET, FISER], [PACKET], [FISER], [PACKET], [PACKET], [PACKET], [PACKET], [PACKET]]),
  references("block-hdc-references", [PACKET, SCORE, FISER, KDOQI, HAKIM]),
];

export const hemodialysisAccessCatheterTopic = buildTopic({
  id: "00000000-0000-4000-8000-000000002420",
  versionId: "00000000-0000-4000-8000-000000002421",
  slug: "hemodialysis-access-catheter",
  title: "Hemodialysis Access Catheter",
  aliases: ["hemodialysis catheter", "dialysis catheter", "tunneled dialysis catheter", "tunneled cuffed catheter", "nontunneled dialysis catheter", "temporary dialysis catheter", "Quinton catheter", "Vas-Cath", "Permcath", "Permacath", "Tesio catheter", "Palindrome catheter", "HD catheter", "TDC", "central venous stenosis", "fibrin sheath", "catheter-related bloodstream infection", "CRBSI", "catheter lock", "taurolidine", "DefenCath", "translumbar catheter", "transhepatic catheter", "Rule of 6s", "rule of sixes", "AEIOU", "KDOQI"],
  scoreNodeId: "vascular-access-conditions",
  scoreCategory: "SCORE · Vascular Access · Diseases & Conditions",
  tags: ["vascular-access", "dialysis-access", "esrd", "absite", "score"],
  sourceId: PACKET,
  additionalSourceIds: [SCORE, FISER, KDOQI, HAKIM],
  blocks,
  reviewedAt: "2026-10-10T00:00:00.000Z",
});
