import { buildTopic, references, sourced } from "@/content/authoring";
import {
  FISER_PEDIATRIC_SOURCE as FISER,
  MALROTATION_PACKET_SOURCE as PACKET,
  SCORE_MALROTATION_OPERATION_SOURCE as SCORE_OP,
  SCORE_MALROTATION_SOURCE as SCORE,
} from "@/content/sources";
import type { TopicBlock } from "@/lib/types";

const blocks: TopicBlock[] = [
  sourced({
    id: "block-malrotation-summary",
    type: "summary",
    heading: "At a glance",
    text: "Malrotation is not really a disease of position — it is a disease of **mesenteric width**. The midgut normally rotates **270 degrees counterclockwise** around the superior mesenteric artery and then fixes to the retroperitoneum at two widely separated points, the duodenojejunal flexure in the left upper quadrant and the cecum in the right lower, and the broad diagonal base between them is what makes the midgut impossible to twist. When rotation arrests, those two points end up close together, the base narrows to a stalk, and the entire midgut hangs from a pedicle it can rotate around. That is why the anatomy matters far less than the width, why an incidental rotational anomaly with a broad base is a genuinely debatable indication, and why **bilious emesis in a neonate is treated as a vascular emergency**: the twist occludes the superior mesenteric artery and vein together, and the whole midgut can be dead in hours.",
  }, SCORE),
  sourced({
    id: "block-malrotation-embryology",
    type: "bullets",
    heading: "Normal rotation, and where it fails",
    items: [
      "The **midgut** runs from the distal duodenum to the proximal two thirds of the transverse colon, supplied by the **superior mesenteric artery** and drained by the **superior mesenteric vein** into the portal system.",
      "Around **eight weeks** of gestation the rapidly growing intestine herniates out of the abdomen and rotates **90 degrees counterclockwise** around the superior mesenteric artery.",
      "By **ten to eleven weeks** the abdominal cavity has grown enough to take the bowel back, and the midgut completes a further **180 degrees counterclockwise**, for 270 degrees in total.",
      "The bowel fixes to the retroperitoneum as it returns, leaving a **broad mesenteric base** running diagonally from the **ligament of Treitz** in the left upper quadrant to the ileocecal valve in the right lower quadrant.",
      "In malrotation the final 180 degrees never completes before fixation, so the duodenojejunal flexure and the cecum come to rest close together and the mesenteric base is a **narrow stalk** instead of a broad diagonal.",
      "**Ladd bands** are the second consequence: peritoneal bands running from the malpositioned cecum across the **third part of the duodenum** to the right retroperitoneum, obstructing the duodenum from outside without any twist at all.",
    ],
  }, SCORE),
  sourced({
    id: "block-malrotation-why",
    type: "prose",
    heading: "Why the pedicle is the whole disease",
    text: "A narrow pedicle turns the midgut into a mass suspended from a single axis, and a mass on an axis rotates. The twist is typically **clockwise**, and because the artery and its vein sit together in that stalk, one rotation occludes inflow and outflow at once. **Venous congestion comes first** and is what makes the bowel dusky and boggy before it is frankly dead, then arterial compromise follows and the whole midgut infarcts. Nothing in this sequence is slow. It is also why the operation is not an anatomic restoration: no one can rebuild a 270-degree rotation, so the **Ladd procedure** instead widens the base as far as it will go and leaves the bowel in **nonrotation**, which is a configuration too broad to twist even though it looks wrong. Duodenal obstruction in malrotation is most often the bands rather than the twist, with volvulus next and internal herniation least common — but the bands cause vomiting and the twist causes death, so the workup is driven entirely by the less common problem.",
  }, PACKET),
  sourced({
    id: "block-malrotation-epidemiology",
    type: "bullets",
    heading: "Epidemiology and the associations worth reflexive suspicion",
    items: [
      "Symptomatic malrotation occurs in roughly **1 in 6,000 live births**, while anatomic rotational variants are present in up to about **1 percent** of the population.",
      "Roughly **30 percent** of cases present by one month, **60 percent** by one year, and **75 percent** by five years of age.",
      "Abdominal wall defects — **gastroschisis** and **omphalocele** — carry a rotational anomaly in essentially every case, because the bowel that never sat in the abdomen never rotated or fixed inside it.",
      "**Congenital diaphragmatic hernia** carries the same assumption for the same reason, and the bowel should be run for rotational anomalies at the time of repair.",
      "**Heterotaxy** and situs anomalies with major congenital cardiac disease form a separate management problem, where mortality is driven by the heart rather than the bowel and prophylactic correction is contested.",
      "**Prune belly syndrome**, duodenal atresia, and intestinal atresia round out the list of anomalies that should prompt a deliberate look at rotation.",
    ],
  }, SCORE),
  sourced({
    id: "block-malrotation-bilious",
    type: "warning",
    heading: "Bilious emesis in a neonate is midgut volvulus until proven otherwise",
    text: "This is the single reflex the topic exists to install. Bile below the pylorus means the obstruction is **postpyloric**, and in a neonate the postpyloric obstruction that kills within hours is a midgut volvulus. Between **60 and 80 percent** of infants with bilious vomiting turn out not to have volvulus, and that statistic is not reassurance — it is the reason the workup has to be fast rather than selective, because the minority who do have it lose the entire midgut while someone waits for a more convincing story. **Hemodynamic stability does not lower the priority**; an infant can be well perfused with a twisted mesentery and decompensate abruptly. Volvulus can also present without bilious vomiting at all, so an acutely ill infant with vague abdominal findings or unexplained lethargy still deserves the question. The corollary runs the other way too: **a normal abdominal radiograph excludes nothing**, and treating one as reassurance is how the diagnosis gets missed.",
  }, SCORE_OP),
  sourced({
    id: "block-malrotation-presentation",
    type: "table",
    heading: "How it presents, by age",
    columns: ["Age group", "Typical picture", "What it means"],
    rows: [
      ["Neonate and infant", "**Bilious emesis**, feeding intolerance, abdominal distention", "The classic presentation, and the one that goes straight down the emergency pathway"],
      ["Infant with established ischemia", "**Hematochezia**, peritonitis, hypovolemic or septic shock", "Bleeding signals evolving necrosis and shock signals perforation or bacterial translocation — the window is closing"],
      ["Older child and adolescent", "Intermittent crampy pain, cyclic vomiting that may or may not be bilious, food intolerance", "Partial or recurrent obstruction from Ladd bands or intermittent twisting, insidious rather than dramatic"],
      ["Older child with chronic obstruction", "**Failure to thrive** and malabsorption", "Long-standing partial obstruction, often mislabelled as a functional disorder for years"],
      ["Adult", "Incidental rotational anomaly on cross-sectional imaging ordered for something else", "Increasingly common, and the counselling problem rather than the emergency"],
    ],
  }, SCORE),
  sourced({
    id: "block-malrotation-workup",
    type: "flow",
    heading: "Working up suspected malrotation",
    nodes: [
      { id: "suspect", label: "Infant with bilious emesis or otherwise suspected malrotation" },
      { id: "unstable", label: "Peritonitis, hemodynamic instability, or pneumoperitoneum", tone: "caution" },
      { id: "straight", label: "Resuscitate, decompress, give antibiotics, and go to laparotomy without imaging", tone: "caution" },
      { id: "stable", label: "Hemodynamically stable with a benign abdomen" },
      { id: "film", label: "Two-view abdominal radiographs, looking for free air" },
      { id: "study", label: "Doppler ultrasound or upper GI contrast series" },
      { id: "volvulus", label: "Whirlpool sign, corkscrew, or bird's beak", tone: "caution" },
      { id: "malroOnly", label: "Rotational anomaly without a twist" },
      { id: "normal", label: "Duodenum crosses the midline and the mesenteric anatomy is normal", tone: "good" },
      { id: "emergent", label: "Emergent Ladd procedure", tone: "caution" },
      { id: "elective", label: "Ladd procedure on an urgent but planned basis", tone: "good" },
      { id: "elsewhere", label: "Look for another cause of the bilious emesis", tone: "good" },
    ],
    edges: [
      { from: "suspect", to: "unstable", label: "unstable or peritonitic" },
      { from: "suspect", to: "stable", label: "stable" },
      { from: "unstable", to: "straight" },
      { from: "straight", to: "emergent" },
      { from: "stable", to: "film" },
      { from: "film", to: "straight", label: "free air" },
      { from: "film", to: "study", label: "no free air" },
      { from: "study", to: "volvulus", label: "twist demonstrated" },
      { from: "study", to: "malroOnly", label: "malposition without a twist" },
      { from: "study", to: "normal", label: "normal study" },
      { from: "volvulus", to: "emergent" },
      { from: "malroOnly", to: "elective" },
      { from: "normal", to: "elsewhere" },
    ],
  }, SCORE),
  sourced({
    id: "block-malrotation-imaging",
    type: "table",
    heading: "What each study shows",
    columns: ["Study", "Findings that support the diagnosis", "Limits"],
    rows: [
      ["Two-view abdominal radiograph", "**Double bubble** with distal gas, a gasless abdomen, or free air mandating immediate operation", "Cannot exclude either malrotation or volvulus, so a normal film changes nothing"],
      ["Upper GI contrast series", "Duodenojejunal junction **failing to cross the midline** and sitting low and rightward, with a **corkscrew** or a **bird's beak** once the midgut has twisted", "Requires a stable infant and contrast reaching the stomach, and is **93 to 100 percent** sensitive rather than perfect"],
      ["Doppler ultrasound", "**Whirlpool sign** of mesentery and vein spiralling around the artery, an **intraperitoneal course of the third part of the duodenum**, and the superior mesenteric vein lying left of or in front of the artery", "Operator dependent and not available at every centre around the clock"],
      ["CT or MRI", "Picks up rotational anomalies incidentally in older children and adults", "**No place in the acute neonatal workup**, where the only thing it reliably buys is delay"],
    ],
  }, PACKET),
  sourced({
    id: "block-malrotation-imaging-conflict",
    type: "prose",
    heading: "Board answer versus current practice: which study comes first",
    text: "The keyed answer is still that the **upper GI contrast series is the gold standard** for malrotation, and on an exam that is the answer to give. Practice has moved, and the reason is that ultrasound has been measured properly rather than assumed. Doppler ultrasound now reports sensitivity and specificity around **93 to 97 percent** and **96 to 100 percent** for the rotational anomaly, and around **97 percent** and **98 to 99 percent** for volvulus, with whirlpool-sign accuracy reported up to **99 percent** and the intraperitoneal position of the third part of the duodenum around **98 percent**. Proximal duodenal diameter is also larger when the midgut has twisted, with a reported median of **13 millimetres against 6**. Many centres therefore lead with ultrasound and reserve the contrast study for equivocal or non-diagnostic scans, which is faster, needs no contrast or ionizing radiation, and can be done at the bedside on an infant too sick to travel. What has not changed is that neither study is used to talk anyone out of operating: **an unstable or peritonitic infant goes to the operating room without imaging of any kind**.",
  }, PACKET),
  sourced({
    id: "block-malrotation-variants",
    type: "table",
    heading: "Rotational variants, and what each means for the mesentery",
    columns: ["Variant", "Anatomy", "Volvulus risk and operative implication"],
    rows: [
      ["Nonrotation", "Small bowel lies entirely to the right and colon entirely to the left, with a broad mesenteric base", "**Low risk**, because the base is wide — and this is precisely the configuration a Ladd procedure deliberately creates"],
      ["Incomplete or mixed rotation", "Duodenojejunal flexure and cecum both malpositioned and lying close together", "The commonest symptomatic pattern and the **highest risk**, since the pedicle is narrow"],
      ["Incomplete rotation with a broad mesentery", "Duodenojejunal flexure abnormally placed but the base still wide", "Low risk, and the one situation where the benefit of correction is genuinely contested"],
      ["Reverse rotation", "Midgut rotates **clockwise** instead, leaving the transverse colon behind the superior mesenteric artery", "Rare, and it obstructs the colon rather than threatening the entire midgut"],
    ],
  }, PACKET),
  sourced({
    id: "block-malrotation-preop",
    type: "bullets",
    heading: "Preoperative management",
    items: [
      "Establish large-bore access and give isotonic crystalloid in **10 to 20 mL/kg** boluses, because third-space losses into obstructed and congested bowel are larger than the abdomen looks.",
      "Decompress with an **orogastric or nasogastric tube**, which relieves distention and reduces the risk of aspiration on induction.",
      "Give **broad-spectrum intravenous antibiotics** covering gram-negatives, gram-positives, and anaerobes before incision, since translocation across ischemic bowel has usually already begun.",
      "Send a type and crossmatch, a blood gas, and a **lactate**, and correct acidosis as resuscitation proceeds.",
      "Resuscitate aggressively and concurrently, but **never let resuscitation postpone the operation** when volvulus is suspected — the definitive treatment for the shock is untwisting the bowel.",
    ],
  }, PACKET),
  sourced({
    id: "block-malrotation-indications",
    type: "bullets",
    heading: "Who gets an operation",
    items: [
      "Every confirmed **midgut volvulus** is an emergency operation, without exception and without further imaging.",
      "**Symptomatic malrotation** is an operative diagnosis, with the caveat that symptoms unrelated to the rotational anomaly will not resolve just because it was corrected.",
      "**Incidentally discovered malrotation in a child** is generally corrected, because the lifetime risk of a catastrophic volvulus is carried over decades and the operation is well tolerated.",
      "Patients **under 18** are strongly urged toward a Ladd procedure once an anomaly is found.",
      "**Adults** with an incidental anomaly are more often left to an informed decision, since the risk of volvulus has already fallen substantially by that age.",
      "Incomplete rotation with a demonstrably **broad mesenteric base** is the honest grey zone, where the pedicle that would have to twist is not narrow in the first place.",
    ],
  }, SCORE_OP),
  sourced({
    id: "block-malrotation-outcomes",
    type: "table",
    heading: "Outcome numbers",
    columns: ["Measure", "Figure", "Qualifier"],
    rows: [
      ["Symptom resolution after uncomplicated correction", "More than **80 percent**", "Symptoms never caused by the rotational anomaly do not resolve with it"],
      ["Overall mortality after operation", "**1 to 9 percent** across reported series", "Attributable mostly to delayed diagnosis rather than to the procedure"],
      ["Mortality with prompt correction and no ischemia", "**Approaching zero**", "In an otherwise healthy child without associated anomalies"],
      ["Mortality when more than 75 percent of bowel is necrotic", "Greater than **65 percent**", "The figure that makes bilious emesis in a neonate an emergency"],
      ["Recurrent volvulus", "Under **2 percent** overall", "Rises when the mesenteric base was not widened adequately"],
      ["Adhesive small bowel obstruction", "**4 to 5 percent**", "The extent of ischemia at the index operation independently predicts it"],
      ["Historical mortality of acute midgut volvulus", "Around **28 percent**", "A figure from delayed and already-ischemic presentations, not from timely correction"],
    ],
  }, SCORE_OP),
  sourced({
    id: "block-malrotation-age-conflict",
    type: "prose",
    heading: "Where the sources disagree on age at presentation",
    text: "Two figures circulate and they are not reconcilable, so it is worth knowing which is which. **Fiser** gives 75 percent presenting in the first month and 90 percent by one year. The **SCORE module** gives roughly 30 percent by one month, 60 percent by one year, and 75 percent by five years. The difference is almost certainly what each is counting: the higher numbers describe **symptomatic neonatal malrotation**, the population a pediatric surgeon is called about, while the lower ones describe **all diagnosed rotational anomalies** including the older children who present with chronic intermittent symptoms and the incidental findings that modern cross-sectional imaging keeps producing. The clinically useful version survives either way — this is overwhelmingly a disease of the first year of life, and the first month is the densest part of it. If a question forces a single set, answer the one that matches the framing: a neonatal vignette wants the high first-month figure, a question about the diagnosed population wants the SCORE distribution.",
  }, FISER),
  sourced({
    id: "block-malrotation-followup",
    type: "bullets",
    heading: "After correction: what goes wrong and how to tell",
    items: [
      "Bilious vomiting and distention returning after a Ladd procedure is **early adhesive obstruction until proven otherwise**, which is commoner than recurrent volvulus but cannot be distinguished from it on the story alone.",
      "Obtain plain films, decompress, and resuscitate — and **re-explore urgently** rather than persisting with conservative management if recurrent volvulus is a live possibility, because the cost of being wrong is the whole midgut.",
      "Recurrent volvulus points back to an **inadequately widened mesenteric base**, which is the step in the index operation that prevents it.",
      "Adhesive obstruction correlates with the extent of ischemia at the index operation, and **adhesion barriers** appear to reduce rehospitalization without increasing recurrent volvulus.",
      "Midgut volvulus is a leading cause of **short bowel syndrome** in infants, bringing parenteral nutrition dependence, intestinal failure-associated liver disease, and central line-associated bloodstream infection with it.",
      "Short bowel is managed by bowel rehabilitation first, then autologous lengthening by the **serial transverse enteroplasty** or **Bianchi** technique, with intestinal transplantation reserved for failure of both.",
    ],
  }, SCORE_OP),
  sourced({
    id: "block-malrotation-pearls",
    type: "bullets",
    heading: "Board pearls",
    items: [
      "**Malrotation is the leading cause of duodenal obstruction beyond the first week of life**; duodenal atresia leads within that first week.",
      "**Bilious vomiting in a neonate** means an emergent study for malrotation, and an unstable or peritonitic infant skips the study and goes to the operating room.",
      "**Corkscrew** or **bird's beak** on an upper GI series and a **whirlpool sign** on Doppler ultrasound all mean the midgut has twisted.",
      "A superior mesenteric vein lying **to the left of or in front of** the artery should prompt the thought of a rotational anomaly.",
      "**Gastroschisis, omphalocele, and congenital diaphragmatic hernia** should each be assumed to carry a rotational anomaly.",
      "Detorsion is **counterclockwise**, and appendectomy is performed because the cecum finishes on the left where a future appendicitis would confuse everyone.",
      "More than **75 percent midgut necrosis** carries a mortality above 65 percent, which is the argument for a planned second look at 24 to 48 hours rather than a massive one-stage resection.",
    ],
  }, FISER),
  references("block-malrotation-references", [SCORE, SCORE_OP, FISER, PACKET]),
];

export const malrotationTopic = buildTopic({
  id: "00000000-0000-4000-8000-000000001104",
  versionId: "00000000-0000-4000-8000-000000001114",
  slug: "malrotation",
  title: "Malrotation",
  aliases: ["malrotation", "intestinal malrotation", "midgut volvulus", "volvulus", "IRA", "intestinal rotational abnormality", "rotational anomaly", "Ladd bands", "bilious emesis", "bilious vomiting", "corkscrew sign", "bird's beak", "whirlpool sign", "nonrotation", "reverse rotation", "narrow mesenteric base", "SMA SMV inversion", "duodenojejunal junction", "ligament of Treitz", "neonatal bowel obstruction", "short bowel syndrome", "heterotaxy", "double bubble"],
  scoreNodeId: "pediatric-conditions",
  scoreCategory: "SCORE · Pediatric Surgery · Diseases & Conditions",
  tags: ["pediatric-surgery", "malrotation", "volvulus", "neonatal", "emergency", "absite", "score"],
  sourceId: SCORE,
  additionalSourceIds: [SCORE_OP, FISER, PACKET],
  blocks,
  reviewedAt: "2026-08-17T00:00:00.000Z",
});
