import { buildTopic, references, sourced } from "@/content/authoring";
import {
  FISER_PEDIATRIC_SOURCE as FISER,
  MALROTATION_PACKET_SOURCE as PACKET,
  SCORE_MALROTATION_OPERATION_SOURCE as SCORE_OP,
  SCORE_MALROTATION_SOURCE as SCORE,
} from "@/content/sources";
import type { TopicBlock } from "@/lib/types";

const blocks: TopicBlock[] = [
  sourced({
    id: "block-ladd-summary",
    type: "summary",
    heading: "At a glance",
    text: "The Ladd procedure does not restore normal anatomy and was never meant to. Nobody can reproduce a 270-degree embryologic rotation, so the operation instead takes the one thing that makes the midgut dangerous — **a narrow mesenteric pedicle** — and makes it as wide as it will go, then parks the bowel in **nonrotation** with the small intestine on the right and the colon on the left. Every step serves that end: detorsion restores flow, dividing the Ladd bands frees the duodenum, straightening the duodenum down the right gutter moves one end of the base as far right as possible, and scoring the mesentery between the vessels moves the other as far left. Appendectomy is housekeeping for a cecum that now sits on the wrong side. In an emergency the operation has a second job layered on top, which is deciding how much bowel is dead — and the discipline there is to **resect as little as possible** and come back in a day, because the alternative to a second look is a child with short bowel syndrome.",
  }, SCORE_OP),
  sourced({
    id: "block-ladd-indications",
    type: "bullets",
    heading: "Indications, and the one real controversy",
    items: [
      "Confirmed **midgut volvulus is an emergency laparotomy**, whatever the hemodynamics look like at the moment of the decision.",
      "**Bilious emesis in an infant is treated as volvulus** until an adequate study says otherwise, so it drives the same urgency until it is disproved.",
      "**Symptomatic malrotation** is an operative diagnosis, although symptoms that were never caused by the anomaly will persist afterwards and this should be said out loud beforehand.",
      "Patients **under 18** with an incidentally discovered rotational anomaly are strongly urged toward correction, because the lifetime risk of catastrophic volvulus is still largely ahead of them.",
      "**Adults** with an incidental anomaly are usually offered an informed choice instead, since the risk of volvulus falls substantially with age and the operation carries real morbidity.",
      "**Asymptomatic heterotaxy** is the genuine controversy: volvulus incidence is low, perioperative mortality is high and driven by the cardiac disease, and prophylactic correction has never clearly shown benefit.",
    ],
  }, SCORE_OP),
  sourced({
    id: "block-ladd-approach",
    type: "flow",
    heading: "Choosing the approach",
    nodes: [
      { id: "present", label: "Patient with a confirmed or strongly suspected rotational anomaly" },
      { id: "acute", label: "Volvulus, peritonitis, instability, or suspected ischemia", tone: "caution" },
      { id: "elective", label: "Stable, no ischemia, operating on a planned basis" },
      { id: "assess", label: "Can every tenet of the Ladd procedure be achieved laparoscopically" },
      { id: "lap", label: "Laparoscopic Ladd procedure", tone: "good" },
      { id: "convert", label: "Convert at a low threshold rather than accept an incomplete operation", tone: "caution" },
      { id: "open", label: "Open laparotomy", tone: "caution" },
    ],
    edges: [
      { from: "present", to: "acute", label: "emergent" },
      { from: "present", to: "elective", label: "elective" },
      { from: "acute", to: "open" },
      { from: "elective", to: "assess" },
      { from: "assess", to: "lap", label: "exposure adequate" },
      { from: "assess", to: "convert", label: "exposure inadequate or anatomy unclear" },
      { from: "convert", to: "open" },
    ],
  }, PACKET),
  sourced({
    id: "block-ladd-approach-table",
    type: "table",
    heading: "Open versus laparoscopic",
    columns: ["Dimension", "Open Ladd", "Laparoscopic Ladd"],
    rows: [
      ["Where it belongs", "**Volvulus, peritonitis**, instability, or any suspicion of necrotic bowel", "Stable elective correction, equivocal imaging, or the older child and young adult"],
      ["Exposure", "Permits rapid evisceration and inspection of the entire midgut in seconds", "Constrained, and the whole bowel is harder to run convincingly"],
      ["Operative time", "Longer in reported comparisons", "Shorter"],
      ["Return of feeds and length of stay", "Slower to feed and longer in hospital", "Faster to feed and out sooner"],
      ["Adhesive obstruction afterwards", "Around **10 percent** in comparative series", "Around **1 percent**"],
      ["Recurrent volvulus", "Low, and the historical standard against which the alternative is measured", "Higher in meta-analysis, with an odds ratio near **2.97**, though single-institution series now report parity"],
      ["Characteristic failure mode", "**Adhesive obstruction** from a large incision and a fully eviscerated midgut", "**An incomplete Ladd**, leaving a duodenal stricture or kink and a base never truly widened"],
    ],
  }, PACKET),
  sourced({
    id: "block-ladd-preop",
    type: "bullets",
    heading: "Preparation and setup",
    items: [
      "Resuscitate concurrently rather than sequentially — isotonic boluses, orogastric decompression with an **8 to 10 French** tube, type and crossmatch, blood gas and lactate, and broad-spectrum antibiotics before incision.",
      "Vasopressor support is used judiciously alongside volume, and none of it may be allowed to postpone the operation when volvulus is suspected.",
      "General endotracheal anesthesia with **rapid-sequence induction**, given a stomach that is obstructed and full.",
      "Confirm the orogastric tube and the urinary catheter after induction, since both drive intraoperative decisions.",
      "Defend **normothermia** aggressively with a warming blanket, a raised ambient theatre temperature, and warmed intravenous fluids and irrigation, because a neonate loses heat faster than anything else on the table.",
      "Position supine and prepare circumferentially from the **nipple line to the mid-thighs**, so the incision can be extended or a stoma brought out without repositioning.",
    ],
  }, PACKET),
  sourced({
    id: "block-ladd-steps",
    type: "sequence",
    heading: "The Ladd procedure, open",
    steps: [
      { title: "Incision and exposure", detail: "A **transverse supraumbilical incision** in the right upper quadrant, or an upper midline, entering under direct vision; evacuate and culture the peritoneal fluid, noting whether it is serous, bilious, or bloody." },
      { title: "Evisceration and detorsion", detail: "Deliver the bowel to expose the mesenteric root and **untwist counterclockwise** — turning back the hands of time — often through **two or three full rotations**, until the mesenteric vessels lie flat and unkinked." },
      { title: "Division of the Ladd bands", detail: "Retract the cecum **inferiorly and to the left** to put the bands on tension, then divide them sharply or with cautery close to the parietal attachments, keeping away from the duodenum, the superior mesenteric vessels, and the biliary structures." },
      { title: "Straightening the duodenum", detail: "Mobilize the entire **duodenal C-loop** until it runs straight down the **right paracolic gutter**, which moves one end of the mesenteric base as far to the right as it will go." },
      { title: "Widening the mesenteric base", detail: "Fan the mesentery out and score the anterior peritoneal leaflet between the vessels, separating duodenum from cecum as widely as possible; **this is the step that prevents recurrence** and the step most often done inadequately." },
      { title: "Appendectomy", detail: "Ligate the mesoappendix and amputate the base, because the cecum now lies on the left and a future appendicitis would be diagnosed late by anyone unfamiliar with the history; roughly **88 percent** of surgeons perform it, and omission is reasonable with necrosis, perforation, or very low birthweight." },
      { title: "Placement in nonrotation", detail: "Leave the small bowel and duodenum entirely in the right abdomen and the colon and cecum entirely in the left, **without routine cecopexy or duodenopexy**." },
      { title: "Closure", detail: "Warm saline irrigation, hemostasis, and counts, then fascia closed with absorbable monofilament and a subcuticular skin closure — or a temporary closure with a planned return if viability is uncertain or the abdomen is too edematous to close safely." },
    ],
  }, PACKET),
  sourced({
    id: "block-ladd-laparoscopic",
    type: "bullets",
    heading: "Laparoscopic modifications",
    items: [
      "**Open Hasson** access at the umbilicus, insufflation to **8 to 12 mmHg**, a **30-degree** scope, and two lower-quadrant working ports.",
      "The tenets do not change: lyse the bands, mobilize the duodenum, widen the base, take the appendix, and leave the bowel in nonrotation.",
      "Running the whole small bowel to confirm there is no twist and no missed pathology is harder laparoscopically and is where an incomplete operation begins.",
      "**Convert early** rather than accept a compromised base — the reported recurrences and duodenal strictures track back to Ladd procedures that were never finished.",
    ],
  }, PACKET),
  sourced({
    id: "block-ladd-cecopexy",
    type: "prose",
    heading: "Board answer versus current practice: cecopexy",
    text: "Fiser writes the operation as detorsion, band division, placing the cecum in the left lower quadrant as a cecopexy, placing the duodenum in the right upper quadrant, and appendectomy — and on an exam, describing the finished anatomy as **cecum left and duodenum right** is the answer. What has fallen away is the fixation. **Routine cecopexy and duodenopexy are not part** of the contemporary Ladd procedure, because artificial fixation points recreate exactly what the operation exists to abolish: a narrow axis, and a potential space behind it for an **internal hernia**. The bowel is left unfixed in nonrotation, and **it is the width of the base, not a stitch**, that prevents the next twist. The nuance worth carrying is that selective cecopexy has been reported in redo operations and proposed as a way of reducing recurrence after laparoscopic repair, which is where the two supplied documents disagreed with each other — one recommended it, the other forbade it. Both are describing something real: it is not a routine step, and it is not never done. A related and much smaller discrepancy is whether the cecum ends in the left upper or left lower quadrant; sources say both, and the only testable fact is that the colon goes left.",
  }, FISER),
  sourced({
    id: "block-ladd-viability",
    type: "flow",
    heading: "Deciding what is dead",
    nodes: [
      { id: "detorsed", label: "Midgut detorsed and the mesenteric vessels lying flat" },
      { id: "warm", label: "Pack in warm moist laparotomy sponges for 10 to 15 minutes at 100 percent inspired oxygen" },
      { id: "reassess", label: "Reassess colour, peristalsis, and mesenteric arterial pulsation" },
      { id: "viable", label: "All three return", tone: "good" },
      { id: "frank", label: "Frank gangrene or perforation", tone: "caution" },
      { id: "equivocal", label: "Viability still uncertain, or ischemia is patchy and multifocal", tone: "caution" },
      { id: "complete", label: "Complete the Ladd procedure and close", tone: "good" },
      { id: "resect", label: "Resect only the clearly necrotic segments", tone: "caution" },
      { id: "second", label: "Leave equivocal bowel in continuity under a temporary closure and return at 24 to 48 hours", tone: "caution" },
      { id: "document", label: "Record the remaining bowel length in the operative note" },
    ],
    edges: [
      { from: "detorsed", to: "warm" },
      { from: "warm", to: "reassess" },
      { from: "reassess", to: "viable", label: "perfusion recovers" },
      { from: "reassess", to: "frank", label: "unequivocally dead" },
      { from: "reassess", to: "equivocal", label: "still in doubt" },
      { from: "viable", to: "complete" },
      { from: "frank", to: "resect" },
      { from: "equivocal", to: "second" },
      { from: "resect", to: "document" },
      { from: "second", to: "document" },
    ],
  }, PACKET),
  sourced({
    id: "block-ladd-viability-detail",
    type: "bullets",
    heading: "Judging viability at the table",
    items: [
      "**Colour, peristalsis, and palpable mesenteric arterial pulsation** are the three classical signs, and the absence of any one of them predicts non-viability.",
      "Doppler assessment of mesenteric flow and **fluorescein with a Wood lamp** are the traditional adjuncts.",
      "**Indocyanine green** fluorescence has largely displaced fluorescein where it is available, and is endorsed for emergency bowel-viability assessment.",
      "**None of the adjuncts overrides the discipline of waiting**: bowel that looks dead immediately after detorsion frequently recovers once it has been warm and perfused for a quarter of an hour.",
    ],
  }, PACKET),
  sourced({
    id: "block-ladd-second-look",
    type: "warning",
    heading: "Do not resect your way into short bowel syndrome",
    text: "The most consequential error in this operation is **a massive resection at the first sitting**. Bowel that has been twisted is congested rather than infarcted for a considerable window, and a surgeon deciding at the moment of maximum ischemic insult will systematically overestimate how much is dead. Massive resection converts a survivable emergency into **lifelong intestinal failure** — parenteral nutrition dependence, intestinal failure-associated liver disease, recurrent line sepsis, and a transplant conversation — while the alternative costs one more anesthetic. So resect only what is unequivocally gangrenous or perforated, leave everything equivocal in continuity, close the abdomen temporarily, and return at **24 to 48 hours** to decide with a day of reperfusion behind you. When more than **75 percent** of the midgut is necrotic the mortality exceeds **65 percent**, which is precisely why the remaining length must be measured and written in the operative note every time: the next team's decisions depend on a number nobody can reconstruct later.",
  }, PACKET),
  sourced({
    id: "block-ladd-postop",
    type: "bullets",
    heading: "Postoperative care",
    items: [
      "Continue **orogastric decompression** until the output falls and clears, then advance enteral feeds as bowel function returns.",
      "Correct electrolytes deliberately, since ongoing gastric losses and third-spacing continue well past the operation.",
      "Start **parenteral nutrition early** where extensive resection or a prolonged ileus is anticipated, rather than waiting for malnutrition to declare itself.",
      "Watch central lines closely in any child heading for short bowel, because line sepsis and parenteral nutrition-associated cholestasis are what actually threaten them over months.",
      "Recurrent bilious vomiting or distention after discharge means imaging and re-evaluation, not reassurance.",
    ],
  }, PACKET),
  sourced({
    id: "block-ladd-complications",
    type: "table",
    heading: "Complications",
    columns: ["Complication", "Frequency and drivers", "Management"],
    rows: [
      ["Adhesive small bowel obstruction", "**4 to 5 percent** overall, and the extent of ischemia at the index operation independently predicts it", "Hydration, bowel rest, and gastric decompression, with operation if medical management fails"],
      ["Recurrent volvulus", "Under **2 percent**, from a mesenteric base that was never widened enough, with operative age beyond **30 days** an independent risk factor after laparoscopic repair", "Urgent re-exploration, since the differential against adhesive obstruction cannot be settled clinically"],
      ["Duodenal stricture or kink", "A reoperation risk specific to an incomplete laparoscopic Ladd", "Re-operation to complete the mobilization properly"],
      ["Short bowel syndrome", "Follows extensive resection for necrosis, with midgut volvulus a leading infantile cause", "Bowel rehabilitation, then autologous lengthening by serial transverse enteroplasty or the Bianchi technique, with transplantation for failure"],
      ["Central line-associated bloodstream infection", "A consequence of prolonged parenteral nutrition rather than of the operation", "Line stewardship and prompt treatment, since it is a leading cause of late death"],
      ["Parenteral nutrition-associated liver disease", "Tracks duration of parenteral nutrition and absent enteral feeding", "Advance enteral feeds as tolerated and modify the lipid source"],
    ],
  }, SCORE_OP),
  sourced({
    id: "block-ladd-heterotaxy",
    type: "bullets",
    heading: "Heterotaxy is a different operation on a different patient",
    items: [
      "Rotational anomalies are **near-universal in heterotaxy**, and the cardiac disease rather than the bowel determines what happens to the child.",
      "Perioperative complications and mortality after a Ladd procedure are substantially higher in this group, driven by the underlying cardiac physiology.",
      "The incidence of volvulus in asymptomatic heterotaxy is **low**, which undercuts the usual prophylactic argument.",
      "Systematic review has **not established a benefit** for prophylactic correction over observation in asymptomatic heterotaxy, and management is best decided jointly with cardiology around the cardiac timeline.",
      "A symptomatic heterotaxy patient is a different question entirely and still needs an operation.",
    ],
  }, PACKET),
  sourced({
    id: "block-ladd-outcomes",
    type: "bullets",
    heading: "Outcomes",
    items: [
      "More than **80 percent** of infants have full resolution of symptoms after operative correction.",
      "Overall mortality runs from about **1 to 4.5 percent** in the operative literature and up to **9 percent** in series weighted toward delayed diagnosis.",
      "Mortality **approaches zero** in an otherwise healthy child diagnosed and corrected promptly without intestinal ischemia.",
      "Mortality exceeds **65 percent** once more than **75 percent** of the bowel is necrotic.",
      "The main causes of death after operation are **intestinal necrosis, nutritional complications, and central line-associated bloodstream infection**.",
      "Prematurity, associated congenital anomalies, perforation, and the presence of necrosis are the factors that move an individual patient's risk.",
    ],
  }, SCORE_OP),
  references("block-ladd-references", [SCORE_OP, PACKET, FISER, SCORE]),
];

export const malrotationOperationTopic = buildTopic({
  id: "00000000-0000-4000-8000-000000001105",
  versionId: "00000000-0000-4000-8000-000000001115",
  slug: "malrotation-operation",
  title: "Malrotation Operation",
  aliases: ["Ladd procedure", "Ladd's procedure", "Ladd operation", "malrotation operation", "malrotation repair", "volvulus operation", "midgut volvulus surgery", "detorsion", "Ladd bands", "laparoscopic Ladd", "cecopexy", "second look laparotomy", "bowel viability", "indocyanine green", "ICG", "mesenteric base widening", "nonrotation", "incidental appendectomy", "damage control", "short bowel syndrome", "heterotaxy", "neonatal laparotomy"],
  scoreNodeId: "pediatric-procedures",
  scoreCategory: "SCORE · Pediatric Surgery · Operations & Procedures",
  tags: ["pediatric-surgery", "malrotation", "volvulus", "operative-technique", "emergency", "absite", "score"],
  sourceId: SCORE_OP,
  additionalSourceIds: [PACKET, FISER, SCORE],
  blocks,
  reviewedAt: "2026-08-17T00:00:00.000Z",
});
