import { buildTopic, references, sourced, sourcedUnits } from "@/content/authoring";
import {
  ALLIANCE_A021501_SOURCE as A021501,
  COCHRANE_ANTECOLIC_2022_SOURCE as ANTECOLIC,
  FISER_PANCREAS_SOURCE as FISER,
  ISGPS_POPF_2016_SOURCE as ISGPS,
  NCCN_PANCREATIC_V4_2026_SOURCE as NCCN,
  NORPACT1_SOURCE as NORPACT,
  PANCREATICODUODENECTOMY_PACKET_SOURCE as PACKET,
  PREOPANC1_SOURCE as PREOPANC,
  PRESTON_PPH_2024_SOURCE as PRESTON,
  PRODIGE24_SOURCE as PRODIGE,
  SCORE_PANCREATICODUODENECTOMY_SOURCE as SCORE,
  WHIPPLE_OPERATIVE_PACKET_SOURCE as OPERATIVE,
} from "@/content/sources";
import type { TopicBlock } from "@/lib/types";

const blocks: TopicBlock[] = [
  sourced({
    id: "block-pd-summary",
    type: "summary",
    heading: "At a glance",
    text: "The **Whipple** removes the pancreatic head and uncinate, the duodenum, the distal bile duct, the gallbladder, and the proximal jejunum, with or without the distal stomach, then rebuilds with three anastomoses on one jejunal limb. It is the operation for resectable **pancreatic head and periampullary cancer**. At high-volume centers mortality is under 5%, but morbidity is not, and the exam lives in three places: **resectability** by degrees of vessel contact, the rule that a resectable head mass needs **no biopsy**, and the three complications the ISGPS defines — **pancreatic fistula**, **post-pancreatectomy hemorrhage**, and **delayed gastric emptying**. The step-by-step operation, with a pitfall for each step, is in the open pancreaticoduodenectomy playbook.",
  }, PACKET),
  sourced({
    id: "block-pd-definition",
    type: "bullets",
    heading: "What comes out, and why all of it has to",
    items: [
      "The en bloc specimen is the **pancreatic head and uncinate**, the **duodenum**, the **distal common bile duct**, the **gallbladder**, and the **proximal jejunum**. The classic **Kausch-Whipple** also takes the antrum or distal stomach.",
      "The anatomic reason: the head and duodenum share the **pancreaticoduodenal arcades** — superior branches from the **GDA**, inferior branches from the **SMA**. Shared blood supply means the head cannot come out without the duodenum.",
      "The physiologic cost: loss of duodenal **motilin** signaling contributes to delayed gastric emptying, loss of acinar mass to **exocrine insufficiency**, and loss of islet mass to new or worsened **diabetes**.",
      "Reconstruction follows the **Child** order on a single jejunal limb: pancreaticojejunostomy first, hepaticojejunostomy next, and the gastro- or duodenojejunostomy furthest downstream.",
      "**Volume matters.** Outcomes are best at centers performing at least **15 to 20** pancreatic resections a year, where operative mortality is **under 5%** — yet overall morbidity still runs **30% to 60%**.",
    ],
  }, PACKET),
  sourced({
    id: "block-pd-indications",
    type: "bullets",
    heading: "Indications",
    items: [
      "**Pancreatic ductal adenocarcinoma** of the head, neck, or uncinate — the classic indication and the usual board answer.",
      "The other three **periampullary cancers**: **ampullary carcinoma**, **distal cholangiocarcinoma**, and **duodenal adenocarcinoma**. Ampullary and duodenal primaries carry the best prognosis of the four.",
      "**Pancreatic neuroendocrine tumors** of the head that are **over 2 cm**, functional, or too close to the main duct for enucleation.",
      "**Main-duct IPMN** of the head, or a mucinous cystic neoplasm with high-risk or malignant features.",
      "Selected solitary metastases to the head, classically **renal cell carcinoma**.",
      "**Chronic pancreatitis** with a dominant inflammatory head mass, intractable pain, or a malignancy that cannot be excluded.",
      "Severe **duodenal polyposis**, such as familial adenomatous polyposis at **Spigelman stage IV**.",
      "**Trauma**: AAST grade IV or V pancreatic or duodenal injury involving the **ampulla** or main pancreatic duct — usually staged, with damage control and wide drainage first and reconstruction after resuscitation.",
    ],
  }, PACKET),
  sourced({
    id: "block-pd-contraindications",
    type: "bullets",
    heading: "↳ Who should not have one",
    items: [
      "**Distant metastases** — liver, peritoneal or omental implants, or **extraregional nodes** in the celiac, para-aortic, or aortocaval stations. A distant node is metastatic disease, whatever the local anatomy looks like.",
      "**Arterial encasement** of more than 180° of the SMA or celiac axis, or aortic invasion.",
      "**Unreconstructable** occlusion of the SMV or portal vein.",
      "Relative: severe cardiopulmonary disease, a performance status of **ECOG 2** or worse, or malnutrition that cannot be corrected.",
      "Contiguous spread into the transverse mesocolon, stomach, adrenal, or kidney is **not** a contraindication — those organs come out en bloc.",
    ],
  }, PACKET),
  sourced({
    id: "block-pd-presentation",
    type: "bullets",
    heading: "Presentation",
    items: [
      "**Painless obstructive jaundice** is the classic presentation of a head or periampullary mass.",
      "**Courvoisier sign** — a palpable, nontender gallbladder in a jaundiced patient — points to malignant distal biliary obstruction rather than stones.",
      "Weight loss, anorexia, **new-onset diabetes**, pale stools, dark urine, and pruritus fill out the picture.",
      "**Back pain** suggests retroperitoneal or perineural invasion and is a red flag for more advanced disease.",
      "Duodenal and ampullary lesions can present with **GI bleeding** or anemia; gastric outlet obstruction is a late feature.",
    ],
  }, OPERATIVE),
  sourced({
    id: "block-pd-workup",
    type: "bullets",
    heading: "Workup",
    items: [
      "**Pancreatic-protocol CT** is first-line: thin sections through the pancreas in more than one contrast phase, read for contact with the **SMA**, celiac axis, common hepatic artery, and **SMV and portal vein**. Stage the chest and pelvis too.",
      "**MRI and MRCP** solve problems — indeterminate liver lesions, tumors CT cannot see, inflammatory versus malignant strictures. The **double-duct sign**, dilation of both the bile duct and the main pancreatic duct, suggests periampullary malignancy.",
      "**Image before stenting.** A biliary stent degrades staging, so dedicated imaging comes first, ideally within **4 weeks** of surgery.",
      "**CA 19-9** is the serum marker, but read it only **after biliary decompression**, because cholestasis falsely raises it. The **5% to 10%** of patients who are Lewis antigen-negative make none at all.",
      "A CA 19-9 of **500 U/mL** or more marks biologically borderline disease and predicts occult metastasis.",
      "**Staging laparoscopy** is selective: borderline or locally advanced disease, a markedly elevated CA 19-9, a large tumor, or equivocal imaging, where occult metastases turn up in up to about **25%** of borderline cases.",
    ],
  }, PACKET),
  sourced({
    id: "block-pd-biopsy",
    type: "warning",
    tone: "pearl",
    heading: "The biopsy rule",
    text: "A classic **resectable** head mass — painless jaundice, weight loss, a double-duct sign — goes to resection **without a tissue diagnosis**, because it is coming out either way. Tissue becomes **mandatory** before neoadjuvant chemotherapy, palliative chemotherapy, or radiation. When it is needed, **EUS-guided** sampling is preferred over percutaneous biopsy to avoid seeding the tract.",
  }, PACKET),
  sourced({
    id: "block-pd-preparation",
    type: "bullets",
    heading: "↳ Preparing the patient",
    items: [
      "With high clinical suspicion of malignancy, an **indeterminate biopsy** does not stop the operation.",
      "Bilirubin must be normal or near normal — **under 4 to 5 mg/dL** — before systemic chemotherapy is safe. For upfront surgery the safe ceiling is debated, with proposed thresholds from 6 to 15 mg/dL.",
      "Judge nutrition by recent **weight loss**, not albumin or prealbumin, which track inflammation rather than nutritional state.",
      "Supplement with high-calorie, high-protein drinks, and start **pancreatic enzyme replacement** before surgery for steatorrhea or a low fecal elastase.",
      "Screen for **diabetes** and for pancreatic insufficiency, and counsel on both before the operation.",
    ],
  }, SCORE),
  sourced({
    id: "block-pd-drainage",
    type: "bullets",
    heading: "Preoperative biliary drainage",
    items: [
      "**Routine drainage is not recommended** before upfront resection. It raises infectious and wound complications without improving survival.",
      "In the landmark randomized trial of drainage against early surgery, serious complications occurred in **74%** after drainage and **39%** after early surgery.",
      "Drain selectively: **cholangitis**, severe pruritus, a very high bilirubin — the trial excluded patients above **14.6 mg/dL** — an expected delay to surgery, or **planned neoadjuvant therapy**.",
      "When drainage is indicated and malignancy is confirmed, a **self-expanding metal stent** beats plastic: longer patency and fewer reinterventions.",
    ],
  }, PACKET),
  sourced({
    id: "block-pd-resectability",
    type: "table",
    heading: "Resectability by vessel contact",
    columns: ["Status", "Arterial — SMA, celiac axis, common hepatic", "Venous — SMV and portal vein"],
    rows: [
      ["**Resectable**", "**No** arterial tumor contact", "No contact, or **180° or less** without contour irregularity"],
      ["**Borderline resectable**", "Head and uncinate: common hepatic contact **without** extension to the celiac axis or hepatic bifurcation, SMA contact of **180° or less**, or contact with variant arterial anatomy. Body and tail: celiac contact of 180° or less", "Contact **over 180°**, or 180° or less with contour irregularity or thrombosis, provided the vein can be reconstructed above and below; or contact with the **IVC**"],
      ["**Locally advanced**", "SMA or celiac contact **over 180°**, or celiac contact with aortic involvement", "**Unreconstructable** SMV or portal vein from tumor involvement or occlusion"],
    ],
  }, NCCN),
  sourced({
    id: "block-pd-vessels",
    type: "bullets",
    heading: "↳ Reading the vessels",
    items: [
      "**Abutment** is tumor contact with 180° or less of the vessel circumference; **encasement** is more than 180°.",
      "Resectability is a **multidisciplinary** decision made on pancreatic-protocol imaging.",
      "**Distant metastasis**, including non-regional nodes, makes disease unresectable regardless of the local picture.",
      "**Isolated venous involvement is not a contraindication.** Segmental SMV or portal vein resection with primary repair or an interposition graft is accepted when it achieves an R0 resection.",
      "**Arterial resection** remains high-morbidity and is reserved for selected patients at expert centers, usually after neoadjuvant therapy.",
    ],
  }, PACKET),
  sourced({
    id: "block-pd-vein-types",
    type: "table",
    heading: "↳ ISGPS venous resection types",
    columns: ["Type", "Resection", "Repair"],
    rows: [
      ["**Type 1**", "Partial side wall", "Primary closure, venorrhaphy"],
      ["**Type 2**", "Partial side wall", "**Patch**"],
      ["**Type 3**", "Segmental", "Primary **end-to-end** anastomosis"],
      ["**Type 4**", "Segmental", "**Interposition graft**"],
    ],
  }, OPERATIVE),
  sourcedUnits({
    id: "block-pd-neoadjuvant",
    type: "bullets",
    heading: "Neoadjuvant therapy: what is settled and what is not",
    items: [
      "**Borderline resectable** disease gets neoadjuvant therapy first — multiagent chemotherapy such as **FOLFIRINOX**, or gemcitabine with nab-paclitaxel, with or without radiation — after tissue confirmation, biliary decompression, and consideration of staging laparoscopy.",
      "**Resectable** disease still goes to upfront surgery by default. Neoadjuvant therapy is reasonable when high-risk features are present: a markedly elevated **CA 19-9**, a large primary, large regional nodes, excessive weight loss, or severe pain.",
      "**PREOPANC** randomized resectable and borderline patients to gemcitabine-based chemoradiotherapy before surgery or to upfront surgery: five-year overall survival was **20.5% against 6.5%**.",
      "**NORPACT-1**, a phase 2 trial in resectable head cancer, found **no survival benefit** from neoadjuvant FOLFIRINOX — median survival was 25.1 months against 38.5 months with upfront surgery.",
      "**Alliance A021501**, in borderline disease, found that adding hypofractionated radiation to mFOLFIRINOX **did not help**: chemotherapy alone produced favorable survival and the radiation arm did not.",
    ],
  }, [[NCCN], [NCCN], [PREOPANC], [NORPACT], [A021501]]),
  sourced({
    id: "block-pd-steps",
    type: "sequence",
    heading: "The operation in outline",
    steps: [
      { title: "Stage before committing", detail: "Inspect for occult liver or peritoneal disease. **Diagnostic laparoscopy** first is used selectively for adenocarcinoma and distal cholangiocarcinoma, since high-quality imaging and neoadjuvant therapy have lowered its yield." },
      { title: "Mobilize the head", detail: "An extended **Kocher maneuver** with right colon mobilization lifts the pancreatic head out of the retroperitoneum." },
      { title: "Portal dissection", detail: "Identify the common bile duct, hepatic artery, and portal vein, and divide the **gastroduodenal artery**." },
      { title: "Divide the bowel", detail: "Divide the proximal jejunum, and either the **distal stomach** for a classic resection or the **proximal duodenum** for a pylorus-preserving one." },
      { title: "Divide the pancreas", detail: "Tunnel behind the neck over the SMV, divide the neck, and complete a margin-negative **uncinate dissection** off the SMV and SMA." },
      { title: "Reconstruct", detail: "On the proximal jejunal loop rather than a Roux limb: end-to-side **pancreaticojejunostomy**, end-to-side **hepaticojejunostomy**, then a loop gastro- or duodenojejunostomy." },
    ],
  }, SCORE),
  sourced({
    id: "block-pd-decisions",
    type: "bullets",
    heading: "↳ Intraoperative decisions",
    items: [
      "Any concern for the **proximal duodenal margin** means a classic resection, not pylorus preservation.",
      "The need for **vein resection** is usually evident on preoperative imaging. When tumor is densely adherent to the SMV or portal vein, resect and reconstruct the vein rather than leave a positive margin there.",
    ],
  }, SCORE),
  sourced({
    id: "block-pd-margins",
    type: "prose",
    heading: "↳ What counts as R0",
    text: "The **SMA margin** — the retroperitoneal or uncinate margin — is the one most often positive and the main determinant of local recurrence. Two definitions of a clear margin coexist: at least **1 mm** of clearance, the stricter rule used in European reporting and increasingly elsewhere, against no tumor **at the inked margin**, the older and looser rule. A question about R0 rates is only answerable once you know which one it means. Intraoperatively, the **pancreatic neck** and **bile duct** margins go for frozen section, divided sharply so cautery artifact does not ruin the read.",
  }, OPERATIVE),
  sourced({
    id: "block-pd-variants",
    type: "table",
    heading: "Classic, pylorus-preserving, or pylorus-resecting",
    columns: ["Variant", "What changes", "Evidence"],
    rows: [
      ["**Classic Kausch-Whipple**", "Includes **antrectomy** or distal gastrectomy", "Preferred when tumor is near the pylorus or the duodenal margin is in doubt"],
      ["**Pylorus-preserving**, Traverso-Longmire", "Duodenum divided about **2 to 3 cm** distal to the pylorus", "**No difference** from classic in mortality, morbidity, or survival, with shorter operating time and less blood loss in a 2016 Cochrane review"],
      ["**Pylorus-resecting**, stomach-preserving", "Stomach divided **2 to 3 cm** proximal to the pylorus and otherwise kept", "Proposed to reduce delayed gastric emptying, but the **PROPP** trial found no reduction against pylorus preservation"],
    ],
  }, PACKET),
  sourced({
    id: "block-pd-popf",
    type: "bullets",
    heading: "Postoperative pancreatic fistula",
    items: [
      "Defined as drain fluid of any volume with amylase **over 3 times** the institutional upper limit of normal serum amylase, on or after **postoperative day 3**.",
      "A **biochemical leak**, the old grade A, has **no clinical impact** and is no longer called a fistula.",
      "**Grade B** changes management: drains left in **beyond 3 weeks**, new or repositioned percutaneous or endoscopic drains, angiographic treatment of bleeding, or infection without organ failure.",
      "**Grade C** means reoperation, organ failure, or death.",
      "A **clinically relevant** fistula, CR-POPF, is grade B or C.",
    ],
  }, ISGPS),
  sourcedUnits({
    id: "block-pd-popf-risk",
    type: "bullets",
    heading: "↳ Who leaks, and what to do about it",
    items: [
      "The four **Fistula Risk Score** variables: a **soft gland**, a **small main duct** under 3 mm, high blood loss, and pathology other than adenocarcinoma or pancreatitis.",
      "High body mass index, pancreatic steatosis, and absent fibrosis add risk.",
      "A clinically relevant fistula occurs in roughly **10% to 30%**, and grade C carries mortality of up to about **25%**.",
      "Management is drainage, nutrition, and targeted antibiotics, with **percutaneous drainage** of any undrained collection. **Octreotide** may lower output, but it has not been shown to close a fistula faster.",
    ],
  }, [[OPERATIVE], [OPERATIVE], [OPERATIVE], [PACKET]]),
  sourced({
    id: "block-pd-pph",
    type: "table",
    heading: "Post-pancreatectomy hemorrhage",
    columns: ["Type", "Timing", "Usual cause", "First-line treatment"],
    rows: [
      ["**Early**", "Within **24 hours**", "Technical failure, a slipped tie, or coagulopathy", "**Operative re-exploration**"],
      ["**Late**", "After 24 hours, often **days 7 to 14**", "A pancreatic leak eroding a vessel into a **pseudoaneurysm**, classically the GDA stump", "**Angiography** with embolization or a covered stent"],
    ],
  }, PACKET),
  sourced({
    id: "block-pd-sentinel",
    type: "warning",
    tone: "danger",
    heading: "A sentinel bleed is a pseudoaneurysm until proven otherwise",
    text: "A small, self-limited bleed into a drain or the GI tract, typically in the second postoperative week, is the herald of **catastrophic arterial rupture**. It gets urgent **CT angiography** and angiography, never observation. Interventional radiology goes first because reoperating in an enzyme-digested, friable field carries mortality approaching **50%**; surgery is for the unstable patient or a failed embolization.",
  }, PACKET),
  sourced({
    id: "block-pd-pph-site",
    type: "bullets",
    heading: "↳ Where it bleeds from",
    items: [
      "**Extraluminal** bleeding comes from the uncinate bed, the pancreatic stump, or a GDA pseudoaneurysm.",
      "**Intraluminal** bleeding comes from an anastomosis — the pancreaticojejunostomy or the gastro- or duodenojejunostomy — or later from a marginal ulcer.",
      "Endoscopy helps only when the bleeding is confidently intraluminal; reaching for it first can delay the angiography the patient needed.",
    ],
  }, SCORE),
  sourced({
    id: "block-pd-dge",
    type: "bullets",
    heading: "Delayed gastric emptying",
    items: [
      "The **most common** complication overall, in roughly **10% to 30%**.",
      "ISGPS definition: a nasogastric tube needed **beyond 3 days**, reinserted for vomiting after day 3, or solids not tolerated by **day 7**.",
      "Treat it as **secondary** until CT has excluded a collection, leak, or abscess.",
      "Then decompress, give a prokinetic such as **erythromycin** or metoclopramide, correct potassium and magnesium, and support nutrition.",
    ],
  }, PACKET),
  sourced({
    id: "block-pd-late",
    type: "bullets",
    heading: "↳ Long-term function",
    items: [
      "**Exocrine insufficiency** shows as steatorrhea and weight loss. A **fecal elastase under 100 µg/g** is severe; treat with **pancrelipase** taken with meals.",
      "**Endocrine insufficiency**: monitor glucose and start insulin as needed.",
    ],
  }, PACKET),
  sourcedUnits({
    id: "block-pd-adjuvant",
    type: "bullets",
    heading: "Adjuvant therapy and surveillance",
    items: [
      "Every fit patient with resected adenocarcinoma who did not have neoadjuvant therapy gets about **6 months** of adjuvant chemotherapy.",
      "**PRODIGE-24**: modified FOLFIRINOX against gemcitabine in ECOG 0 to 1 patients gave median overall survival of **53.5 against 35.5 months**, and five-year survival of **43.2% against 31.4%**, at the cost of grade 3 to 4 toxicity in about three quarters.",
      "**Modified FOLFIRINOX** is the preferred regimen for fit patients; **gemcitabine with capecitabine** is the other category 1 combination, and gemcitabine or 5-FU with leucovorin alone serve less-fit patients.",
      "Surveillance: history and examination, **CA 19-9**, and CT of the chest, abdomen, and pelvis every **3 to 6 months for 2 years**, then every 6 to 12 months.",
    ],
  }, [[NCCN], [PRODIGE], [NCCN], [NCCN]]),
  sourcedUnits({
    id: "block-pd-splits",
    type: "table",
    heading: "Board answer versus current practice",
    columns: ["Question", "Board answer", "Current practice"],
    rows: [
      ["Does pylorus preservation cause more delayed gastric emptying?", "**Yes**, and resecting the pylorus fixes it", "**No reliable difference.** QUANUPAD found 50% after classic and 62% after pylorus preservation, not significant, and the PROPP trial found pylorus resection did not reduce it"],
      ["Where does a late hemorrhage come from?", "The **GDA stump**, from a pseudoaneurysm a leak has eroded", "Usually somewhere else: in more than 3,000 resections the GDA was the source in only **16.7%**, and empiric GDA embolization or stenting without a visible source caused morbidity and rebleeding"],
      ["Does an antecolic gastrojejunostomy reduce delayed gastric emptying?", "Antecolic is favored, to keep the anastomosis away from a pancreatic leak", "**No clear difference** across 8 randomized trials and 818 patients; the route is surgeon preference"],
      ["Does the artery-first approach improve survival?", "Taking the SMA plane first gives better margins and an early resectability call", "**MAPLE-PD**, a 354-patient randomized trial, found **no survival difference**; the case rests on margin and safety, not survival"],
      ["Neoadjuvant therapy for borderline disease", "Chemotherapy **plus radiation**", "Chemotherapy alone carries the stronger evidence — **A021501** found no benefit from adding radiation to mFOLFIRINOX"],
      ["Five-year survival after resection", "About **20%** after resection for cure", "Higher in fit patients completing modern adjuvant therapy — **43%** at five years with modified FOLFIRINOX in PRODIGE-24"],
    ],
  }, [[PACKET, OPERATIVE], [PRESTON], [ANTECOLIC], [OPERATIVE], [FISER, A021501], [FISER, PRODIGE]]),
  sourcedUnits({
    id: "block-pd-pearls",
    type: "bullets",
    heading: "Board pearls",
    items: [
      "Painless jaundice, weight loss, and a **double-duct sign** with resectable anatomy: proceed to a Whipple **without a biopsy**.",
      "A pulsatile vessel **posterolateral to the bile duct** is a **replaced right hepatic artery** from the SMA until proven otherwise. Preserve it.",
      "Hepatic pulse lost on the **GDA clamp test**: celiac stenosis, usually from the **median arcuate ligament**. Do not divide the GDA until inflow is restored.",
      "Drain amylase over 3 times serum normal on day 3 or later is a fistula; in a well patient it is a **biochemical leak**, and you observe.",
      "A **sentinel bleed** in the second week: CT angiography and embolization or a covered stent, not reoperation.",
      "Most common complication after a Whipple: **delayed gastric emptying**, treated with **metoclopramide**.",
      "An ulcer at the gastrojejunostomy after a Whipple is a **marginal ulcer**: treat with a proton pump inhibitor.",
      "A suspicious node **outside the field** of resection gets a biopsy only, not a lymphadenectomy.",
      "Steatorrhea and weight loss after a Whipple: **exocrine insufficiency**. Check fecal elastase, then give pancrelipase.",
      "**Fistula and hemorrhage** drive mortality; **delayed gastric emptying** drives length of stay.",
    ],
  }, [[PACKET], [PACKET], [PACKET], [PACKET], [PACKET], [FISER], [FISER], [FISER], [PACKET], [OPERATIVE]]),
  references("block-pd-references", [PACKET, OPERATIVE, SCORE, FISER, NCCN, ISGPS, PRODIGE, PRESTON, PREOPANC, NORPACT, A021501, ANTECOLIC]),
];

export const pancreaticoduodenectomyTopic = buildTopic({
  id: "00000000-0000-4000-8000-000000002320",
  versionId: "00000000-0000-4000-8000-000000002321",
  slug: "pancreaticoduodenectomy",
  title: "Pancreaticoduodenectomy",
  aliases: ["Whipple", "Whipple procedure", "Kausch-Whipple", "pancreatoduodenectomy", "PPPD", "pylorus-preserving pancreaticoduodenectomy", "pylorus-resecting pancreaticoduodenectomy", "Traverso-Longmire", "periampullary cancer", "periampullary tumor", "pancreatic head cancer", "pancreatic head mass", "borderline resectable", "borderline resectable pancreatic cancer", "locally advanced pancreatic cancer", "double-duct sign", "double duct sign", "Courvoisier sign", "Courvoisier gallbladder", "pancreatic fistula", "postoperative pancreatic fistula", "POPF", "CR-POPF", "biochemical leak", "Fistula Risk Score", "post-pancreatectomy hemorrhage", "postpancreatectomy hemorrhage", "PPH", "GDA pseudoaneurysm", "DGE", "ISGPS", "pancreaticojejunostomy", "Child reconstruction", "GDA clamp test", "preoperative biliary drainage", "FOLFIRINOX", "mFOLFIRINOX", "PRODIGE-24", "PREOPANC", "NORPACT-1", "A021501", "PROPP", "QUANUPAD", "MAPLE-PD", "artery-first approach", "SMA margin"],
  scoreNodeId: "pancreas-procedures",
  scoreCategory: "SCORE · Pancreas · Operations & Procedures",
  tags: ["pancreas", "hepatobiliary", "surgical-oncology", "operative-technique", "absite", "score"],
  sourceId: PACKET,
  additionalSourceIds: [OPERATIVE, SCORE, FISER, NCCN, ISGPS, PRODIGE, PRESTON, PREOPANC, NORPACT, A021501, ANTECOLIC],
  blocks,
  reviewedAt: "2026-10-04T00:00:00.000Z",
});
