import { buildTopic, references, sourced } from "@/content/authoring";
import { ACR_BIRADS_SOURCE as BIRADS, BREAST_BIOPSY_PACKET_SOURCE as PACKET, FISER_BREAST_SOURCE as FISER, SCORE_PERCUTANEOUS_BREAST_BIOPSY_SOURCE as SCORE } from "@/content/sources";
import type { TopicBlock } from "@/lib/types";

const blocks: TopicBlock[] = [
  sourced({
    id: "block-breastbx-summary",
    type: "summary",
    heading: "At a glance",
    text: "Image-guided **core needle biopsy** is the standard of care for tissue diagnosis of an imaging-detected breast abnormality, and it has displaced open surgical biopsy as the first step. The whole algorithm runs off **BI-RADS**: category 4 or 5 mandates tissue, ultrasound guides the biopsy whenever a sonographic correlate exists, and calcifications without one go to **stereotactic vacuum-assisted** biopsy with specimen radiography. The judgment that matters afterward is **radiologic-pathologic concordance**.",
  }, PACKET),
  sourced({
    id: "block-breastbx-modalities",
    type: "bullets",
    heading: "The four things a needle can do here",
    items: [
      "**Core needle biopsy** removes tissue cores that preserve architecture, so it distinguishes **invasive from in situ** disease and yields grade plus **ER, PR, and HER2** status.",
      "**Vacuum-assisted biopsy** uses a larger 7 to 11 gauge device to take multiple contiguous cores through **one insertion** with suction, and is superior for calcifications and small or non-mass lesions.",
      "**Cyst aspiration** drains a fluid-filled lesion and is **both diagnostic and therapeutic** — it relieves symptoms and separates cyst from solid.",
      "**Fine-needle aspiration** at 25 to 28 gauge yields **cytology only**, with no architecture; its remaining role is mainly the suspicious **axillary node**.",
      "The argument for core over open biopsy is concrete: a complication rate **under 1%** against 2% to 10%, lower cost, better cosmesis, and **single-stage** definitive surgery with concurrent axillary staging.",
      "Women diagnosed by core biopsy are roughly **14 times more likely** to be treated with a **single** operation than those diagnosed by open biopsy.",
    ],
  }, PACKET),
  sourced({
    id: "block-breastbx-birads",
    type: "table",
    heading: "BI-RADS and what each category obliges you to do",
    columns: ["Category", "Assessment", "Malignancy risk", "Management"],
    rows: [
      ["**0**", "Incomplete", "Not assigned", "Additional imaging — diagnostic views or ultrasound"],
      ["**1**", "Negative", "**0%**", "Routine screening"],
      ["**2**", "Benign — simple cyst, calcified fibroadenoma", "**Essentially zero**", "Return to routine screening"],
      ["**3**", "Probably benign", "**2% or less**", "Short-interval follow-up at **6, 12, and 24 months**, over 1 to 2 years of surveillance"],
      ["**4**", "Suspicious", "**Above 2% and below 95%**", "**Core needle biopsy**"],
      ["**4A**", "Low suspicion", "**2% to 9%**", "Core needle biopsy"],
      ["**4B**", "Moderate suspicion", "**10% to 49%**", "Core needle biopsy"],
      ["**4C**", "High suspicion", "**50% to 94%**", "Core needle biopsy"],
      ["**5**", "Highly suggestive of malignancy", "**95% or greater**", "**Mandatory** biopsy — any benign result is automatically discordant"],
      ["**6**", "Known biopsy-proven malignancy", "Established", "Definitive oncologic therapy"],
    ],
  }, BIRADS),
  sourced({
    id: "block-breastbx-category3",
    type: "prose",
    heading: "↳ The category 3 rule has fine print",
    text: "Probably-benign surveillance is validated for exactly three findings: a **noncalcified circumscribed solid mass**, a **focal asymmetry**, and a **solitary group of punctate calcifications**. It requires a **complete diagnostic workup** first, and it must **not** be applied to a lesion that is **new, enlarging, or palpable**. Stretching category 3 over a palpable mass is how a cancer gets six months of watching instead of a needle.",
  }, BIRADS),
  sourced({
    id: "block-breastbx-workup",
    type: "flow",
    heading: "Working up a palpable mass",
    nodes: [
      { id: "mass", label: "Palpable breast mass" },
      { id: "young", label: "Under 30 — targeted ultrasound first, because dense tissue blunts mammographic sensitivity" },
      { id: "older", label: "30 or older — bilateral diagnostic mammogram with tomosynthesis plus targeted ultrasound" },
      { id: "assess", label: "Assign a BI-RADS category on the completed diagnostic workup" },
      { id: "benign", label: "BI-RADS 1 or 2 — return to routine screening", tone: "good" },
      { id: "probably", label: "BI-RADS 3 — short-interval imaging follow-up, unless the lesion is new, enlarging, or palpable", tone: "default" },
      { id: "suspicious", label: "BI-RADS 4 or 5 — image-guided core needle biopsy with a marker clip", tone: "caution" },
      { id: "concordant", label: "Benign pathology that explains the imaging — routine or short-interval follow-up", tone: "good" },
      { id: "discordant", label: "Discordant benign result — repeat image-guided biopsy or needle-localized excision", tone: "caution" },
    ],
    edges: [
      { from: "mass", to: "young", label: "age under 30" },
      { from: "mass", to: "older", label: "age 30 or older" },
      { from: "young", to: "assess" },
      { from: "older", to: "assess" },
      { from: "assess", to: "benign" },
      { from: "assess", to: "probably" },
      { from: "assess", to: "suspicious" },
      { from: "suspicious", to: "concordant", label: "concordant" },
      { from: "suspicious", to: "discordant", label: "not concordant" },
    ],
  }, PACKET),
  sourced({
    id: "block-breastbx-guidance",
    type: "table",
    heading: "Choosing the guidance modality",
    columns: ["Modality", "Preferred for", "What it requires"],
    rows: [
      ["**Ultrasound-guided**", "Any lesion with a **sonographic correlate** — the first-line choice", "Real-time visualization, no radiation or contrast; faster, cheaper, and most comfortable. Spring-loaded or vacuum devices both work"],
      ["**Stereotactic or tomosynthesis-guided**", "**Calcifications**, architectural distortion, and asymmetries or masses **without** an ultrasound correlate", "A **vacuum-assisted** device, and **mandatory specimen radiography** when the target is calcifications"],
      ["**MRI-guided**", "Lesions visible **only on MRI**, such as non-mass enhancement", "Try MRI-directed targeted ultrasound or contrast-enhanced mammography first; needs a vacuum device"],
    ],
  }, PACKET),
  sourced({
    id: "block-breastbx-indications",
    type: "bullets",
    heading: "Indications and contraindications",
    items: [
      "**Biopsy any BI-RADS 4 or 5 lesion** — suspicious calcifications, mass, architectural distortion, or focal asymmetry — on mammography, ultrasound, or MRI.",
      "Biopsy even at very high probability of malignancy, because tissue is what supplies **biomarker and molecular profiling** for treatment planning.",
      "**BI-RADS 3**: biopsy is a legitimate option instead of short-interval follow-up, by shared decision-making or overriding clinical concern.",
      "**BI-RADS 6**: biopsy an additional lesion when the histology would change management.",
      "**Aspirate a cyst** for symptomatic or painful disease, uncertainty between a complicated cyst and a solid mass, correlation with another modality, or suspected abscess. Persistence through menstrual cycles and progressive enlargement also support it.",
      "A **simple cyst needs no aspiration** unless it bothers the patient — it is **BI-RADS 2** with essentially no malignant risk.",
      "**Contraindications to core biopsy** are almost entirely technical: an extremely superficial lesion, or a target lying **immediately against the chest wall** where needle excursion is unsafe.",
      "**Contraindications specific to stereotactic biopsy**: inability to hold the prone or upright position, a target too close to **nipple, skin, chest wall, or implant**, weight beyond the table limit, and **insufficient compressed thickness for an adequate stroke margin**.",
      "**Relative**: uncorrectable coagulopathy or anticoagulation, managed per protocol rather than treated as an absolute bar.",
    ],
  }, PACKET),
  sourced({
    id: "block-breastbx-complex",
    type: "warning",
    tone: "pearl",
    heading: "Complicated is not complex, and the difference decides needle versus aspiration",
    text: "A **complicated** cyst has homogeneous internal echoes or debris, **no solid component and no flow** — it is **BI-RADS 3**. A **complex cystic and solid mass** has a thick wall, thick septations, an intracystic or mural solid nodule, mixed cystic and solid components, or **vascular flow on Doppler** — it is **BI-RADS 4 and it gets a core biopsy**, not a simple aspiration. Clustered microcysts are **BI-RADS 2**. Conflating the two words is how a solid nodule gets aspirated and dismissed.",
  }, PACKET),
  sourced({
    id: "block-breastbx-aspiration",
    type: "sequence",
    heading: "Ultrasound-guided cyst aspiration, step by step",
    steps: [
      { title: "Verify the target", detail: "Confirm the simple-cyst criteria under real-time ultrasound: **anechoic, round or oval, circumscribed, thin-walled**, with **posterior acoustic enhancement**." },
      { title: "Prep and anesthetize", detail: "Create a **sterile field**, cleanse the skin, and infiltrate local anesthetic into the skin and subcutaneous tract." },
      { title: "Aspirate under vision", detail: "Guide the needle to the **center of the cyst** under real-time ultrasound, apply suction, and make additional passes until it is decompressed." },
      { title: "Withdraw safely", detail: "**Release suction before withdrawing** so the tract is not seeded, then dress the site." },
      { title: "Document collapse", detail: "Confirm **complete collapse** with no residual mural nodule. Anything left behind changes the plan." },
    ],
  }, SCORE),
  sourced({
    id: "block-breastbx-aspirate",
    type: "table",
    heading: "↳ Managing what comes back",
    columns: ["Aspirate", "What it means", "What to do"],
    rows: [
      ["**Non-bloody** — green, yellow, straw, or cloudy — with complete collapse", "Benign", "**Discard the fluid.** Routine cytology is **not recommended**, and the patient returns to screening"],
      ["**Bloody**, without a traumatic tap", "Potentially significant", "Place a **marker clip** and send the fluid for **cytology**, with culture if infection is suspected"],
      ["Bloody with **negative** cytology", "Unresolved", "Consider **core needle biopsy** or short-term follow-up"],
      ["Bloody with **atypical or malignant** cytology", "Diagnostic", "**Surgical consultation** with a view to excision"],
      ["**No fluid**, incomplete collapse, a persisting mass, or rapid recurrence", "Not a simple cyst", "**Convert to ultrasound-guided core needle biopsy** with clip placement, or proceed to excisional biopsy"],
    ],
  }, SCORE),
  sourced({
    id: "block-breastbx-stereotactic",
    type: "sequence",
    heading: "Stereotactic core needle biopsy, step by step",
    steps: [
      { title: "Position and compress", detail: "Prone on a stereotactic table or upright, with the breast compressed so the **target sits closest to the needle entry site**." },
      { title: "Triangulate", detail: "Take a scout image, then a **stereo pair at plus and minus 15 degrees**, to compute the target's X, Y, and Z coordinates." },
      { title: "Check the stroke margin", detail: "Confirm a **positive stroke margin** — the fired needle must not strike the detector or exit through the far skin. This is the step that is skipped and then regretted." },
      { title: "Sample", detail: "Prep, anesthetize, make an **11-blade dermatotomy**, advance to pre-fire, take **pre-fire and post-fire images**, then acquire multiple contiguous cores with the **vacuum-assisted** device rotated through 360 degrees." },
      { title: "Radiograph the specimen", detail: "**Mandatory when biopsying calcifications** — confirm the targeted calcifications are actually in the specimen before the patient leaves." },
      { title: "Mark and document", detail: "Deploy a **radiopaque, nonmagnetic marker clip**, then obtain a **post-biopsy two-view mammogram** to record where the clip actually landed." },
    ],
  }, SCORE),
  sourced({
    id: "block-breastbx-concordance",
    type: "prose",
    heading: "Radiologic-pathologic concordance",
    text: "**Discordance** means benign pathology that does not explain a suspicious imaging finding — a spiculated mass returning \"fibrocystic changes\" is the archetype. The rule that follows is absolute: a **BI-RADS 5 lesion with any non-malignant result is automatically discordant**, and benign pathology is never accepted for a radiographically suspicious lesion without proven concordance. Management is **repeat image-guided core biopsy or needle-localized surgical excision**, and the concordance judgment belongs to the radiologist and breast specialist, usually at a multidisciplinary radiology-pathology conference.",
  }, PACKET),
  sourced({
    id: "block-breastbx-b3",
    type: "table",
    heading: "High-risk lesions and their upgrade rates",
    columns: ["Lesion on core biopsy", "Upgrade to DCIS or invasive disease", "Classic management", "Current nuance"],
    rows: [
      ["**Atypical ductal hyperplasia**", "Pooled around **29%**, range 9% to 56%", "**Surgical excision**", "**Selective observation** for carefully chosen focal disease, with multidisciplinary input"],
      ["**ADH bordering on DCIS**", "**40% to 46%**", "Excision", "Higher risk than conventional atypical ductal hyperplasia — excise"],
      ["**Flat epithelial atypia**", "About **10% to 17%**", "Excision, classically", "Observation is reasonable if small, fully sampled, concordant, and without other atypia"],
      ["**Classic LCIS and atypical lobular hyperplasia**", "Low — **0% to 6%** when incidental and concordant", "Historically excised", "Routine excision **generally not required** when incidental and concordant"],
      ["**Non-classic LCIS**, pleomorphic or florid", "Higher, with limited outcome data", "**Excision to negative margins**", "Treated like DCIS; the evidence base remains thin"],
      ["**Papilloma without atypia**", "About **3% to 10%**", "Excision, or vacuum-assisted removal", "Observation is an option when fully sampled and concordant"],
      ["**Radial scar or complex sclerosing lesion**", "About **5% to 16%**, driven by accompanying atypia", "Excision, classically", "Vacuum-assisted excision or surveillance if adequately sampled **without atypia**"],
    ],
  }, PACKET),
  sourced({
    id: "block-breastbx-adh",
    type: "prose",
    heading: "↳ The ADH argument, stated carefully",
    text: "The default answer for **atypical ductal hyperplasia** on core biopsy is still **surgical excision**, because the pooled upgrade rate stays above the 2% threshold regardless of device. Current **ASBrS** guidance accepts that a **subset** may be observed, and the conditions the supporting literature applies are consistent: **no palpable mass**; an imaging finding limited to **calcifications**, with no mass, asymmetry, or distortion; **focal** disease of small volume; confirmed **radiologic-pathologic concordance**; **more than half** the imaging abnormality removed at biopsy; and **multidisciplinary** agreement. Miss any of those and the answer reverts to excision. Separately, ADH carries a **fourfold relative risk** of future breast cancer and roughly **30% cumulative incidence at 25 years**, which is what makes **risk-reduction therapy** — tamoxifen, raloxifene, or an aromatase inhibitor — part of the conversation.",
  }, PACKET),
  sourced({
    id: "block-breastbx-complications",
    type: "bullets",
    heading: "Complications and their management",
    items: [
      "**Vasovagal reaction**: release the compression, uncross the legs, and lay the patient **supine or in Trendelenburg**. It is self-limited and needs nothing more.",
      "**Hematoma**: **immediate manual compression and ice**, then a supportive compressive bra. Evacuation is rarely needed unless it expands rapidly or threatens the skin.",
      "**Infection**: delayed erythema, warmth, and tenderness, treated with a short oral course covering **skin flora**.",
      "**Clip displacement or migration**, the accordion effect: if the tract is identifiable, deploy a **second distinct clip**; otherwise document the clip-to-target **distance and direction** on post-procedure mammography for operative planning.",
      "**Milk fistula** after core biopsy in lactation is **rare** — it is not a reason to delay an indicated biopsy.",
    ],
  }, SCORE),
  sourced({
    id: "block-breastbx-splits",
    type: "table",
    heading: "Board answer versus current practice",
    columns: ["Question", "Board answer", "Current practice"],
    rows: [
      ["Age at which a palpable mass gets a mammogram as well as ultrasound", "**40** — Fiser keys ultrasound and core biopsy under 40, and bilateral mammography over 40", "**30** — both the SCORE module and current guidance add diagnostic mammography with tomosynthesis at **30 and older**"],
      ["Upgrade rate for atypical ductal hyperplasia", "**15%** to DCIS and **3%** to invasive disease", "Pooled around **29%**, range 9% to 56%; the management answer, excision, is unchanged"],
      ["Radial scar on core biopsy", "**All** require excisional biopsy — the diagnosis cannot be made on core alone", "Vacuum-assisted excision or surveillance is reasonable when the lesion is **adequately sampled and free of atypia**"],
      ["Classic LCIS or atypical lobular hyperplasia, incidental and concordant", "Excise, or follow closely with imaging every 6 to 12 months", "Routine excision **generally not required**; pleomorphic and florid variants are the ones that still come out"],
      ["Which device is first-line for calcifications", "**14 gauge spring-loaded core needle biopsy** is the standard", "**Vacuum-assisted biopsy** is increasingly favored — a 60-study meta-analysis found lower ADH underestimation (RR 0.63) and DCIS underestimation (RR 0.47), better calcification retrieval, and fewer repeat biopsies"],
    ],
  }, PACKET),
  sourced({
    id: "block-breastbx-discordance-warning",
    type: "warning",
    tone: "danger",
    heading: "A BI-RADS 5 lesion with a benign result has not been diagnosed",
    text: "Category 5 means a **95% or greater** probability of malignancy before the needle went in. A benign core result against that pretest probability is **automatically discordant** — it is far likelier that the lesion was missed than that the imaging was wrong. **Re-biopsy or excise.** Accepting the benign report is the single most consequential error in this whole workflow.",
  }, PACKET),
  sourced({
    id: "block-breastbx-pearls",
    type: "bullets",
    heading: "Board pearls",
    items: [
      "**BI-RADS 4 or 5 means tissue diagnosis, always**, and BI-RADS 5 with benign pathology means re-biopsy or excise.",
      "**Complex cystic and solid mass** — solid component, thick septa, mural nodule, or flow — is **BI-RADS 4 and gets a core biopsy**, not an aspiration.",
      "**Simple cyst is BI-RADS 2** and needs no aspiration unless symptomatic; a **non-bloody aspirate that fully collapses is discarded** without cytology.",
      "**Bloody cyst fluid or a residual mass after aspiration** means clip, cytology, and core biopsy or excision.",
      "**Palpable mass under 30 gets ultrasound first**; **30 or older gets diagnostic mammography plus ultrasound**.",
      "**Ultrasound guides the biopsy whenever a sonographic correlate exists**; calcifications without one go **stereotactic and vacuum-assisted**, with specimen radiography.",
      "**Always place a marker clip** and confirm its position with **post-biopsy two-view mammography**.",
      "**ADH on core biopsy still means excision** as the default, with selective observation reserved for focal, concordant, calcification-only disease agreed multidisciplinarily.",
      "Mammography is **not contraindicated in pregnancy**, and an indicated biopsy should proceed; **contrast MRI is** avoided because gadolinium crosses the placenta.",
    ],
  }, PACKET),
  references("block-breastbx-references", [PACKET, SCORE, BIRADS, FISER]),
];

export const percutaneousBreastBiopsyTopic = buildTopic({
  id: "00000000-0000-4000-8000-000000002210",
  versionId: "00000000-0000-4000-8000-000000002211",
  slug: "percutaneous-breast-biopsy-and-cyst-aspiration",
  title: "Percutaneous Breast Biopsy and Cyst Aspiration",
  aliases: ["percutaneous breast biopsy", "breast biopsy", "core needle biopsy", "core biopsy", "CNB", "vacuum-assisted biopsy", "vacuum assisted breast biopsy", "VAB", "stereotactic biopsy", "stereotactic core biopsy", "cyst aspiration", "breast cyst aspiration", "fine-needle aspiration", "FNA", "BI-RADS", "BIRADS", "breast imaging reporting and data system", "marker clip", "biopsy clip", "specimen radiography", "radiologic-pathologic concordance", "discordance", "atypical ductal hyperplasia", "ADH", "flat epithelial atypia", "FEA", "atypical lobular hyperplasia", "radial scar", "complex sclerosing lesion", "intraductal papilloma", "high-risk breast lesion", "B3 lesion", "complex cystic and solid mass", "complicated cyst", "simple cyst", "milk fistula", "stroke margin"],
  scoreNodeId: "breast-procedures",
  scoreCategory: "SCORE · Breast · Operations & Procedures",
  tags: ["breast", "biopsy", "imaging", "operative-technique", "absite", "score"],
  sourceId: PACKET,
  additionalSourceIds: [SCORE, BIRADS, FISER],
  blocks,
  reviewedAt: "2026-08-25T00:00:00.000Z",
});
