import { buildTopic, references, sourced } from "@/content/authoring";
import { ASCRS_HEMORRHOIDS_SOURCE as ASCRS, FISER_ANORECTAL_SOURCE as FISER, HEMORRHOIDS_PACKET_SOURCE as PACKET, SCORE_HEMORRHOIDS_SOURCE as SCORE } from "@/content/sources";
import type { TopicBlock } from "@/lib/types";

const blocks: TopicBlock[] = [
  sourced({
    id: "block-hemproc-summary",
    type: "summary",
    heading: "At a glance",
    text: "Procedures for **[[hemorrhoids]]** sort by grade and by which side of the dentate line the problem sits on. Grades I and II, and selected grade III, belong in the office; **rubber band ligation** is the most effective of the office options and **sclerotherapy** the safest on anticoagulation. Grade III and IV disease, a symptomatic external component, and any complication go to **excisional hemorrhoidectomy** — the most durable operation and the most painful one.",
  }, PACKET),
  sourced({
    id: "block-hemproc-flow",
    type: "flow",
    heading: "Choosing the procedure",
    nodes: [
      { id: "symptomatic", label: "Symptomatic hemorrhoidal disease, graded on anoscopy" },
      { id: "medical", label: "Fiber, fluid, and behavioral change first, at every grade" },
      { id: "office", label: "Grade I or II, or selected grade III, that failed medical therapy", tone: "default" },
      { id: "band", label: "Rubber band ligation — the most effective office procedure", tone: "good" },
      { id: "sclero", label: "Sclerotherapy or infrared coagulation — small columns, or anticoagulation", tone: "good" },
      { id: "operative", label: "Grade III or IV, mixed internal and external, symptomatic external component, or failed office therapy", tone: "caution" },
      { id: "excision", label: "Excisional hemorrhoidectomy — Milligan-Morgan open or Ferguson closed", tone: "caution" },
      { id: "emergency", label: "Strangulation, gangrene, or irreducible incarceration", tone: "caution" },
      { id: "urgent", label: "Emergent operative intervention, pregnancy included", tone: "caution" },
    ],
    edges: [
      { from: "symptomatic", to: "medical" },
      { from: "medical", to: "office", label: "bleeding or prolapse persists" },
      { from: "medical", to: "operative", label: "advanced grade or external component" },
      { from: "medical", to: "emergency", label: "acute compromise" },
      { from: "office", to: "band", label: "not anticoagulated" },
      { from: "office", to: "sclero", label: "anticoagulated or small columns" },
      { from: "operative", to: "excision" },
      { from: "emergency", to: "urgent" },
    ],
  }, PACKET),
  sourced({
    id: "block-hemproc-office",
    type: "table",
    heading: "Office-based procedures compared",
    columns: ["Procedure", "Best use", "Numbers to know", "The caveat"],
    rows: [
      ["**Rubber band ligation**", "The most effective office option — grade I and II, selected grade III", "**87% to 89%** symptom resolution; roughly a fifth to a third need repeat treatment; recurrence about **15.5% at two years**", "Place the band **1 to 2 cm above the dentate line**; use caution on anticoagulation"],
      ["**Sclerotherapy**", "Small columns, and the anticoagulated patient", "Short-term success **70% to 85%**; long-term remission in only about **one third**", "Less effective than banding, but the **lowest bleeding risk** of the office options"],
      ["**Infrared coagulation**", "Grade I and II bleeding", "**70% to 80%** success", "Less durable than banding; pain if the probe is misplaced"],
    ],
  }, PACKET),
  sourced({
    id: "block-hemproc-banding",
    type: "bullets",
    heading: "Rubber band ligation — technique and trouble",
    items: [
      "Position **prone jackknife** or **left lateral decubitus**, with good light and a **slotted anoscope**.",
      "Deploy the band at the **apex** of the column, **1 to 2 cm above the dentate line**, to stay clear of sensate tissue.",
      "One to three columns can be banded in a sitting, but pain and complication rates climb with each additional column.",
      "**Procedural pain** usually means the band sits too low — **remove it immediately** rather than waiting it out.",
      "**Delayed hemorrhage at roughly 5 to 14 days**, as the eschar and pedicle slough, is the characteristic complication; about **1%** is severe.",
      "**Pelvic sepsis** is rare and life-threatening, and it is the reason a post-banding patient with fever and pain is never reassured by telephone.",
      "Other complications include stenosis and, uncommonly, **Fournier gangrene**.",
    ],
  }, SCORE),
  sourced({
    id: "block-hemproc-excision-indications",
    type: "bullets",
    heading: "When to operate",
    items: [
      "Symptoms that persist or recur despite lifestyle change, medical management, and office procedures.",
      "Internal hemorrhoids **beyond grade II** that are not amenable to banding.",
      "Symptomatic hemorrhoids with a **large external component** — the office cannot address what sits below the dentate line.",
      "**Mixed internal and external** disease, where a single operation can treat both.",
      "Complications of the disease itself: **thrombosis, strangulation, and gangrene**.",
      "**Strangulated or gangrenous disease requires immediate operative intervention**, and pregnancy does not defer it.",
    ],
  }, SCORE),
  sourced({
    id: "block-hemproc-steps",
    type: "sequence",
    heading: "Key steps of excisional hemorrhoidectomy",
    steps: [
      { title: "Start with the largest column", detail: "Begin with the **largest and most bothersome** hemorrhoid, which sets the geometry for what remains." },
      { title: "Develop the plane off the sphincter", detail: "**Dissect the cushion off the internal anal sphincter.** The sphincter is never excised and never divided — this is the step that protects continence." },
      { title: "Ligate the pedicle high", detail: "**Suture-ligate the vascular pedicle** at the apex, above the level of the excision." },
      { title: "Excise the cushion", detail: "Remove it sharply, with cautery, or with a **vessel-sealing device**; bipolar sealing may reduce early postoperative pain, though long-term data are thin." },
      { title: "Close or leave open", detail: "**Ferguson** closes the wound and **Milligan-Morgan** leaves it open, with similar recurrence and complication rates either way." },
      { title: "Preserve the skin bridges", detail: "Leave **generous anoderm and skin bridges** between excision sites. Failing here is what produces **anal stenosis**." },
    ],
  }, SCORE),
  sourced({
    id: "block-hemproc-thrombosed",
    type: "table",
    heading: "The thrombosed external hemorrhoid — the 72-hour rule",
    columns: ["Timing", "What to do", "Why"],
    rows: [
      ["**Within 72 hours** (up to 4 days by the ACG) with severe pain", "**Excise** the clot with the overlying skin in the office — an elliptical excision, not a lancing", "Faster relief, longer remission, and recurrence around **6%** against roughly **25%** managed conservatively"],
      ["**Beyond 72 hours**", "**Conservative** care — sitz baths, stool softeners, oral analgesia, topical 5% lidocaine", "The clot is already organizing and resorbing, so excising it now causes more pain than it prevents"],
    ],
  }, PACKET),
  sourced({
    id: "block-hemproc-alternatives",
    type: "table",
    heading: "Alternative operations",
    columns: ["Operation", "The case for it", "The case against it"],
    rows: [
      ["**Doppler-guided hemorrhoidal artery ligation** with or without mucopexy", "Less pain than excision; lower one-year recurrence than banding, **30% against 49%**", "**Higher recurrence than excision**, pooled near **17.5%**, and costlier than banding. An ASCRS conditional recommendation"],
      ["**Stapled hemorrhoidopexy**", "Historically offered for circumferential prolapse with less immediate pain", "**Not recommended first-line** — marginal efficacy, recurrence **32%** against **14%** for excision, no effect on the external component, and rare but catastrophic harms including rectovaginal fistula, rectal perforation, staple-line stenosis, sepsis, and death"],
    ],
  }, ASCRS),
  sourced({
    id: "block-hemproc-postop",
    type: "bullets",
    heading: "Postoperative care is not optional",
    items: [
      "A **proactive bowel regimen** is mandatory — fiber, an osmotic laxative, and a stool softener — because the first bowel movement is the one that hurts and the one that impacts.",
      "Use **multimodal analgesia**, adding a topical anesthetic and **topical diltiazem**, an ASCRS grade 1B recommendation.",
      "Warn the patient plainly that pain will be **significant** and recovery takes **9 to 14 days**; surprise is what drives the emergency visit.",
      "Oral **metronidazole is not superior to placebo** for post-hemorrhoidectomy pain, notwithstanding its persistence in order sets.",
      "Follow up clinically at **6 to 8 weeks**; repeat banding for recurrence, and escalate to operation for failed office therapy or grade IV disease.",
    ],
  }, PACKET),
  sourced({
    id: "block-hemproc-complications",
    type: "table",
    heading: "Complications and what to do",
    columns: ["Complication", "How it shows up", "Management"],
    rows: [
      ["**Urinary retention**", "The most common early complication", "Restrict perioperative fluids and straight-catheterize"],
      ["**Immediate hemorrhage**, within 24 hours", "Technical — a slipped ligature", "**Return to the operating room** for hemostasis"],
      ["**Delayed hemorrhage**, around 7 to 14 days", "Eschar slough at the pedicle", "**Foley balloon tamponade** or anal packing first; operate if that fails"],
      ["**Anal stenosis**", "Excess anoderm removed or inadequate skin bridges, classically after emergent three-column excision", "Bulk laxatives and dilation; **anoplasty** — Y-V or house flap — for a severe stricture"],
      ["**Fecal incontinence**", "Thermal or mechanical sphincter injury, or too much cushion excised", "Prevention is the whole answer; assess the sphincter before offering repair"],
      ["**Pelvic and perineal sepsis**", "**Fever, worsening perianal pain, and urinary retention** — the classic triad", "**Emergent examination under anesthesia**, debridement, and broad-spectrum intravenous antibiotics"],
      ["**Rectovaginal or anovaginal fistula**", "Stool or flatus per vagina, from suture bites taken too deep", "Delineate the tract and repair formally; more common after stapled procedures"],
    ],
  }, PACKET),
  sourced({
    id: "block-hemproc-sepsis",
    type: "warning",
    tone: "danger",
    heading: "Fever, pain, and urinary retention after any anorectal procedure means the operating room",
    text: "**Pelvic sepsis** is rare after banding or hemorrhoidectomy and it kills. The triad is **fever, severe or worsening perianal pain, and urinary retention**, and it can appear after a procedure as minor as a band. The response is **emergent examination under anesthesia** with debridement and broad-spectrum intravenous antibiotics — not an outpatient antibiotic prescription and a next-week appointment.",
  }, PACKET),
  sourced({
    id: "block-hemproc-splits",
    type: "table",
    heading: "Board answer versus current practice",
    columns: ["Question", "Board answer", "Current practice"],
    rows: [
      ["Thrombosed external hemorrhoid inside 72 hours", "Older texts say **incision and drainage**, or lancing", "**Complete elliptical excision** of clot and overlying skin — lancing leaves high recurrence and persistent bleeding. The ACG's pregnancy guidance still prints the older wording"],
      ["Stapled hemorrhoidopexy", "A reasonable option for circumferential prolapse", "**Not recommended first-line** by the 2024 ASCRS guideline, on marginal efficacy and a serious risk profile"],
      ["Banding an anticoagulated patient", "**Absolutely contraindicated**", "**Caution**, and hold agents where possible — a retrospective clopidogrel cohort found no significant excess bleeding. **Sclerotherapy** remains the safer office alternative"],
      ["Operation for grade III and IV disease", "**Three-quadrant excision**", "Same operation, with explicit attention to **preserving skin bridges** — three-column excision without them is the classic route to stenosis"],
    ],
  }, PACKET),
  sourced({
    id: "block-hemproc-pearls",
    type: "bullets",
    heading: "Board pearls",
    items: [
      "**Rubber band ligation is the most effective office procedure**, and **excisional hemorrhoidectomy is the most durable operation** for grade III and IV or mixed disease.",
      "**Band 1 to 2 cm above the dentate line**, and never band anything below it.",
      "**Anticoagulated patient needing an office procedure — sclerotherapy** is the keyed answer.",
      "**Excise a thrombosed external hemorrhoid inside 72 hours, treat it medically after**, and excise rather than lance.",
      "Bleeding **within 24 hours** is a slipped ligature and goes back to the operating room; bleeding at **7 to 14 days** is eschar slough and gets tamponade first.",
      "**Dissect off the internal sphincter and never through it**, and leave the skin bridges alone.",
      "**Urinary retention is the most common early complication** of hemorrhoidectomy.",
      "**Stapled hemorrhoidopexy does not treat the external component** and is no longer a first-line choice.",
    ],
  }, PACKET),
  references("block-hemproc-references", [PACKET, SCORE, ASCRS, FISER]),
];

export const proceduresForHemorrhoidsTopic = buildTopic({
  id: "00000000-0000-4000-8000-000000002120",
  versionId: "00000000-0000-4000-8000-000000002121",
  slug: "procedures-for-hemorrhoids",
  title: "Procedures for Hemorrhoids",
  aliases: ["hemorrhoidectomy", "excisional hemorrhoidectomy", "rubber band ligation", "band ligation", "hemorrhoid banding", "sclerotherapy", "infrared coagulation", "Milligan-Morgan", "Ferguson hemorrhoidectomy", "stapled hemorrhoidopexy", "procedure for prolapse and hemorrhoids", "hemorrhoidal artery ligation", "mucopexy", "hemorrhoid surgery", "anoplasty", "house flap", "anal stenosis", "pelvic sepsis", "thrombosed hemorrhoid excision", "slotted anoscope", "prone jackknife"],
  scoreNodeId: "anorectal-procedures",
  scoreCategory: "SCORE · Anorectal · Operations & Procedures",
  tags: ["anorectal", "hemorrhoids", "colorectal", "operative-technique", "absite", "score"],
  sourceId: PACKET,
  additionalSourceIds: [SCORE, ASCRS, FISER],
  blocks,
  reviewedAt: "2026-08-25T00:00:00.000Z",
});
