import { buildTopic, references, sourced } from "@/content/authoring";
import { ULCERATIVE_COLITIS_PACKET_SOURCE as PACKET } from "@/content/sources";
import type { TopicBlock } from "@/lib/types";

const blocks: TopicBlock[] = [
  sourced({
    id: "block-uc-summary",
    type: "summary",
    heading: "At a glance",
    text: "Ulcerative colitis is **continuous, confluent, circumferential mucosal inflammation that begins in the rectum and extends proximally without skip areas**, and the two words that govern everything surgical are **continuous** and **mucosal**. Because inflammation never leaves the colon and rectum, **total proctocolectomy is curative of the intestinal disease** — the one thing that can never be said of Crohn. Because it is limited to mucosa and submucosa, sparing muscularis propria and serosa except when complicated by toxic megacolon or perforation, it bleeds and it dilates rather than fistulising and stricturing. Roughly **10 to 30 percent of patients eventually come to surgery**, and the surgical work divides cleanly in two: the **acute severe flare**, where the decision is when to stop waiting, and the **elective reconstruction**, where the decision is how many stages and what kind of anastomosis.",
  }, PACKET),
  sourced({
    id: "block-uc-pathology",
    type: "bullets",
    heading: "Pathology and endoscopic hallmarks",
    items: [
      "**Depth**: inflammation is limited to **mucosa and submucosa**, sparing muscularis propria and serosa unless complicated by toxic megacolon or perforation. This is the key distinction from transmural Crohn disease.",
      "**Endoscopic hallmarks**: erythema, **loss of vascular markings**, granularity, friability, pseudopolyps, and continuous involvement extending proximally from the rectum.",
      "**Active histology**: neutrophilic **crypt abscesses**, crypt distortion and branching, crypt atrophy.",
      "**Chronic histology**: basal plasmacytosis, basal lymphoid aggregates, and **Paneth cell metaplasia**.",
      "**Granulomas are absent** — their presence should redirect you toward Crohn disease.",
      "**Pathogenesis**: a dysregulated mucosal immune response to gut microbiota in a genetically susceptible host is the dominant driver, with environmental factors, an altered microbiome, and epithelial barrier dysfunction contributing.",
      "**Smoking is protective** in ulcerative colitis, the reverse of Crohn, and **appendectomy is associated with reduced risk**.",
    ],
  }, PACKET),
  sourced({
    id: "block-uc-epidemiology",
    type: "bullets",
    heading: "Epidemiology and who ends up in an operating room",
    items: [
      "Up to **25 percent** of patients are hospitalised for **acute severe ulcerative colitis** at some point, and **10 to 30 percent** ultimately require surgery.",
      "**Predictors of colectomy or an aggressive course**: extensive colitis, deep ulcers, need for systemic steroids, young age at diagnosis, elevated CRP or ESR, and a prior hospitalisation for colitis.",
      "**Colorectal cancer risk factors**: longer disease duration, greater extent (pancolitis above left-sided above proctitis), severity of inflammation, concomitant **primary sclerosing cholangitis**, a **first-degree relative with colorectal cancer under 50 years**, and prior dysplasia.",
      "**Extraintestinal manifestations**: primary sclerosing cholangitis, peripheral and axial arthropathies, uveitis and episcleritis, erythema nodosum, and pyoderma gangrenosum.",
    ],
  }, PACKET),
  sourced({
    id: "block-uc-presentation",
    type: "bullets",
    heading: "Presentation and red flags",
    items: [
      "**Typical**: bloody diarrhea with mucus, **tenesmus**, fecal urgency, and lower abdominal cramping, with fever, weight loss, and fatigue appearing as severity climbs.",
      "**Red flags for acute severe colitis or a complication**: high stool frequency with systemic toxicity, abdominal distension, tympany, and rebound or guarding — the last two suggesting toxic megacolon or perforation.",
      "Extraintestinal manifestations that **improve after colectomy**: peripheral arthritis, uveitis and episcleritis, and most erythema nodosum.",
      "Extraintestinal manifestations that **do not improve after colectomy**: primary sclerosing cholangitis and axial arthropathy — ankylosing spondylitis and sacroiliitis, HLA-B27 associated.",
    ],
  }, PACKET),
  sourced({
    id: "block-uc-workup",
    type: "bullets",
    heading: "Diagnosis and workup",
    items: [
      "**First-line**: flexible sigmoidoscopy or colonoscopy with biopsy showing continuous inflammation extending from the rectum, plus **stool studies to exclude infection including C. difficile**.",
      "**In acute severe colitis**, assess with a **plain abdominal radiograph**: a transverse colon diameter above **5.5 cm** predicts a worse outcome, and **three or more dilated small-bowel loops** predicts nonresponse to medical therapy.",
      "**Reserve CT** for a suspected extraluminal complication or perforation, or where the distinction from Crohn disease is genuinely unclear.",
      "In a severe flare, a **full colonoscopy is avoided** — the risk of perforating an acutely inflamed, dilating colon outweighs what the proximal extent adds.",
    ],
  }, PACKET),
  sourced({
    id: "block-uc-severity",
    type: "table",
    heading: "The criteria that drive decisions",
    columns: ["Criterion", "Definition", "What it triggers"],
    rows: [
      ["Truelove and Witts severe colitis", "**Six or more bloody stools per day** plus at least one systemic sign of toxicity — temperature above 37.8 °C, heart rate above 90, **hemoglobin below 10.5 g/dL**, or ESR above 30 mm/hr", "Admission, intravenous steroids, and surgical involvement from the outset"],
      ["Oxford (Travis) criteria", "On **day 3** of intravenous steroids: more than **8 stools per day**, or 3 to 8 stools with a **CRP above 45 mg/L**", "Predicts roughly **85 percent colectomy risk** — start rescue therapy now"],
      ["Toxic megacolon", "Colonic dilation, usually transverse, above **5.5 to 6 cm** together with systemic toxicity", "Emergent operation if it does not resolve promptly"],
      ["Montreal extent", "E1 proctitis; E2 left-sided, distal to the splenic flexure; E3 extensive or pancolitis", "Sets colorectal cancer surveillance strategy"],
      ["Endoscopic severity", "**Mayo Endoscopic Score 2 to 3**, or **UCEIS 5 to 8**", "Defines moderate-to-severe disease for therapy selection"],
    ],
  }, PACKET),
  sourced({
    id: "block-uc-toxic",
    type: "warning",
    heading: "Do not slow the colon down",
    text: "**Opioids, anticholinergics, and antidiarrheals can precipitate toxic megacolon** in an acutely inflamed colon, and they are prescribed with the best intentions to a patient complaining of pain and stool frequency. Toxic megacolon is **transverse colonic dilation above 6 cm with systemic toxicity**, and once it is established the window to operate before perforation is short. The other half of the same reflex: an acute severe flare needs **VTE prophylaxis**, because inflammatory bowel disease is prothrombotic and the bloody diarrhea reads as a reason to withhold it. It is not.",
  }, PACKET),
  sourced({
    id: "block-uc-asuc-flow",
    type: "flow",
    heading: "Acute severe ulcerative colitis, day by day",
    nodes: [
      { id: "admit", label: "Acute severe ulcerative colitis by Truelove and Witts criteria" },
      { id: "emergent", label: "Free perforation, uncontrolled hemorrhage, toxic megacolon, or multiorgan dysfunction", tone: "caution" },
      { id: "medical", label: "No absolute indication — admit for medical therapy" },
      { id: "steroids", label: "IV methylprednisolone 60 mg daily or hydrocortisone 100 mg three to four times daily, plus VTE prophylaxis, fluid and electrolyte correction, and early surgical consultation" },
      { id: "day3", label: "Reassess on day 3 against the Oxford criteria" },
      { id: "responding", label: "Responding — continue steroids and plan a transition to maintenance therapy", tone: "good" },
      { id: "rescue", label: "Nonresponse: start rescue therapy with infliximab 5 mg/kg or cyclosporine 2 mg/kg/day IV" },
      { id: "day7", label: "Reassess within 4 to 7 days of starting rescue" },
      { id: "rescueWorks", label: "Rescue succeeds — bridge to maintenance therapy and plan outpatient follow-up", tone: "good" },
      { id: "colectomy", label: "Total abdominal colectomy with end ileostomy and a long rectal stump", tone: "caution" },
      { id: "reconstruct", label: "Delayed completion proctectomy with ileal pouch-anal anastomosis once recovered and off steroids", tone: "good" },
    ],
    edges: [
      { from: "admit", to: "emergent", label: "absolute indication" },
      { from: "admit", to: "medical", label: "no absolute indication" },
      { from: "emergent", to: "colectomy" },
      { from: "medical", to: "steroids" },
      { from: "steroids", to: "day3" },
      { from: "day3", to: "responding", label: "responding" },
      { from: "day3", to: "rescue", label: "Oxford criteria met" },
      { from: "rescue", to: "day7" },
      { from: "day7", to: "rescueWorks", label: "responds" },
      { from: "day7", to: "colectomy", label: "fails — do not delay beyond 4 to 7 days" },
      { from: "colectomy", to: "reconstruct" },
    ],
  }, PACKET),
  sourced({
    id: "block-uc-rescue",
    type: "bullets",
    heading: "Rescue therapy, and the clock",
    items: [
      "**First-line for acute severe colitis** is intravenous corticosteroids — methylprednisolone **60 mg daily** or hydrocortisone **100 mg three to four times daily**.",
      "**Rescue at day 3 to 5 nonresponse**: **infliximab 5 mg/kg** or **cyclosporine 2 mg/kg/day intravenously**, with similar short-term efficacy — response rates of **60 to 80 percent** over a mean of **5 to 7 days**.",
      "A recent meta-analysis found **infliximab associated with a lower colectomy risk than cyclosporine** at discharge, at 3 months, and at 12 months.",
      "**Do not delay surgery beyond 4 to 7 days of failed rescue.** The morbidity of a colectomy in a patient who is still salvageable is far lower than in one who has been immunosuppressed into malnutrition and sepsis.",
      "**Early surgical consultation is part of the admission**, not a step taken once medicine has failed.",
    ],
  }, PACKET),
  sourced({
    id: "block-uc-indications",
    type: "bullets",
    heading: "Indications for operation",
    items: [
      "**Emergent and absolute**: free perforation, toxic megacolon, uncontrolled hemorrhage, and multiorgan dysfunction.",
      "**Failure to progress** after 3 to 5 days of intravenous steroids, or after failed rescue therapy.",
      "**Elective, and the most common indication overall**: medically refractory or steroid-dependent disease.",
      "**Medication intolerance**, where the therapy is doing more damage than the colitis.",
      "**High-grade dysplasia**, and **multifocal or endoscopically unresectable low-grade dysplasia**.",
      "**Colorectal cancer**.",
    ],
  }, PACKET),
  sourced({
    id: "block-uc-operations",
    type: "bullets",
    heading: "The operations",
    items: [
      "**Urgent or emergent operation of choice**: **total abdominal colectomy with end ileostomy**, leaving a **long rectal stump** as a Hartmann pouch or a mucous fistula.",
      "**Never construct a pouch acutely** — the risks of pelvic sepsis, bleeding, and nerve injury in an inflamed, immunosuppressed pelvis are the whole reason the operation is staged.",
      "**Elective standard**: restorative **total proctocolectomy with ileal pouch-anal anastomosis**, usually a **J-pouch**.",
      "**High-dose steroids**, defined as more than **20 mg prednisone equivalent per day**, mandate a staged approach with total abdominal colectomy first, to reduce anastomotic leak and pelvic sepsis.",
      "The **long rectal stump** is deliberate: it preserves the plane and the length needed for a later pelvic dissection, and it keeps the dissection out of a pelvis nobody wants to enter twice.",
    ],
  }, PACKET),
  sourced({
    id: "block-uc-staging",
    type: "table",
    heading: "Staged approaches to restorative proctocolectomy",
    columns: ["Approach", "Sequence", "Best suited for", "Notes"],
    rows: [
      ["One-stage", "Total proctocolectomy with ileal pouch-anal anastomosis and no diversion", "Highly selected, healthy patients off steroids and biologics", "Uncommon, with a higher leak risk if misapplied"],
      ["Two-stage (traditional)", "Proctocolectomy with pouch and a diverting loop ileostomy, then ileostomy closure", "Stable, well-nourished patients on minimal immunosuppression", "Historically the most common approach, around **75 percent**"],
      ["Modified two-stage", "Total abdominal colectomy with end ileostomy, then completion proctectomy with pouch and no diversion", "Rising use, avoiding a temporary stoma in more than 75 percent of patients", "Not associated with higher leak or sepsis than the traditional two-stage in the ASCRS review, but a 2025 European cohort found a **higher leak rate of 18 percent against 5 percent**"],
      ["Three-stage", "Total abdominal colectomy with end ileostomy, then completion proctectomy with pouch and loop ileostomy, then reversal", "**Acute severe colitis, fulminant disease, high-dose steroids or biologics, malnutrition, and emergency presentation**", "Safest when inflammation and immunosuppression are high, at the cost of a longer total hospital stay"],
    ],
  }, PACKET),
  sourced({
    id: "block-uc-staging-split",
    type: "prose",
    heading: "Where the evidence on staging genuinely disagrees",
    text: "The **modified two-stage** approach — colectomy first, then completion proctectomy with an undiverted pouch — is attractive for an obvious reason: it spares most patients a temporary stoma while still keeping the pouch out of an acutely inflamed pelvis. The **ASCRS review** found it no worse than the traditional two-stage for leak and pelvic sepsis. A **2025 European cohort** then reported a **leak rate of 18 percent against 5 percent** for the three-stage approach, which is not a rounding difference. Both findings are probably describing something real and the likely reconciliation is selection: an undiverted pouch is safe in the patient who has genuinely recovered from the colectomy — off steroids, nutritionally repleted, months out — and is not safe in the patient who has merely survived it. The teaching that survives either way is that **diversion is what you fall back on when the pelvis, the nutrition, or the immunosuppression is anything less than reassuring**, and that a longer hospital course is the cheaper of the two errors.",
  }, PACKET),
  sourced({
    id: "block-uc-anastomosis",
    type: "prose",
    heading: "Board answer versus current practice: stapled or hand-sewn pouch",
    text: "Classic teaching favours **mucosectomy with a hand-sewn ileal pouch-anal anastomosis**, and the logic is impeccable on its face — strip out every millimetre of at-risk mucosa and there is nothing left to become dysplastic. Current **ASCRS** practice prefers a **double-stapled anastomosis**, which deliberately leaves a short **anal transition zone**, because measured outcomes did not follow the logic. The stapled technique gives **better bowel function and better symptom-specific quality of life**, and the **cuff neoplasia risk turned out to be low** rather than the dominant concern it was assumed to be. Mucosectomy with a hand-sewn anastomosis is now **reserved for dysplasia or cancer involving the distal rectum or anal transition zone**, and it carries higher rates of **nocturnal seepage, stricture, and septic complications**. Give the stapled answer for anything framed around function or guidelines, and the hand-sewn answer when the vignette puts dysplasia in the distal rectum.",
  }, PACKET),
  sourced({
    id: "block-uc-outcomes",
    type: "table",
    heading: "Outcome numbers",
    columns: ["Measure", "Figure", "Qualifier"],
    rows: [
      ["Postoperative mortality after colectomy", "About **1.0 percent**", "Across reported series, including urgent cases"],
      ["Mortality after ileal pouch-anal anastomosis", "**0.5 percent**", "The elective, reconstructive half of the pathway"],
      ["Morbidity after ileal pouch-anal anastomosis", "**19 to 27 percent**", "A reconstruction, not a small operation"],
      ["Pouch failure", "**5 to 10 percent**", "Higher in low-volume centres and in patients who turn out to have Crohn disease"],
      ["Baseline pouch function", "About **4 to 8 bowel movements per day**", "Minor nocturnal seepage is common and should be part of the consent conversation"],
      ["Major incontinence after pouch", "Under **5 percent**", "Distinct from the seepage most patients experience"],
    ],
  }, PACKET),
  sourced({
    id: "block-uc-surveillance",
    type: "bullets",
    heading: "Colorectal cancer surveillance",
    items: [
      "Begin **surveillance colonoscopy 8 years after symptom onset** for disease extending beyond the rectum.",
      "With **primary sclerosing cholangitis**, begin at the **diagnosis of PSC** regardless of disease duration, and scope **annually**.",
      "**Interval is risk-stratified from 1 to 5 years.** Scope **annually** for PSC, active moderate-to-severe inflammation, prior dysplasia, dense pseudopolyposis, a stricture, or a first-degree relative with colorectal cancer.",
      "**Technique**: high-definition white-light endoscopy with or without chromoendoscopy, targeted biopsies of every visible lesion, plus random four-quadrant biopsies every 10 cm for at least **32 samples**.",
      "**Isolated proctitis without proximal extension carries no increased colorectal cancer risk** and reverts to average-risk screening.",
    ],
  }, PACKET),
  sourced({
    id: "block-uc-interval-split",
    type: "prose",
    heading: "A genuine guideline discrepancy: the maximum surveillance interval",
    text: "Societies do not agree on how long a low-risk patient may safely go between scopes, and the disagreement is real rather than a matter of phrasing. **ACG caps the maximum interval at 3 years.** **AGA, BSG, and ECCO allow up to 5 years** in patients who are genuinely low risk — long-standing remission, limited extent, no dysplasia, no PSC, no family history. Everyone agrees on the high-risk end, where annual surveillance is the answer, so the discrepancy only bites in the patient a question is most likely to describe as doing well. If an examination cites a society, follow that society; if it does not, **3 years is the safer answer** because it satisfies every guideline in the room.",
  }, PACKET),
  sourced({
    id: "block-uc-complications",
    type: "bullets",
    heading: "Complications after reconstruction",
    items: [
      "**Pouchitis** is the most common long-term complication of an ileal pouch, affecting up to about **50 percent within 5 years**.",
      "**First-line for pouchitis**: antibiotics — **ciprofloxacin and/or metronidazole for 2 to 4 weeks**.",
      "**Recurrent antibiotic-responsive pouchitis** is managed with **probiotics for prevention**; **chronic antibiotic-refractory pouchitis** calls for **vedolizumab** — the **EARNEST** trial reported remission of **31 percent against 10 percent** on placebo at week 14 — or another advanced therapy, and should prompt you to reconsider **missed Crohn disease**.",
      "**Anastomotic leak and pelvic sepsis** are the leading cause of pouch failure. A **contained** leak is managed with CT-guided drainage and antibiotics; an **uncontained leak or peritonitis** goes to the operating room for washout and diversion.",
      "**Rectal stump blowout**: if the patient is stable, antibiotics with percutaneous or transrectal drainage; if unstable, the operating room. Prevent it by placing a **mucous fistula or a subcutaneous stump** when the tissue is friable, and treat diversion proctitis with topical steroid or mesalamine.",
    ],
  }, PACKET),
  sourced({
    id: "block-uc-pearls",
    type: "bullets",
    heading: "Board pearls",
    items: [
      "**Rectum plus continuous plus mucosal and submucosal with no granulomas** means ulcerative colitis; **skip lesions, transmural inflammation, granulomas, and perianal disease** mean Crohn.",
      "**Smoking is protective in ulcerative colitis** and harmful in Crohn — the classic testable inversion.",
      "**Toxic megacolon is transverse colonic dilation above 6 cm with systemic toxicity**, and opioids, anticholinergics, and antidiarrheals can precipitate it.",
      "**The urgent operation is total abdominal colectomy with end ileostomy and a long rectal stump** — never build a pouch in an acute, septic, or immunosuppressed setting.",
      "**Day-3 Oxford criteria** — more than 8 stools per day, or 3 to 8 with a CRP above 45 — mean start rescue therapy and involve surgery, and do not delay colectomy beyond 4 to 7 days of failed rescue.",
      "**PSC starts surveillance at the PSC diagnosis and scopes annually**, and PSC does not improve after colectomy.",
      "**Classic versus current on the anastomosis**: board teaching favoured mucosectomy with a hand-sewn pouch; the ASCRS standard is a **double-stapled** anastomosis, reserving mucosectomy for distal dysplasia or cancer.",
      "**Classic versus current on staging**: the default two-stage teaching is shifting, and with modern biologic exposure a three-stage or modified two-stage approach is increasingly chosen to reduce pelvic sepsis in sicker patients.",
      "**Extraintestinal manifestations after colectomy**: peripheral arthritis, uveitis and episcleritis, and most erythema nodosum improve; **PSC and axial arthropathy do not**.",
    ],
  }, PACKET),
  references("block-uc-references", [PACKET]),
];

export const ulcerativeColitisTopic = buildTopic({
  id: "00000000-0000-4000-8000-000000001311",
  versionId: "00000000-0000-4000-8000-000000001321",
  slug: "ulcerative-colitis",
  title: "Ulcerative Colitis",
  aliases: ["ulcerative colitis", "UC", "acute severe ulcerative colitis", "ASUC", "inflammatory bowel disease", "IBD", "toxic megacolon", "toxic colitis", "Truelove and Witts", "Truelove Witts", "Oxford criteria", "Travis criteria", "Mayo endoscopic score", "UCEIS", "Montreal classification", "pancolitis", "proctitis", "backwash ileitis", "crypt abscess", "pseudopolyps", "IPAA", "ileal pouch anal anastomosis", "J-pouch", "restorative proctocolectomy", "total abdominal colectomy", "TAC", "total proctocolectomy", "TPC", "pouchitis", "cuffitis", "mucosectomy", "anal transition zone", "rectal stump", "primary sclerosing cholangitis", "PSC", "cyclosporine", "infliximab", "EARNEST", "dysplasia surveillance"],
  scoreNodeId: "large-intestine-conditions",
  scoreCategory: "SCORE · Large Intestine · Diseases & Conditions",
  tags: ["large-intestine", "ulcerative-colitis", "inflammatory-bowel-disease", "colorectal", "ileal-pouch", "absite", "score"],
  sourceId: PACKET,
  blocks,
  reviewedAt: "2026-08-20T00:00:00.000Z",
});
