import { buildTopic, references, sourced } from "@/content/authoring";
import { TRAUMA_VASCULAR_THORACIC_PACKET_SOURCE as PACKET } from "@/content/sources";
import type { TopicBlock } from "@/lib/types";

const blocks: TopicBlock[] = [
  sourced({
    id: "block-vti-summary",
    type: "summary",
    heading: "At a glance",
    text: "Blunt thoracic aortic injury (BTAI) is the dominant lethal thoracic vascular injury and the board-classic focus of this topic: partial- or full-thickness aortic wall disruption from rapid deceleration, almost always at the aortic isthmus in patients who survive to reach the hospital. The workup is settled — CT angiography is a true one-stop shop that grades the injury and stages associated trauma in the same pass — but the treatment story has moved since the board question was written. TEVAR has replaced open repair as first-line for most grades, and a growing body of evidence now favors delaying repair past 24 hours in a grade 3 injury rather than fixing it immediately, so the competing injuries that so often ride along with BTAI can be stabilized first. This topic also covers the resuscitative thoracotomy criteria and spinal cord ischemia prevention that share this anatomic territory.",
  }, PACKET),
  sourced({
    id: "block-vti-pathophysiology",
    type: "bullets",
    heading: "Definition and pathophysiology",
    items: [
      "BTAI is a partial- or full-thickness aortic wall disruption from rapid deceleration or blunt force, and the dominant lethal thoracic vascular injury.",
      "The **aortic isthmus**, just distal to the left subclavian artery at the ligamentum arteriosum, is the **most common site in survivors reaching the hospital (roughly 90%)**; the aortic root and ascending aorta are more often immediately fatal at the scene.",
      "Injury occurs where the mobile aorta meets fixed anchor points, generating transmural shear, via a **three-force model**: deceleration or shear at tether points, an osseous pinch between the sternum, clavicle, first rib, and vertebral column, and a water-hammer effect from a sudden intraluminal pressure spike.",
      "Etiology, ranked: **motor vehicle collision** is most common, followed by auto-versus-pedestrian, motorcycle crash, falls from height, and crush.",
    ],
  }, PACKET),
  sourced({
    id: "block-vti-epidemiology",
    type: "bullets",
    heading: "Epidemiology and associated injuries",
    items: [
      "Isolated BTAI is exceedingly rare — its presence implies massive kinetic energy, so assume concomitant injuries.",
      "Board pattern of associated injuries: multiple rib fractures, sternal fracture, thoracic spine fracture, and blunt liver or spleen injury; traumatic brain injury and pelvic fracture are the dominant competing hemorrhage risks that alter timing.",
      "Suspect BTAI in any high-speed deceleration, unrestrained occupant, ejection, or steering-wheel or chest-wall impact — **regardless of a normal chest x-ray**.",
    ],
  }, PACKET),
  sourced({
    id: "block-vti-presentation",
    type: "bullets",
    heading: "Clinical presentation",
    items: [
      "Presentation is often nonspecific or obscured by polytrauma and requires a high index of suspicion.",
      "Signs: chest or interscapular pain, dyspnea, chest-wall tenderness or crepitus, **pseudocoarctation** (upper-extremity hypertension with diminished femoral pulses), and a new murmur.",
      "Red flags: hemorrhagic shock, expanding hemothorax, and hoarseness from recurrent laryngeal nerve stretch.",
      "Untreated natural history: high-grade lesions rupture early, and free rupture is rapidly fatal.",
    ],
  }, PACKET),
  sourced({
    id: "block-vti-diagnosis",
    type: "bullets",
    heading: "Diagnosis and workup",
    items: [
      "**CT angiography (CTA) of the chest is the criterion standard**: sensitivity roughly 0.98, specificity roughly 0.97, AUC roughly 1.0, and it stages associated injuries in the same study.",
      "Confirm on contrast-enhanced CTA even when another study already suggests injury.",
      "e-FAST detects hemothorax, pneumothorax, and pericardial effusion or tamponade; pitfall — a false-negative pericardial window occurs when tamponade decompresses into a communicating hemothorax.",
      "Transesophageal echocardiography is an alternative when CTA is not feasible (sensitivity roughly 0.94), limited by availability, operator expertise, and polytrauma positioning.",
      "Conventional angiography is the historical gold standard, now reserved for equivocal cases or intervention.",
    ],
  }, PACKET),
  sourced({
    id: "block-vti-cxr-warning",
    type: "warning",
    tone: "danger",
    heading: "CXR is an unreliable screen — a normal film does not rule out BTAI",
    text: "Classic CXR signs — a widened mediastinum over 8 cm, an apical pleural cap, tracheal or NG-tube rightward deviation, a depressed left mainstem bronchus, loss of the aortic knob, or a left hemothorax — are **low yield**. A widened mediastinum is present in only a minority of confirmed BTAI cases. Any deceleration mechanism with a normal CXR still needs **CTA**.",
  }, PACKET),
  sourced({
    id: "block-vti-staging-table",
    type: "table",
    heading: "SVS BTAI grading (drives treatment)",
    columns: ["Grade", "Lesion", "Default management"],
    rows: [
      ["I", "Intimal tear or flap", "Nonoperative, blood-pressure control, follow-up CTA"],
      ["II", "Intramural hematoma", "Nonoperative if no high-risk features; TEVAR if high-risk features are present"],
      ["III", "Pseudoaneurysm", "TEVAR (repair indicated)"],
      ["IV", "Free rupture or active extravasation", "Immediate repair, TEVAR preferred"],
    ],
  }, PACKET),
  sourced({
    id: "block-vti-high-risk-features",
    type: "bullets",
    heading: "Grade II: high-risk imaging features that push toward TEVAR",
    items: [
      "Posterior mediastinal hematoma **greater than 10 mm**.",
      "Lesion-to-normal aortic diameter ratio **greater than 1.4**.",
      "Mediastinal hematoma with mass effect, pseudocoarctation, a left hemothorax, or arch or great-vessel involvement.",
      "EACTS/STS 2024 corroborates this stratification: grade I is nonoperative, grade II is stratified by these high-risk features, and grade III to IV is operative; ESC 2024 adds timing detail — grade 3 gets semi-elective repair within 24 to 72 hours, grade 4 gets immediate repair.",
    ],
  }, PACKET),
  sourced({
    id: "block-vti-management-flow",
    type: "flow",
    heading: "From suspected BTAI to definitive repair",
    nodes: [
      { id: "present", label: "Suspected BTAI: deceleration mechanism, chest or interscapular pain, pseudocoarctation, or associated high-risk injuries — regardless of a normal CXR" },
      { id: "cta", label: "CT angiography of the chest" },
      { id: "gradeI", label: "Grade I: intimal tear or flap" },
      { id: "gradeII", label: "Grade II: intramural hematoma" },
      { id: "gradeIIlow", label: "No high-risk imaging features" },
      { id: "gradeIIhigh", label: "High-risk imaging features present", tone: "caution" },
      { id: "gradeIII", label: "Grade III: pseudoaneurysm", tone: "caution" },
      { id: "gradeIV", label: "Grade IV: free rupture or active extravasation", tone: "caution" },
      { id: "nonop", label: "Nonoperative: anti-impulse therapy, strict blood-pressure control, serial CTA", tone: "good" },
      { id: "tevar", label: "TEVAR, first-line in anatomically suitable patients", tone: "good" },
      { id: "immediate", label: "Immediate repair, TEVAR preferred", tone: "caution" },
    ],
    edges: [
      { from: "present", to: "cta" },
      { from: "cta", to: "gradeI" },
      { from: "cta", to: "gradeII" },
      { from: "cta", to: "gradeIII" },
      { from: "cta", to: "gradeIV" },
      { from: "gradeI", to: "nonop" },
      { from: "gradeII", to: "gradeIIlow" },
      { from: "gradeII", to: "gradeIIhigh" },
      { from: "gradeIIlow", to: "nonop" },
      { from: "gradeIIhigh", to: "tevar" },
      { from: "gradeIII", to: "tevar" },
      { from: "gradeIV", to: "immediate" },
    ],
  }, PACKET),
  sourced({
    id: "block-vti-medical-therapy",
    type: "bullets",
    heading: "Anti-impulse medical therapy, all grades, before or awaiting repair",
    items: [
      "**Short-acting beta-blocker first (esmolol)**, with a vasodilator added as needed, to blunt dP/dt and prevent rupture.",
      "Board-classic target is SBP 100 to 120 mmHg; guideline targets vary — EACTS/STS specifies SBP under 100 mmHg and heart rate under 100 bpm, while ESC specifies a mean blood pressure not exceeding 80 mmHg. Know that the exact target differs by source.",
      "Avoid aggressive fluid resuscitation, which worsens hemorrhage and hypertension.",
    ],
  }, PACKET),
  sourced({
    id: "block-vti-repair-choice",
    type: "bullets",
    heading: "Definitive repair: TEVAR versus open",
    items: [
      "**TEVAR is first-line for grades III to IV and high-risk grade II** in anatomically suitable patients; registry and meta-analysis data show lower 30-day mortality, spinal cord ischemia, and acute kidney injury versus open repair, though no randomized trial exists.",
      "In-hospital mortality is **7.9% for TEVAR versus 20% for open repair**; 1-year mortality is 8.7% versus 17%.",
      "Open repair — left posterolateral thoracotomy, with left heart bypass as needed — is reserved for unstable patients, TEVAR-unsuitable anatomy, or TEVAR failure; one long-term series reported higher acute kidney injury (47.6% vs 18.9%) and more bowel ischemia with open repair.",
      "Nonoperative management suits grades I to II without high-risk features: strict blood-pressure control plus serial CTA. Most low-grade injuries resolve, many within roughly 8 weeks.",
    ],
  }, PACKET),
  sourced({
    id: "block-vti-timing-board-note",
    type: "prose",
    heading: "Board answer versus current practice: TEVAR timing",
    text: "The classic teaching is to fix BTAI immediately once diagnosed. Current evidence for **grade 3 BTAI points the other way: delayed repair, beyond 24 hours, is associated with lower mortality than early repair (under 24 hours), with a relative risk of roughly 2.04 for early repair**, because delay allows stabilization of competing injuries such as traumatic brain injury or pelvic fracture. The exception runs in the opposite direction in concurrent TBI: very early TEVAR, under 9 hours, increased mortality in that specific combination (12.9% vs 6.5%). Know both directions — delay generally helps grade 3, but extremely early repair in TBI is its own separate hazard rather than the fix for delay's downside.",
  }, PACKET),
  sourced({
    id: "block-vti-lsa",
    type: "bullets",
    heading: "Left subclavian artery and anticoagulation",
    items: [
      "Covering the left subclavian artery without revascularization may increase ischemic events in the arm, posterior circulation, or spinal cord — **revascularize with a carotid-to-subclavian bypass** if symptomatic arm ischemia develops or to protect the cord.",
      "Intraoperative heparin during TEVAR is associated with lower mortality, but this must be balanced against polytrauma bleeding risk.",
    ],
  }, PACKET),
  sourced({
    id: "block-vti-incisions",
    type: "table",
    heading: "Incision selection by target",
    columns: ["Incision", "Reaches"],
    rows: [
      ["Median sternotomy", "Ascending aorta, innominate artery, proximal right subclavian, common carotids, innominate veins"],
      ["Left anterolateral or posterolateral thoracotomy", "Descending thoracic aorta, distal left subclavian artery"],
      ["Clamshell or trapdoor", "Bilateral or combined cervicothoracic exposure"],
    ],
  }, PACKET),
  sourced({
    id: "block-vti-rt",
    type: "bullets",
    heading: "Resuscitative thoracotomy: indications and outcomes",
    items: [
      "Strongly recommended (EAST/WTA): pulseless with **signs of life** after penetrating thoracic trauma.",
      "Conditionally recommended: penetrating extrathoracic trauma with or without signs of life, penetrating thoracic trauma without signs of life, and blunt trauma with signs of life; recommended against in blunt trauma, pulseless, with no signs of life.",
      "Time cutoffs (WTA): CPR under **15 minutes** for penetrating torso trauma, under **10 minutes** for blunt trauma, and under **5 minutes** for penetrating neck or extremity trauma.",
      "Survival: roughly **35% for a penetrating cardiac wound in shock**, roughly 15% for all penetrating injury, and roughly 2% for blunt trauma in shock; isolated cardiac tamponade is the best-outcome indication.",
    ],
  }, PACKET),
  sourced({
    id: "block-vti-massive-hemothorax-warning",
    type: "warning",
    tone: "danger",
    heading: "Massive hemothorax thresholds are a guide, not a rule",
    text: "The board-classic thoracotomy triggers are an **initial chest-tube output of at least 1500 mL, or at least 200 mL/hour for 3 consecutive hours**, though WSES and JOMI variants cite 200 mL/hour for 4 hours. Whichever number is tested, **physiology and hemodynamics override the absolute volume** — a patient who is deteriorating does not need to wait for the number to be reached.",
  }, PACKET),
  sourced({
    id: "block-vti-sci",
    type: "bullets",
    heading: "Spinal cord ischemia prevention",
    items: [
      "A baseline neurologic exam is mandatory before repair; spinal cord ischemia can be immediate or **delayed up to roughly 2 weeks**.",
      "A **CSF drain (Class I, SVS/AHA)** is indicated for high-risk repair or long-segment coverage, defined as coverage over 200 mm or within 20 mm of the celiac artery. Spinal cord perfusion pressure equals mean arterial pressure minus intrathecal CSF pressure, so drain CSF and augment MAP to optimize perfusion.",
      "Delayed paraparesis is managed by **reinserting the CSF drain and raising MAP with vasopressors**.",
    ],
  }, PACKET),
  sourced({
    id: "block-vti-followup",
    type: "bullets",
    heading: "Follow-up and surveillance",
    items: [
      "Post-TEVAR surveillance CTA at **1, 6, and 12 months, then annually, lifelong**, since durability data in young patients with a long graft life ahead remain unknown.",
      "Nonoperative injuries: grade 1 needs no routine follow-up imaging; grade 2 gets a **1-month CTA**.",
      "Endoleak and aneurysm surveillance is mandatory; antiplatelet therapy does not increase endoleak incidence.",
    ],
  }, PACKET),
  sourced({
    id: "block-vti-retained-hemothorax",
    type: "bullets",
    heading: "Retained hemothorax algorithm",
    items: [
      "A CT-confirmed retained hemothorax **over 300 to 500 mL warrants VATS within 72 hours**; VATS, not a second chest tube, is definitive.",
      "Early VATS, within 5 days, achieves roughly **87% resolution with an 11% conversion-to-thoracotomy rate**.",
      "Intrapleural fibrinolytics (tPA with or without DNase) avoid operation in roughly 87% of selected cases, but are reserved for poor surgical candidates because of a longer length of stay (roughly 14.9 days); WSES cautions that lytics may delay resolution in trauma.",
      "Prophylactic antibiotics reduce post-traumatic empyema.",
    ],
  }, PACKET),
  sourced({
    id: "block-vti-pearls",
    type: "bullets",
    heading: "Board pearls",
    items: [
      "The **isthmus** is the number-one site in hospital survivors; ascending aorta or root ruptures kill at the scene.",
      "**CTA has replaced conventional angiography as the current criterion standard.**",
      "If an endograft covers the left subclavian artery and new left-arm ischemia develops, perform a **carotid-to-subclavian bypass**.",
      "A **blunt arrest with no signs of life is not an indication for resuscitative thoracotomy.**",
    ],
  }, PACKET),
  references("block-vti-references", [PACKET]),
];

export const vascularThoracicInjuryTopic = buildTopic({
  id: "00000000-0000-4000-8000-000000001233",
  versionId: "00000000-0000-4000-8000-000000001243",
  slug: "vascular-thoracic-injury",
  title: "Vascular Thoracic Injury",
  aliases: ["blunt thoracic aortic injury", "BTAI", "traumatic aortic injury", "traumatic aortic transection", "aortic isthmus injury", "aortic pseudoaneurysm", "TEVAR", "thoracic endovascular aortic repair", "SVS BTAI grade", "resuscitative thoracotomy", "spinal cord ischemia", "CSF drain", "spinal cord perfusion pressure", "left subclavian artery revascularization", "massive hemothorax", "widened mediastinum", "great vessel injury", "thoracic vascular trauma", "absite", "score"],
  scoreNodeId: "trauma-conditions",
  scoreCategory: "SCORE · Trauma · Diseases & Conditions",
  tags: ["trauma", "vascular", "aorta", "thoracic-trauma", "absite", "score"],
  sourceId: PACKET,
  blocks,
  reviewedAt: "2026-08-21T00:00:00.000Z",
});
