import type { TaxonomyNode } from "@/lib/types";

export const taxonomy: TaxonomyNode[] = [
  { id: "score", title: "SCORE Curriculum", slug: "score", order: 0 },
  { id: "alimentary", title: "Alimentary Tract", slug: "alimentary-tract", parentId: "score", order: 1 },
  { id: "biliary", title: "Biliary Tract", slug: "biliary-tract", parentId: "alimentary", order: 2 },
  { id: "breast", title: "Breast", slug: "breast", parentId: "score", order: 3 },
  { id: "breast-benign", title: "Benign Breast Disease", slug: "benign-breast-disease", parentId: "breast", order: 4 },
  { id: "general-abdomen", title: "General Abdomen", slug: "general-abdomen", parentId: "score", order: 5 },
  { id: "abdomen-conditions", title: "Diseases & Conditions", slug: "abdomen-diseases-conditions", parentId: "general-abdomen", order: 6 },
  { id: "abdomen-procedures", title: "Operations & Procedures", slug: "abdomen-operations-procedures", parentId: "general-abdomen", order: 7 },
  { id: "hernia", title: "Hernia", slug: "hernia", parentId: "score", order: 8 },
  { id: "hernia-conditions", title: "Diseases & Conditions", slug: "hernia-diseases-conditions", parentId: "hernia", order: 9 },
  { id: "hernia-procedures", title: "Operations & Procedures", slug: "hernia-operations-procedures", parentId: "hernia", order: 10 },
  { id: "arterial-disease", title: "Arterial Disease", slug: "arterial-disease", parentId: "score", order: 11 },
  { id: "arterial-conditions", title: "Diseases & Conditions", slug: "arterial-diseases-conditions", parentId: "arterial-disease", order: 12 },
  { id: "arterial-procedures", title: "Operations & Procedures", slug: "arterial-operations-procedures", parentId: "arterial-disease", order: 13 },
  { id: "critical-care", title: "Surgical Critical Care", slug: "surgical-critical-care", parentId: "score", order: 14 },
  { id: "critical-care-conditions", title: "Diseases & Conditions", slug: "critical-care-diseases-conditions", parentId: "critical-care", order: 15 },
  { id: "critical-care-procedures", title: "Operations & Procedures", slug: "critical-care-operations-procedures", parentId: "critical-care", order: 16 },
  { id: "esophagus", title: "Esophagus", slug: "esophagus", parentId: "score", order: 17 },
  { id: "esophagus-conditions", title: "Diseases & Conditions", slug: "esophagus-diseases-conditions", parentId: "esophagus", order: 18 },
  { id: "esophagus-procedures", title: "Operations & Procedures", slug: "esophagus-operations-procedures", parentId: "esophagus", order: 19 },
  { id: "pediatric", title: "Pediatric Surgery", slug: "pediatric-surgery", parentId: "score", order: 20 },
  { id: "pediatric-conditions", title: "Diseases & Conditions", slug: "pediatric-diseases-conditions", parentId: "pediatric", order: 21 },
  { id: "pediatric-procedures", title: "Operations & Procedures", slug: "pediatric-operations-procedures", parentId: "pediatric", order: 22 },
  { id: "trauma", title: "Trauma", slug: "trauma", parentId: "score", order: 23 },
  { id: "trauma-conditions", title: "Diseases & Conditions", slug: "trauma-diseases-conditions", parentId: "trauma", order: 24 },
  { id: "trauma-procedures", title: "Operations & Procedures", slug: "trauma-operations-procedures", parentId: "trauma", order: 25 },
  { id: "small-intestine", title: "Small Intestine", slug: "small-intestine", parentId: "score", order: 26 },
  { id: "small-intestine-conditions", title: "Diseases & Conditions", slug: "small-intestine-diseases-conditions", parentId: "small-intestine", order: 27 },
  { id: "small-intestine-procedures", title: "Operations & Procedures", slug: "small-intestine-operations-procedures", parentId: "small-intestine", order: 28 },
  { id: "large-intestine", title: "Large Intestine", slug: "large-intestine", parentId: "score", order: 29 },
  { id: "large-intestine-conditions", title: "Diseases & Conditions", slug: "large-intestine-diseases-conditions", parentId: "large-intestine", order: 30 },
  { id: "large-intestine-procedures", title: "Operations & Procedures", slug: "large-intestine-operations-procedures", parentId: "large-intestine", order: 31 },
  { id: "vascular-access", title: "Vascular Access", slug: "vascular-access", parentId: "score", order: 32 },
  { id: "vascular-access-conditions", title: "Diseases & Conditions", slug: "vascular-access-diseases-conditions", parentId: "vascular-access", order: 33 },
  { id: "vascular-access-procedures", title: "Operations & Procedures", slug: "vascular-access-operations-procedures", parentId: "vascular-access", order: 34 },
];
