import { buildPlaybook, references, sourced, sourcedUnits } from "@/content/authoring";
import {
  COCHRANE_ANTECOLIC_2022_SOURCE as ANTECOLIC,
  LEOPARD2_SOURCE as LEOPARD,
  PANCREATICODUODENECTOMY_PACKET_SOURCE as PACKET,
  PRESTON_PPH_2024_SOURCE as PRESTON,
  WHIPPLE_OPERATIVE_PACKET_SOURCE as SOURCE,
} from "@/content/sources";
import type { TopicBlock } from "@/lib/types";

const blocks: TopicBlock[] = [
  sourced({
    id: "block-whipple-summary",
    type: "summary",
    heading: "At a glance",
    text: "The open Whipple in twelve steps: nine to resect and three to rebuild. The resection ends with the uncinate dissection off the SMA, the **point of no return**, so resectability has to be settled before the neck is divided and the SMA plane entered. Reconstruction follows the **Child** order on one jejunal limb — pancreaticojejunostomy, hepaticojejunostomy, then gastro- or duodenojejunostomy — and the pancreaticojejunostomy is the anastomosis that fails. Indications, staging, and complication grading are in the pancreaticoduodenectomy topic.",
  }, SOURCE),
  sourced({
    id: "block-whipple-gda",
    type: "warning",
    tone: "danger",
    heading: "Clamp the GDA before you divide it",
    text: "Occlude the **gastroduodenal artery** with a bulldog and confirm the hepatic artery pulse persists, by palpation or Doppler. If the pulse disappears, the liver is living on retrograde flow through the GDA from the SMA, because of **celiac stenosis** — most often **median arcuate ligament** compression. Dividing the GDA then infarcts the liver, stomach, and bile duct. Divide the median arcuate ligament first; if flow does not return, revascularize, or stent the celiac before the operation. And do not clamp anything until the GDA is definitively identified: it can be small, and a clamp on the common or proper hepatic artery, or on an aberrant branch, is catastrophic.",
  }, SOURCE),
  sourced({
    id: "block-whipple-before",
    type: "bullets",
    heading: "Before the incision",
    items: [
      "Resectability confirmed on **pancreatic-protocol CT**, ideally within 4 weeks of surgery and before any biliary stent.",
      "No tissue diagnosis is needed for a classic resectable head mass going straight to surgery; one is mandatory before any neoadjuvant therapy.",
      "Read the CT for the two arterial surprises this operation punishes: a **replaced right hepatic artery** and **celiac stenosis**.",
      "Staging laparoscopy first for borderline disease, a markedly elevated CA 19-9, a large tumor, or equivocal imaging.",
      "A biliary stent only for cholangitis, severe pruritus, a bilirubin above 14.6 mg/dL, an expected delay, or planned neoadjuvant therapy — and a **metal stent** if one is placed.",
    ],
  }, PACKET),
  sourced({
    id: "block-whipple-anatomy",
    type: "bullets",
    heading: "Anatomy to have in your head",
    items: [
      "**Hepatoduodenal ligament**: the common bile duct anterolateral on the patient's right, the proper hepatic artery anteromedial on the left, the portal vein posterior and deep.",
      "**Arterial supply of the head**: the GDA, off the common hepatic, gives the anterior and posterior superior pancreaticoduodenal arteries, which arcade with the **inferior pancreaticoduodenal artery** off the SMA.",
      "**Venous confluence**: the SMV and splenic vein join behind the pancreatic neck to form the portal vein.",
      "The **gastrocolic trunk of Henle** enters the right anterolateral SMV and has to be divided to expose the inferior border of the neck.",
      "About **20%** of patients have a hepatic arterial variant. The commonest is a **replaced or accessory right hepatic artery** from the SMA, running posterolateral to the bile duct and portal vein; find it before the uncinate dissection or the lymphadenectomy.",
      "A **replaced left hepatic artery** from the left gastric runs in the gastrohepatic ligament.",
      "The **left renal vein**, exposed by the extended Kocher, marks the level of the SMA origin.",
    ],
  }, PACKET),
  sourced({
    id: "block-whipple-flow",
    type: "flow",
    heading: "Operative flow",
    nodes: [
      { id: "explore", label: "Explore liver, peritoneum, mesenteric root, and para-aortic nodes", tone: "default" },
      { id: "stop", label: "Distant disease — confirm on frozen section and do not resect", tone: "caution" },
      { id: "kocher", label: "Extended Kocher to the IVC, aorta, and left renal vein", tone: "default" },
      { id: "smv", label: "Lesser sac, find the SMV below the neck, start the tunnel", tone: "default" },
      { id: "duct", label: "Cholecystectomy, divide the hepatic duct, bile duct margin to frozen section", tone: "default" },
      { id: "clamp", label: "Clamp the GDA — hepatic pulse persists?", tone: "default" },
      { id: "mal", label: "Divide the median arcuate ligament, or revascularize", tone: "caution" },
      { id: "gda", label: "Ligate and oversew the GDA", tone: "default" },
      { id: "variant", label: "Classic or pylorus-preserving?", tone: "default" },
      { id: "antrectomy", label: "Stapled antrectomy", tone: "default" },
      { id: "duodenum", label: "Divide the duodenum 2 to 3 cm past the pylorus", tone: "default" },
      { id: "jejunum", label: "Divide the jejunum and pass it under the mesenteric vessels", tone: "default" },
      { id: "neck", label: "Divide the neck over the SMV and portal vein, neck margin to frozen section", tone: "default" },
      { id: "uncinate", label: "Uncinate off the SMV, skeletonize the right side of the SMA", tone: "default" },
      { id: "vein", label: "Tumor still tethered to the SMV or portal vein?", tone: "default" },
      { id: "venous", label: "Venorrhaphy, patch, or segmental vein resection", tone: "caution" },
      { id: "rebuild", label: "Pancreaticojejunostomy, hepaticojejunostomy, gastro- or duodenojejunostomy, drains", tone: "good" },
    ],
    edges: [
      { from: "explore", to: "stop", label: "Distant disease" },
      { from: "explore", to: "kocher", label: "None found" },
      { from: "kocher", to: "smv" },
      { from: "smv", to: "duct" },
      { from: "duct", to: "clamp" },
      { from: "clamp", to: "gda", label: "Yes" },
      { from: "clamp", to: "mal", label: "No" },
      { from: "mal", to: "gda" },
      { from: "gda", to: "variant" },
      { from: "variant", to: "antrectomy", label: "Classic" },
      { from: "variant", to: "duodenum", label: "Pylorus-preserving" },
      { from: "antrectomy", to: "jejunum" },
      { from: "duodenum", to: "jejunum" },
      { from: "jejunum", to: "neck" },
      { from: "neck", to: "uncinate" },
      { from: "uncinate", to: "vein" },
      { from: "vein", to: "venous", label: "Tethered" },
      { from: "vein", to: "rebuild", label: "Free" },
      { from: "venous", to: "rebuild" },
    ],
  }, SOURCE),
  sourced({
    id: "block-whipple-resection",
    type: "sequence",
    heading: "Resection, step by step",
    steps: [
      { title: "Explore and stage", detail: "Through an upper midline or bilateral subcostal incision, inspect the peritoneum, liver, mesenteric root, and para-aortic nodes **before anything irreversible**. Distant disease, including a non-regional node, contraindicates resection whatever the local anatomy. Watch for: low-volume peritoneal or liver disease missed now becomes a futile resection." },
      { title: "Kocher maneuver", detail: "Mobilize the duodenum and pancreatic head medially off the retroperitoneum to expose the **IVC**, aorta, and **left renal vein**; an extended Kocher reaches the SMA origin. Assess the posterior margin and the tumor's relationship to the SMA here. Watch for: aggressive dissection tears the IVC or left renal vein, and timid mobilization makes the uncinate dissection harder later." },
      { title: "Lesser sac and the infrapancreatic SMV", detail: "Divide the gastrocolic ligament, take down the hepatic flexure, and find the **SMV at the inferior border of the neck** by following the middle colic or gastroepiploic veins, then begin the tunnel anterior to the SMV and portal vein. Watch for: the **gastrocolic trunk** and fragile SMV tributaries avulse easily, the classic source of sudden venous bleeding. Tunnel only in a tumor-free plane, and never force a tumor off the SMV." },
      { title: "Cholecystectomy and the hepatic duct", detail: "Take the gallbladder retrograde, loop the common hepatic duct above the cystic duct insertion, divide it, send the **bile duct margin** for frozen section, and clamp the proximal duct to control spillage. Watch for: a **replaced right hepatic artery** from the SMA, present in about 10% to 23%, posterolateral to the bile duct and portal vein. Palpate the posterolateral porta and protect it before clearing lymphatic tissue — injury means hepatic ischemia, an ischemic biliary anastomosis, and liver abscess. A small duct predicts a harder hepaticojejunostomy." },
      { title: "Portal dissection and the GDA", detail: "Clear the hepatoduodenal ligament, trace the common hepatic artery to the **gastroduodenal artery**, clamp-test it, then ligate it and oversew the stump with a suture ligature. Watch for: lost hepatic pulse on clamping, a small GDA that invites a clamp on the wrong vessel, and an un-oversewn stump that a later leak erodes into a pseudoaneurysm." },
      { title: "Divide the stomach or duodenum", detail: "Classic: antrectomy with a stapled gastric division. Pylorus-preserving: divide the duodenum about **2 to 3 cm** past the pylorus, keeping the right gastric artery and the vagal supply. Watch for: a devascularized duodenal cuff leaks, and an ischemic or denervated pylorus empties poorly." },
      { title: "Divide the jejunum", detail: "Divide the proximal jejunum and its mesentery, release the fourth portion of the duodenum from its suspensory ligament, and deliver the duodenojejunal segment **under the mesenteric vessels** to the right. Watch for: the first jejunal branches of the SMV and SMA, and mesenteric tension that devascularizes the limb you need for reconstruction." },
      { title: "Divide the pancreatic neck", detail: "Place hemostatic stay sutures on the superior and inferior borders over the pancreaticoduodenal vessels, then divide the neck over the SMV and portal vein. Cut the **main pancreatic duct** with cold scissors and send the **neck margin** for frozen section. Watch for: bleeding from the vein beneath, so keep vascular control ready; cautery artifact that ruins the frozen section; and a soft gland with a small duct, which marks a high fistula risk and argues for a stent." },
      { title: "Uncinate and SMA dissection", detail: "Separate the head and uncinate from the right side of the SMV and portal vein, then skeletonize the **right lateral border of the SMA** to the adventitia and divide the **inferior pancreaticoduodenal artery**. This clears the SMA margin, the commonest positive margin and the main driver of local recurrence. Watch for: this is the **point of no return**, so confirm resectability first. Uncinate bleeding and SMV injury are the dominant hazards, tumor tethered to the lateral portal vein wall may only declare itself now, and **circumferential** SMA clearance in benign disease denervates the plexus and causes intractable diarrhea." },
    ],
  }, SOURCE),
  sourced({
    id: "block-whipple-reconstruction",
    type: "sequence",
    heading: "Reconstruction, step by step",
    steps: [
      { title: "Pancreaticojejunostomy", detail: "End-to-side **duct-to-mucosa**, two-layer or modified **Blumgart**, is the most widely used. Invagination is an alternative, particularly for a soft gland with a small duct, and pancreaticogastrostomy is another. Place a transanastomotic stent for a small duct or a soft gland. Watch for: this anastomosis is the operation's weak point, and no single technique has proven superior across randomized trials." },
      { title: "Hepaticojejunostomy", detail: "End-to-side on the same limb with fine absorbable monofilament, interrupted for a small or thin duct to limit stricture. Watch for: a thin duct leaks early and strictures late. Protect its arterial supply — the replaced right hepatic artery again — because an ischemic duct is the one that leaks. Bile in the drain usually means a technical failure here." },
      { title: "Gastro- or duodenojejunostomy and drains", detail: "Complete the gastro- or duodenojejunostomy downstream on the same limb. Place drains at the pancreaticojejunostomy and hepaticojejunostomy, and add a **feeding jejunostomy** selectively for a malnourished or high-risk patient. Watch for: afferent-limb kinking or torsion, which feeds delayed gastric emptying." },
    ],
  }, SOURCE),
  sourced({
    id: "block-whipple-layout",
    type: "table",
    heading: "↳ Where each anastomosis goes",
    columns: ["Anastomosis", "Position on the limb", "Technique"],
    rows: [
      ["**Pancreaticojejunostomy**", "First and most proximal", "Duct-to-mucosa or invagination"],
      ["**Hepaticojejunostomy**", "About **5 to 10 cm** beyond the pancreaticojejunostomy", "Single layer, absorbable suture"],
      ["**Gastro- or duodenojejunostomy**", "About **30 to 40 cm** beyond the hepaticojejunostomy", "The distance keeps bile and pancreatic juice from refluxing into the stomach"],
    ],
  }, PACKET),
  sourced({
    id: "block-whipple-route",
    type: "prose",
    heading: "↳ Antecolic or retrocolic",
    text: "An **antecolic** gastro- or duodenojejunostomy is often favored on the reasoning that it keeps the anastomosis away from a pancreatic leak and so empties better. The randomized evidence does not bear that out: a 2022 Cochrane review of **8 trials** and **818 patients** found no clear difference in delayed gastric emptying by route. Choose by preference and by what lies without tension.",
  }, ANTECOLIC),
  sourcedUnits({
    id: "block-whipple-variants",
    type: "bullets",
    heading: "↳ Minimally invasive and artery-first variants",
    items: [
      "Laparoscopic and robotic pancreatoduodenectomy reach complication rates comparable to open, with less blood loss and a shorter stay, at expert high-volume centers. Neither is yet a universal standard.",
      "**LEOPARD-2**, the Dutch randomized trial of laparoscopic against open, was stopped early when complication-related mortality reached **10%** in the laparoscopic arm against **2%** open.",
      "The **artery-first**, or mesenteric, approach takes the SMA plane at the start, to call resectability early and clear the SMA margin. Meta-analyses suggest higher R0 rates and less blood loss, but the **MAPLE-PD** randomized trial found no survival difference.",
      "**Venous resection** at experienced centers is an accepted extension of the standard operation when it achieves R0. **Arterial resection** remains selective and center-restricted, usually after extended neoadjuvant therapy with an objective response.",
    ],
  }, [[SOURCE], [LEOPARD], [SOURCE], [SOURCE]]),
  sourcedUnits({
    id: "block-whipple-postop",
    type: "bullets",
    heading: "The first two weeks",
    items: [
      "Drain amylase **over 3 times** the serum upper limit from day 3 onward is a pancreatic fistula. Routine wide drainage is being challenged by selective strategies with early, amylase-guided drain removal.",
      "Bilious drain output points at the **hepaticojejunostomy**. Observe a small, asymptomatic leak; drain a larger or symptomatic one percutaneously, adding endoscopic or transhepatic decompression as needed.",
      "A nasogastric tube still needed after day 3: get a CT for a **collection** before calling it gastroparesis.",
      "A small bleed into a drain or the gut in the second week is a **sentinel bleed** — CT angiography, then embolization or a covered stent, not observation and not reoperation.",
      "The GDA stump is not the only suspect: in more than 3,000 resections it was the source in only **16.7%** of hemorrhages, and empiric GDA embolization without a visible source caused morbidity and rebleeding.",
    ],
  }, [[SOURCE], [PACKET], [PACKET], [PACKET], [PRESTON]]),
  references("block-whipple-references", [SOURCE, PACKET, PRESTON, ANTECOLIC, LEOPARD]),
];

export const openPancreaticoduodenectomyPlaybook = buildPlaybook({
  id: "00000000-0000-4000-9000-000000000011",
  slug: "open-pancreaticoduodenectomy",
  title: "Open Pancreaticoduodenectomy",
  aliases: ["Whipple", "Open Whipple", "Whipple procedure", "Pancreatoduodenectomy", "Pylorus-preserving pancreaticoduodenectomy", "PPPD", "GDA clamp test"],
  procedureId: "open_pancreaticoduodenectomy",
  approach: "open",
  specialty: "Hepatobiliary",
  tags: ["hepatobiliary", "pancreas", "open", "surgical oncology", "Whipple"],
  sourceId: SOURCE,
  additionalSourceIds: [PACKET, PRESTON, ANTECOLIC, LEOPARD],
  relatedTopicSlugs: ["pancreaticoduodenectomy"],
  blocks,
  reviewedAt: "2026-10-04T00:00:00.000Z",
});
